/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)'],
        serif: ['var(--font-serif)'],
        body: ['var(--font-sans)'],
        display: ['var(--font-serif)'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '20px',
        '3xl': '24px',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        ocean: {
          deep: 'hsl(var(--ocean-deep))',
          mid: 'hsl(var(--ocean-mid))',
          surface: 'hsl(var(--ocean-surface))',
        },
        fog: 'hsl(var(--fog))',
        moonlight: 'hsl(var(--moonlight))',
        sand: {
          warm: 'hsl(var(--sand-warm))',
          soft: 'hsl(var(--sand-soft))',
        },
        'sea-glass': {
          DEFAULT: 'hsl(var(--sea-glass))',
          dim: 'hsl(var(--sea-glass-dim))',
        },
        tide: 'hsl(var(--tide-blue))',
        mist: 'hsl(var(--mist-blue))',
        ember: 'hsl(var(--ember))',
        safety: 'hsl(var(--safety-green))',
        glass: {
          bg: 'hsl(var(--glass-bg))',
          border: 'hsl(var(--glass-border))',
        },
        'truth-glow': 'hsl(var(--truth-glow))',
        harbor: {
          deep: 'hsl(var(--harbor-deep))',
          sage: 'hsl(var(--harbor-sage))',
          amber: 'hsl(var(--harbor-amber))',
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'breathe-in': { '0%': { transform: 'scale(0.6)', opacity: '0.4' }, '100%': { transform: 'scale(1)', opacity: '0.8' } },
        'breathe-out': { '0%': { transform: 'scale(1)', opacity: '0.8' }, '100%': { transform: 'scale(0.6)', opacity: '0.4' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        'glow-pulse': { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '0.8' } },
        'wave-drift': { '0%': { transform: 'translateX(0) scaleY(1)' }, '50%': { transform: 'translateX(-10px) scaleY(1.05)' }, '100%': { transform: 'translateX(0) scaleY(1)' } },
        'truth-reveal': { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'breathe-in': 'breathe-in 4s ease-in-out',
        'breathe-out': 'breathe-out 4s ease-in-out',
        'float': 'float 6s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 4s ease-in-out infinite',
        'wave-drift': 'wave-drift 8s ease-in-out infinite',
        'truth-reveal': 'truth-reveal 0.8s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
