// Generated by Miravelys story-driven website content pass.

export const experienceCopy = {
  "en": {
    "scenarios": {
      "eyebrow": "Where Miravelys helps",
      "title": "The app is designed around real moments, not perfect routines.",
      "intro": "Miravelys begins where ordinary emotional moments actually happen: before sleep, after a message that hurt, during a conversation that keeps replaying, or after a week that quietly showed you something.",
      "items": [
        {
          "title": "When one message becomes a whole story",
          "body": "Write the raw thought. Miravelys helps separate the words in the message from the meaning your mind added around them.",
          "tag": "Get Clear"
        },
        {
          "title": "When your body is too loud to think clearly",
          "body": "The app can pause inquiry and guide you into Calm Now first, so the body is not forced to solve a story while activated.",
          "tag": "Calm Now"
        },
        {
          "title": "When night makes everything feel heavier",
          "body": "Sleep Now keeps the tone softer, helps park the loop, and avoids dragging you into heavy analysis before bed.",
          "tag": "Sleep Now"
        },
        {
          "title": "When the same belief keeps returning",
          "body": "Weekly Mirror reflects patterns only with enough evidence, and every reflection stays editable, humble, and correctable.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Emotional proof without fake hype",
      "title": "The promise is small, believable, and repeatable.",
      "intro": "These moment cards show the kind of shift Miravelys is built to support: from one fused emotional truth toward a smaller, kinder, more specific next step.",
      "items": [
        {
          "before": "Before: “I know I’m overreacting, but it still feels completely true.”",
          "after": "After: “Part of this is a feeling. Part is a story. I can answer the fact, not the fear.”"
        },
        {
          "before": "Before: “If I sleep now, I’ll lose control of the problem.”",
          "after": "After: “I wrote the next step down. I can let the night be night.”"
        },
        {
          "before": "Before: “This keeps happening, so maybe this is just who I am.”",
          "after": "After: “This pattern appeared more than once. It is information, not an identity.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Clear positioning",
      "title": "Miravelys is not trying to be everything. That is part of the trust.",
      "intro": "Clear boundaries are part of the trust. Miravelys explains what it supports — reflection, grounding, pattern awareness — and what it does not claim to do.",
      "items": [
        {
          "title": "Not a diary that stores everything forever",
          "body": "It is a guided clarity space. You can keep, correct, hide, or delete what does not fit."
        },
        {
          "title": "Not therapy, diagnosis, or spiritual certainty",
          "body": "It does not name your wounds, label your identity, or claim absolute truth about you."
        },
        {
          "title": "Not a streak machine",
          "body": "No guilt loops, no manipulative urgency, no fake productivity pressure. Return because it helps, not because it shames you."
        },
        {
          "title": "A private understanding companion",
          "body": "It helps you notice what is real, what is added, what calms you, and what actually supports your next step."
        }
      ]
    },
    "beta": {
      "eyebrow": "A softer way to begin",
      "title": "Start with one honest line. The app can meet you there.",
      "body": "Join early access for launch updates and private beta news. The invitation is calm on purpose: no pressure, no streaks, no emotional urgency.",
      "placeholder": "Email for launch updates",
      "button": "Join early access",
      "success": "Thank you — your launch request was saved on this device. If the mail app opened, send the message so we can receive it.",
      "emailError": "Please enter a valid email address.",
      "mailtoSubject": "Miravelys early access",
      "mailtoBody": "Please add {email} to Miravelys early access updates.",
      "privacy": "No pressure, no spam tone, no emotional manipulation. Just product updates when Miravelys is ready."
    },
    "sticky": {
      "appStore": "Download Miravelys",
      "mockups": "Inside the app",
      "explore": "Begin with one clear moment",
      "earlyAccess": "Join early access",
      "privacy": "How privacy works"
    }
  },
  "ru": {
    "scenarios": {
      "eyebrow": "Где помогает Miravelys",
      "title": "Приложение создано вокруг реальных моментов, а не идеальных привычек.",
      "intro": "Miravelys начинается там, где обычные эмоциональные моменты действительно происходят: перед сном, после зацепившего сообщения, во время разговора, который снова прокручивается, или после недели, которая тихо что-то показала.",
      "items": [
        {
          "title": "Когда одно сообщение превращается в целую историю",
          "body": "Запиши сырую мысль. Miravelys помогает отделить слова в сообщении от смысла, который ум добавил вокруг них.",
          "tag": "Get Clear"
        },
        {
          "title": "Когда тело слишком громкое, чтобы ясно думать",
          "body": "Приложение может остановить inquiry и сначала направить в Calm Now, чтобы тело не пыталось решать историю в состоянии напряжения.",
          "tag": "Calm Now"
        },
        {
          "title": "Когда ночью всё кажется тяжелее",
          "body": "Sleep Now делает тон мягче, помогает отложить петлю мыслей и не втягивает в тяжёлый анализ перед сном.",
          "tag": "Sleep Now"
        },
        {
          "title": "Когда одно и то же убеждение возвращается снова",
          "body": "Weekly Mirror показывает паттерны только при достаточных доказательствах, а любое отражение остаётся редактируемым, скромным и исправляемым.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Эмоциональное доказательство без фальшивого хайпа",
      "title": "Обещание маленькое, правдоподобное и повторяемое.",
      "intro": "Эти карточки показывают сдвиг, который Miravelys должен поддерживать: от слитого эмоционального «это правда» к более маленькому, доброму и конкретному следующему шагу.",
      "items": [
        {
          "before": "До: «Я понимаю, что, возможно, преувеличиваю, но это всё равно кажется полностью правдой».",
          "after": "После: «Часть этого — чувство. Часть — история. Я могу ответить на факт, а не на страх».",
        },
        {
          "before": "До: «Если я сейчас усну, я потеряю контроль над проблемой».",
          "after": "После: «Я записал следующий шаг. Ночь может быть ночью».",
        },
        {
          "before": "До: «Это повторяется, значит, наверное, это просто я такой».",
          "after": "После: «Этот паттерн появлялся не раз. Это информация, а не личность».",
        }
      ]
    },
    "positioning": {
      "eyebrow": "Ясное позиционирование",
      "title": "Miravelys не пытается быть всем сразу. В этом и есть часть доверия.",
      "intro": "Чёткие границы — часть доверия. Miravelys объясняет, что поддерживает: размышление, заземление, замечание паттернов, — и чего не обещает.",
      "items": [
        {
          "title": "Не дневник, который хранит всё навсегда",
          "body": "Это направляемое пространство ясности. Ты можешь оставить, исправить, скрыть или удалить то, что не подходит."
        },
        {
          "title": "Не терапия, диагноз и не духовная окончательность",
          "body": "Приложение не называет твою рану, не навешивает ярлык личности и не заявляет абсолютную правду о тебе."
        },
        {
          "title": "Не машина стриков",
          "body": "Без чувства вины, манипулятивной срочности и фальшивого давления продуктивности. Возвращайся потому, что помогает, а не потому, что стыдно."
        },
        {
          "title": "Приватный спутник понимания",
          "body": "Он помогает замечать, что реально, что добавлено умом, что тебя успокаивает и что действительно поддерживает следующий шаг."
        }
      ]
    },
    "beta": {
      "eyebrow": "Более мягкое начало",
      "title": "Начни с одной честной строки. Приложение встретит тебя там.",
      "body": "Присоединяйтесь к раннему доступу, чтобы получать новости запуска и приватной беты. Приглашение намеренно спокойное: без давления, streaks и эмоциональной срочности.",
      "placeholder": "Email для новостей о запуске",
      "button": "Присоединиться",
      "success": "Спасибо — запрос на запуск сохранён на этом устройстве. Если открылось почтовое приложение, отправьте письмо, чтобы мы его получили.",
      "privacy": "Без давления, спама и эмоциональных манипуляций. Только новости продукта, когда Miravelys будет готов.",
      "emailError": "Введите корректный адрес электронной почты.",
      "mailtoSubject": "Ранний доступ Miravelys",
      "mailtoBody": "Добавьте, пожалуйста, {email} в список раннего доступа Miravelys."
    },
    "sticky": {
      "appStore": "Скачать Miravelys",
      "mockups": "Внутри приложения",
      "explore": "Начни с одного ясного момента",
      "earlyAccess": "Ранний доступ",
      "privacy": "Как работает приватность"
    }
  },
  "ro": {
    "scenarios": {
      "eyebrow": "Unde ajută Miravelys",
      "title": "Aplicația este construită pentru momente reale, nu pentru rutine perfecte.",
      "intro": "Miravelys începe acolo unde apar de fapt momentele emoționale obișnuite: înainte de somn, după un mesaj care a durut, în urma unei conversații care se repetă în minte sau după o săptămână care ți-a arătat ceva în liniște.",
      "items": [
        {
          "title": "Când un mesaj devine o poveste întreagă",
          "body": "Scrie gândul brut. Miravelys te ajută să separi cuvintele din mesaj de sensul pe care mintea l-a adăugat în jurul lor.",
          "tag": "Get Clear"
        },
        {
          "title": "Când corpul este prea zgomotos ca să gândești clar",
          "body": "Aplicația poate opri inquiry-ul și te poate duce întâi în Calm Now, ca trupul să nu fie forțat să rezolve o poveste când este activat.",
          "tag": "Calm Now"
        },
        {
          "title": "Când noaptea face totul să pară mai greu",
          "body": "Sleep Now păstrează tonul mai blând, te ajută să lași bucla deoparte și evită analiza grea înainte de culcare.",
          "tag": "Sleep Now"
        },
        {
          "title": "Când aceeași convingere revine",
          "body": "Weekly Mirror reflectă tipare doar cu suficiente dovezi, iar fiecare reflecție rămâne editabilă, modestă și corectabilă.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Dovadă emoțională fără exagerare falsă",
      "title": "Promisiunea este mică, credibilă și repetabilă.",
      "intro": "Aceste carduri arată schimbarea pe care Miravelys este construit să o susțină: de la un adevăr emoțional amestecat la un pas următor mai mic, mai blând și mai precis.",
      "items": [
        {
          "before": "Înainte: „Știu că poate exagerez, dar tot se simte complet adevărat.”",
          "after": "După: „O parte este emoție. O parte este poveste. Pot răspunde faptului, nu fricii.”"
        },
        {
          "before": "Înainte: „Dacă adorm acum, pierd controlul asupra problemei.”",
          "after": "După: „Am scris următorul pas. Pot lăsa noaptea să fie noapte.”"
        },
        {
          "before": "Înainte: „Se tot repetă, deci poate asta sunt eu.”",
          "after": "După: \"Acest tipar a apărut de mai multe ori. Este informație, nu identitate.\"",
        }
      ]
    },
    "positioning": {
      "eyebrow": "Poziționare clară",
      "title": "Miravelys nu încearcă să fie totul. Asta face parte din încredere.",
      "intro": "Granițele clare fac parte din încredere. Miravelys explică ce susține — reflecție, ancorare, observarea tiparelor — și ce nu pretinde să facă.",
      "items": [
        {
          "title": "Nu este un jurnal care păstrează totul pentru totdeauna",
          "body": "Este un spațiu ghidat de claritate. Poți păstra, corecta, ascunde sau șterge ce nu se potrivește."
        },
        {
          "title": "Nu este terapie, diagnostic sau certitudine spirituală",
          "body": "Nu numește rănile, nu etichetează identitatea și nu pretinde adevăr absolut despre tine."
        },
        {
          "title": "Nu este o mașină de streak-uri",
          "body": "Fără vinovăție, urgență manipulativă sau presiune falsă de productivitate. Revii pentru că ajută, nu pentru că te rușinează."
        },
        {
          "title": "Un companion privat de înțelegere",
          "body": "Te ajută să observi ce este real, ce este adăugat, ce te calmează și ce îți susține cu adevărat următorul pas."
        }
      ]
    },
    "beta": {
      "eyebrow": "Un început mai blând",
      "title": "Începe cu o singură propoziție sinceră. Aplicația te poate întâlni acolo.",
      "body": "Intră în accesul timpuriu pentru noutăți despre lansare și beta privată. Invitația rămâne calmă intenționat: fără presiune, fără streak-uri, fără urgență emoțională.",
      "placeholder": "Email pentru noutăți despre lansare",
      "button": "Intră în acces timpuriu",
      "success": "Mulțumim — cererea ta a fost salvată pe acest dispozitiv. Dacă s-a deschis aplicația de email, trimite mesajul ca să îl primim.",
      "privacy": "Fără presiune, fără spam, fără manipulare emoțională. Doar noutăți despre produs când Miravelys este gata.",
      "emailError": "Introdu o adresă de email validă.",
      "mailtoSubject": "Acces timpuriu Miravelys",
      "mailtoBody": "Te rog adaugă {email} la actualizările de acces timpuriu Miravelys."
    },
    "sticky": {
      "appStore": "Descarcă Miravelys",
      "mockups": "În aplicație",
      "explore": "Începe cu un moment clar",
      "earlyAccess": "Acces timpuriu",
      "privacy": "Cum funcționează confidențialitatea"
    }
  },
  "fr": {
    "scenarios": {
      "eyebrow": "Là où Miravelys aide",
      "title": "L’application est conçue autour de vrais moments, pas de routines parfaites.",
      "intro": "Miravelys commence là où les moments émotionnels ordinaires arrivent vraiment : avant de dormir, après un message qui a blessé, après une conversation qui tourne encore, ou après une semaine qui a discrètement montré quelque chose.",
      "items": [
        {
          "title": "Quand un message devient toute une histoire",
          "body": "Écrivez la pensée brute. Miravelys aide à séparer les mots du message du sens que l’esprit a ajouté autour d’eux.",
          "tag": "Get Clear"
        },
        {
          "title": "Quand le corps est trop bruyant pour penser clairement",
          "body": "L’application peut mettre l’exploration en pause et vous guider d’abord vers Calm Now, pour ne pas forcer le corps à résoudre une histoire en état d’activation.",
          "tag": "Calm Now"
        },
        {
          "title": "Quand la nuit rend tout plus lourd",
          "body": "Sleep Now garde un ton plus doux, aide à poser la boucle de pensée, et évite de lancer une analyse lourde avant le coucher.",
          "tag": "Sleep Now"
        },
        {
          "title": "Quand la même croyance revient",
          "body": "Weekly Mirror reflète les schémas seulement avec assez de preuves, et chaque reflet reste modifiable, humble et corrigeable.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Preuve émotionnelle sans fausse exagération",
      "title": "La promesse est petite, crédible et répétable.",
      "intro": "Ces cartes montrent le changement que Miravelys cherche à soutenir : passer d’une vérité émotionnelle mélangée à un prochain pas plus petit, plus doux et plus précis.",
      "items": [
        {
          "before": "Avant : « Je sais que j’exagère peut-être, mais ça semble totalement vrai. »",
          "after": "Après : « Une partie est une émotion. Une partie est une histoire. Je peux répondre au fait, pas à la peur. »"
        },
        {
          "before": "Avant : « Si je dors maintenant, je perds le contrôle du problème. »",
          "after": "Après : « J’ai écrit la prochaine étape. Je peux laisser la nuit être la nuit. »"
        },
        {
          "before": "Avant : « Ça revient sans cesse, donc c’est peut-être juste qui je suis. »",
          "after": "Après : « Ce schéma est apparu plus d’une fois. C’est une information, pas une identité. »"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Positionnement clair",
      "title": "Miravelys n’essaie pas d’être tout. C’est aussi ce qui le rend digne de confiance.",
      "intro": "Des limites claires font partie de la confiance. Miravelys explique ce qu’il soutient — réflexion, ancrage, attention aux motifs — et ce qu’il ne prétend pas faire.",
      "items": [
        {
          "title": "Pas un journal qui garde tout pour toujours",
          "body": "C’est un espace guidé de clarté. Vous pouvez garder, corriger, masquer ou supprimer ce qui ne vous correspond pas."
        },
        {
          "title": "Pas une thérapie, un diagnostic ou une certitude spirituelle",
          "body": "Il ne nomme pas vos blessures, ne colle pas d’étiquette identitaire et ne prétend pas connaître une vérité absolue sur vous."
        },
        {
          "title": "Pas une machine à séries",
          "body": "Pas de culpabilité, pas d’urgence manipulatrice, pas de fausse pression de productivité. Revenez parce que cela aide, pas parce que cela vous fait honte."
        },
        {
          "title": "Un compagnon privé de compréhension",
          "body": "Il aide à voir ce qui est réel, ce qui est ajouté, ce qui vous apaise et ce qui soutient vraiment votre prochain pas."
        }
      ]
    },
    "beta": {
      "eyebrow": "Une manière plus douce de commencer",
      "title": "Commencez par une seule phrase honnête. L’application peut vous rejoindre là.",
      "body": "Rejoins l’accès anticipé pour recevoir les nouvelles du lancement et de la bêta privée. L’invitation reste volontairement calme : pas de pression, pas de séries, pas d’urgence émotionnelle.",
      "placeholder": "E-mail pour les nouvelles du lancement",
      "button": "Rejoindre l’accès anticipé",
      "success": "Merci — ta demande de lancement a été enregistrée sur cet appareil. Si l’app Mail s’est ouverte, envoie le message pour que nous le recevions.",
      "privacy": "Pas de pression, pas de spam, pas de manipulation émotionnelle. Seulement des nouvelles du produit quand Miravelys sera prêt.",
      "emailError": "Saisis une adresse e-mail valide.",
      "mailtoSubject": "Accès anticipé Miravelys",
      "mailtoBody": "Merci d'ajouter {email} aux mises à jour d'accès anticipé Miravelys."
    },
    "sticky": {
      "appStore": "Télécharger Miravelys",
      "mockups": "Dans l’app",
      "explore": "Commence par un moment clair",
      "earlyAccess": "Accès anticipé",
      "privacy": "Comment fonctionne la confidentialité"
    }
  },
  "hi": {
    "scenarios": {
      "eyebrow": "Miravelys कहाँ मदद करता है",
      "title": "ऐप perfect routines के लिए नहीं, real moments के लिए बनाया गया है।",
      "intro": "Miravelys वहीं शुरू होता है जहाँ रोज़मर्रा के भावनात्मक पल सच में आते हैं: सोने से पहले, किसी चोट पहुँचाने वाले message के बाद, replay होती conversation के बीच, या ऐसी week के बाद जिसने चुपचाप कुछ दिखाया।",
      "items": [
        {
          "title": "जब एक message पूरी कहानी बन जाता है",
          "body": "कच्चा thought लिखें। Miravelys आपके लिखे words और मन द्वारा जोड़े गए meaning को अलग देखने में मदद करता है।",
          "tag": "Get Clear"
        },
        {
          "title": "जब body इतनी loud हो कि साफ़ सोचना मुश्किल हो",
          "body": "ऐप inquiry को pause करके पहले Calm Now में ले जा सकता है, ताकि activated body को story solve करने के लिए force न किया जाए।",
          "tag": "Calm Now"
        },
        {
          "title": "जब रात हर चीज़ को भारी बना देती है",
          "body": "Sleep Now tone को softer रखता है, loop को park करने में मदद करता है और सोने से पहले heavy analysis में नहीं खींचता।",
          "tag": "Sleep Now"
        },
        {
          "title": "जब वही belief बार-बार लौटता है",
          "body": "Weekly Mirror patterns को तभी दिखाता है जब enough evidence हो, और हर reflection editable, humble और correctable रहता है।",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Fake hype के बिना emotional proof",
      "title": "Promise छोटा, believable और repeatable है।",
      "intro": "ये moment cards वह बदलाव दिखाते हैं जिसे Miravelys support करना चाहता है: एक fused emotional truth से छोटे, नरम और ज़्यादा specific next step तक।",
      "items": [
        {
          "before": "पहले: “मुझे पता है शायद मैं overreact कर रहा/रही हूँ, लेकिन यह अभी पूरी तरह सच लगता है।",
          "after": "बाद में: “इसका एक हिस्सा feeling है। एक हिस्सा story है। मैं fear नहीं, fact को जवाब दे सकता/सकती हूँ।"
        },
        {
          "before": "पहले: “अगर मैं अभी सो गया/गई, तो problem पर control खो दूँगा/दूँगी।",
          "after": "बाद में: “मैंने अगला कदम लिख लिया। मैं रात को रात होने दे सकता/सकती हूँ।"
        },
        {
          "before": "पहले: “यह फिर हो रहा है। शायद मैं ऐसी/ऐसा ही हूँ।",
          "after": "बाद में: “यह pattern एक से ज़्यादा बार आया। यह information है, identity नहीं।"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Clear positioning",
      "title": "Miravelys हर चीज़ बनने की कोशिश नहीं करता। यही trust का हिस्सा है।",
      "intro": "Clear boundaries trust का हिस्सा हैं। Miravelys बताता है कि यह क्या support करता है — reflection, grounding, pattern awareness — और क्या claim नहीं करता।",
      "items": [
        {
          "title": "यह कोई ऐसा diary नहीं जो सब कुछ हमेशा के लिए रखे",
          "body": "यह एक guided clarity space है। आप जो fit नहीं होता उसे रख, correct, hide या delete कर सकते हैं।"
        },
        {
          "title": "यह therapy, diagnosis या spiritual certainty नहीं है",
          "body": "यह आपके दर्द को नाम नहीं देता, आपकी identity को label नहीं करता, और आपके बारे में absolute truth claim नहीं करता।"
        },
        {
          "title": "यह कोई streak machine नहीं है",
          "body": "No guilt loops, no manipulative urgency, no fake productivity pressure। वापस इसलिए आएँ क्योंकि यह मदद करता है, न कि शर्मिंदा करने के लिए।"
        },
        {
          "title": "एक private understanding companion",
          "body": "यह आपको यह notice करने में मदद करता है कि क्या real है, क्या added है, क्या आपको शांत करता है, और आपके अगले कदम को असल में क्या support करता है।"
        }
      ]
    },
    "beta": {
      "eyebrow": "एक नरम शुरुआत",
      "title": "एक honest line से शुरू करें। ऐप वहीं आपसे मिल सकता है।",
      "body": "Launch updates और private beta news के लिए early access में शामिल हों। यह invitation जानबूझकर शांत है: कोई दबाव नहीं, कोई streak नहीं, कोई emotional urgency नहीं।",
      "placeholder": "Email for launch updates",
      "button": "Join early access",
      "success": "Thank you — your launch request was saved on this device. If the mail app opened, send the message so we can receive it.",
      "emailError": "Please enter a valid email address.",
      "mailtoSubject": "Miravelys early access",
      "mailtoBody": "Please add {email} to Miravelys early access updates.",
      "privacy": "No pressure, no spam tone, no emotional manipulation. Just product updates when Miravelys is ready."
    },
    "sticky": {
      "appStore": "Miravelys डाउनलोड करें",
      "mockups": "ऐप के अंदर",
      "explore": "एक clear moment से शुरू करें",
      "earlyAccess": "Early access",
      "privacy": "Privacy कैसे काम करती है"
    }
  },
  "zh": {
    "scenarios": {
      "eyebrow": "Miravelys 在哪些地方有帮助",
      "title": "这个应用为真实时刻而设计，不是为完美的日常习惯。",
      "intro": "Miravelys 从那些真实的情绪瞬间开始：睡前、一条刺痛你的消息之后、一段反复重播的对话之后，或者某一周安静地让你看见了什么之后。",
      "items": [
        {
          "title": "当一条消息变成一整套故事",
          "body": "写下最原始的念头。Miravelys 帮你把消息里的文字和头脑围绕它添加的意义分开。",
          "tag": "Get Clear"
        },
        {
          "title": "当身体太吵，无法清晰思考",
          "body": "应用可以暂停探询，先引导你进入 Calm Now，让身体不必在激活状态下试图解决一个故事。",
          "tag": "Calm Now"
        },
        {
          "title": "当夜晚让一切都变重",
          "body": "Sleep Now 保持更柔软的语气，帮你把循环的念头先放一放，避免睡前陷入沉重的分析。",
          "tag": "Sleep Now"
        },
        {
          "title": "当同一个信念反复出现",
          "body": "Weekly Mirror 只在有足够依据时反映模式，而且每一次反映都可编辑、谦逊、可修正。",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "没有虚假炒作的情绪证明",
      "title": "这个承诺很小、可信、可重复。",
      "intro": "这些时刻卡片展示了 Miravelys 旨在支持的那种转变：从一种融合的情绪真实，转向一个更小、更温柔、更具体的下一步。",
      "items": [
        {
          "before": "之前：“我知道我可能反应过度，但它现在仍然感觉很真实。”",
          "after": "之后：“一部分是感受，一部分是故事。我可以回应事实，而不是恐惧。”"
        },
        {
          "before": "之前：“如果我现在睡觉，我会失去对问题的控制。”",
          "after": "之后：“我把下一步写下来了。我可以让夜晚只是夜晚。”"
        },
        {
          "before": "之前：“这件事反复发生，所以也许这就是我。”",
          "after": "之后：“这个模式出现了不止一次。它是信息，不是身份。”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "清晰的定位",
      "title": "Miravelys 不想做所有的事情。这正是信任的一部分。",
      "intro": "清晰的边界是信任的一部分。Miravelys 说明它支持什么——反思、 grounding、模式觉察——以及它不声称做什么。",
      "items": [
        {
          "title": "不是永久储存一切的日记",
          "body": "它是一个引导式的清晰空间。你可以保留、修正、隐藏或删除不适合的内容。"
        },
        {
          "title": "不是治疗、诊断或灵性确定性",
          "body": "它不会命名你的伤口，不会给你的身份贴标签，也不会声称对你有绝对真理。"
        },
        {
          "title": "不是打卡机器",
          "body": "没有内疚循环，没有操纵性的紧迫感，没有虚假的生产力压力。回来是因为它有帮助，而不是因为它让你羞耻。"
        },
        {
          "title": "一个私密的理解陪伴",
          "body": "它帮助你留意什么是真实的、什么是添加的、什么让你平静，以及什么真正支持你的下一步。"
        }
      ]
    },
    "beta": {
      "eyebrow": "一种更柔软的开始方式",
      "title": "从一句诚实的话开始。应用可以在那里与你相遇。",
      "body": "加入早期访问，获取发布更新和私人测试版消息。这份邀请 deliberately 平静：没有压力，没有打卡，没有情绪上的紧迫感。",
      "placeholder": "用于发布更新的邮箱",
      "button": "加入早期访问",
      "success": "谢谢——你的发布请求已保存在这台设备上。如果邮件应用已打开，请发送邮件以便我们收到。",
      "emailError": "请输入有效的电子邮箱地址。",
      "mailtoSubject": "Miravelys 早期访问",
      "mailtoBody": "请将 {email} 添加到 Miravelys 早期访问更新列表。",
      "privacy": "没有压力，没有垃圾邮件语气，没有情绪操控。只在 Miravelys 准备好时发送产品更新。"
    },
    "sticky": {
      "appStore": "下载 Miravelys",
      "mockups": "应用内体验",
      "explore": "从一个清晰时刻开始",
      "earlyAccess": "早期访问",
      "privacy": "隐私如何运作"
    }
  },
  "de": {
    "scenarios": {
      "eyebrow": "Wo Miravelys hilft",
      "title": "Die App ist für echte Momente gebaut, nicht für perfekte Routinen.",
      "intro": "Miravelys beginnt dort, wo gewöhnliche emotionale Momente tatsächlich passieren: vor dem Schlafen, nach einer verletzenden Nachricht, während eines Gesprächs, das immer wieder abgespielt wird, oder nach einer Woche, die dir leise etwas gezeigt hat.",
      "items": [
        {
          "title": "Wenn eine Nachricht zur ganzen Geschichte wird",
          "body": "Schreibe den rohen Gedanken auf. Miravelys hilft, die Worte in der Nachricht von der Bedeutung zu trennen, die der Verstand darumgelegt hat.",
          "tag": "Get Clear"
        },
        {
          "title": "Wenn der Körper zu laut ist, um klar zu denken",
          "body": "Die App kann die Untersuchung pausieren und dich zuerst zu Calm Now führen, damit der Körper nicht gezwungen ist, eine Geschichte im aktivierten Zustand zu lösen.",
          "tag": "Calm Now"
        },
        {
          "title": "Wenn die Nacht alles schwerer macht",
          "body": "Sleep Now hält den Ton sanfter, hilft, die Schleife zu parken, und zieht dich vor dem Schlafen nicht in schwere Analyse.",
          "tag": "Sleep Now"
        },
        {
          "title": "Wenn dieselbe Überzeugung immer wieder kommt",
          "body": "Weekly Mirror spiegelt Muster nur mit genügend Belegen wider, und jede Reflexion bleibt editierbar, bescheiden und korrigierbar.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Emotionale Evidenz ohne fake Hype",
      "title": "Das Versprechen ist klein, glaubwürdig und wiederholbar.",
      "intro": "Diese Moment-Karten zeigen die Verschiebung, die Miravelys unterstützen soll: von einer verschmolzenen emotionalen Wahrheit hin zu einem kleineren, freundlicheren, spezifischeren nächsten Schritt.",
      "items": [
        {
          "before": "Vorher: „Ich weiß, ich übertreibe vielleicht, aber es fühlt sich trotzdem völlig wahr an.",
          "after": "Nachher: „Ein Teil davon ist ein Gefühl. Ein Teil ist eine Geschichte. Ich kann auf die Tatsache antworten, nicht auf die Angst."
        },
        {
          "before": "Vorher: „Wenn ich jetzt schlafe, verliere ich die Kontrolle über das Problem.",
          "after": "Nachher: „Ich habe den nächsten Schritt aufgeschrieben. Ich kann die Nacht einfach Nacht sein lassen."
        },
        {
          "before": "Vorher: „Das passiert immer wieder, also ist das vielleicht einfach ich.",
          "after": "Nachher: „Dieses Muster ist mehr als einmal aufgetaucht. Es ist Information, keine Identität."
        }
      ]
    },
    "positioning": {
      "eyebrow": "Klare Positionierung",
      "title": "Miravelys versucht nicht, alles zu sein. Das ist Teil des Vertrauens.",
      "intro": "Klare Grenzen sind Teil des Vertrauens. Miravelys erklärt, was es unterstützt — Reflexion, Bodenhaftung, Musterbewusstsein — und was es nicht behauptet zu tun.",
      "items": [
        {
          "title": "Kein Tagebuch, das alles für immer speichert",
          "body": "Es ist ein geführter Klarheitsraum. Du kannst behalten, korrigieren, verbergen oder löschen, was nicht passt."
        },
        {
          "title": "Keine Therapie, Diagnose oder spirituelle Gewissheit",
          "body": "Es benennt keine Wunden, klebt dir keine Identitätsbezeichnung an und behauptet keine absolute Wahrheit über dich."
        },
        {
          "title": "Keine Streak-Maschine",
          "body": "Keine Schuldspiralen, keine manipulative Dringlichkeit, kein falscher Produktivitätsdruck. Komm zurück, weil es hilft, nicht weil es dich beschämt."
        },
        {
          "title": "Ein privater Begleiter zum Verstehen",
          "body": "Er hilft dir zu bemerken, was real ist, was hinzugefügt wurde, was dich beruhigt und was deinen nächsten Schritt wirklich unterstützt."
        }
      ]
    },
    "beta": {
      "eyebrow": "Ein sanfterer Beginn",
      "title": "Beginne mit einer ehrlichen Zeile. Die App kann dich dort treffen.",
      "body": "Tritt dem Early Access bei für Launch-Updates und private Beta-News. Die Einladung ist absichtlich ruhig: kein Druck, keine Serien, keine emotionale Dringlichkeit.",
      "placeholder": "E-Mail für Launch-Updates",
      "button": "Frühen Zugang erhalten",
      "success": "Danke — deine Launch-Anfrage wurde auf diesem Gerät gespeichert. Wenn sich die Mail-App geöffnet hat, sende die Nachricht, damit wir sie erhalten.",
      "emailError": "Bitte gib eine gültige E-Mail-Adresse ein.",
      "mailtoSubject": "Miravelys Early Access",
      "mailtoBody": "Bitte füge {email} zu den Miravelys Early Access Updates hinzu.",
      "privacy": "Kein Druck, kein Spam-Ton, keine emotionale Manipulation. Nur Produktupdates, wenn Miravelys bereit ist."
    },
    "sticky": {
      "appStore": "Miravelys laden",
      "mockups": "In der App",
      "explore": "Beginne mit einem klaren Moment",
      "earlyAccess": "Früher Zugang",
      "privacy": "Wie Privatsphäre funktioniert"
    }
  },
  "ja": {
    "scenarios": {
      "eyebrow": "Miravelys が助ける場所",
      "title": "このアプリは、完璧なルーティンのためではなく、本当の瞬間のために作られています。",
      "intro": "Miravelys は、普通の感情的な瞬間が実際に起こる場所から始まります。眠る前、傷つくメッセージを受け取った後、何度も頭の中で再生される会話の途中、あるいは何かを静かに教えてくれた一週間の後。",
      "items": [
        {
          "title": "一つのメッセージが大きな物語になるとき",
          "body": "ありのままの思いを書き留める。Miravelys は、メッセージの言葉と、心がそれに重ねた意味とを分けて見る手助けをします。",
          "tag": "Get Clear"
        },
        {
          "title": "身体が騒がしすぎてはっきり考えられないとき",
          "body": "アプリは問いを一時停止し、まず Calm Now に誘うことができます。活性化した状態で、身体に物語を解かせようとしないためです。",
          "tag": "Calm Now"
        },
        {
          "title": "夜がすべてを重く感じさせるとき",
          "body": "Sleep Now はトーンをやわらげ、ぐるぐる回る思考をいったん置き、眠る前に重い分析に引きずり込まないようにします。",
          "tag": "Sleep Now"
        },
        {
          "title": "同じ信念が何度も戻ってくるとき",
          "body": "Weekly Mirror は十分な根拠があるときだけパターンを映し出し、どの振り返りも編集可能で、謙虚で、訂正可能なままです。",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "偽の誇大広告なしの感情的証明",
      "title": "約束は小さく、信じられ、繰り返し可能です。",
      "intro": "これらのカードは、Miravelys が支えたい変化を示しています。混ざり合った一つの感情的真実から、より小さく、やさしく、具体的な次の一歩へ。",
      "items": [
        {
          "before": "前：「大げさかもしれないけど、今は完全に本当に感じる。」",
          "after": "後：「一部は感情。一部は物語。恐怖ではなく、事実に応えられる。」"
        },
        {
          "before": "前：「今寝たら、問題のコントロールを失う。」",
          "after": "後：「次の一歩を書き留めた。夜は夜でいい。」"
        },
        {
          "before": "前：「これが繰り返されるから、たぶんこれが私なんだ。」",
          "after": "後：「このパターンは何度も現れた。情報であって、アイデンティティではない。」"
        }
      ]
    },
    "positioning": {
      "eyebrow": "明確なポジショニング",
      "title": "Miravelys はすべてをしようとしていません。それが信頼の一部です。",
      "intro": "明確な境界線は信頼の一部です。Miravelys は、反射、接地、パターンの気づきをサポートすること、そして何をしないかを説明します。",
      "items": [
        {
          "title": "すべてを永遠に保存する日記ではない",
          "body": "それは導かれた明晰さの場所です。合わないものは保持したり、修正したり、隠したり、削除したりできます。"
        },
        {
          "title": "療法、診断、霊的確信ではない",
          "body": "傷に名前をつけず、アイデンティティにラベルを貼らず、あなたについての絶対的な真実を主張しません。"
        },
        {
          "title": "ストリークマシンではない",
          "body": "罪悪感のループ、操作による緊急性、偽の生産性プレッシャーはありません。恥をかかせられるからではなく、役立つから戻ってきます。"
        },
        {
          "title": "私的な理解の伴走者",
          "body": "何が現実で、何が付け加えられ、何があなたを落ち着かせ、次の一歩を本当に支えるかに気づく手助けをします。"
        }
      ]
    },
    "beta": {
      "eyebrow": "よりやさしく始める方法",
      "title": "正直な一文から始めましょう。アプリはそこであなたに会います。",
      "body": "ローンチの更新情報とプライベートベータのニュースを受け取るために、早期アクセスに参加してください。招待状は意図的に静かです。プレッシャーも連続記録も、感情的な緊急性もありません。",
      "placeholder": "ローンチ情報用メールアドレス",
      "button": "早期アクセスに参加",
      "success": "ありがとうございます——ローンチのリクエストはこのデバイスに保存されました。メールアプリが開いた場合は、メッセージを送信して私たちが受け取れるようにしてください。",
      "emailError": "有効なメールアドレスを入力してください。",
      "mailtoSubject": "Miravelys 早期アクセス",
      "mailtoBody": "{email} を Miravelys 早期アクセス更新リストに追加してください。",
      "privacy": "プレッシャーはなく、スパム調でもなく、感情的な操作もありません。Miravelys の準備ができたときにのみ製品アップデートをお送りします。"
    },
    "sticky": {
      "appStore": "Miravelys をダウンロード",
      "mockups": "アプリの中",
      "explore": "一つの明確な瞬間から始める",
      "earlyAccess": "早期アクセス",
      "privacy": "プライバシーの仕組み"
    }
  },
  "es": {
    "scenarios": {
      "eyebrow": "Dónde ayuda Miravelys",
      "title": "La app está diseñada para momentos reales, no rutinas perfectas.",
      "intro": "Miravelys empieza donde realmente ocurren los momentos emocionales ordinarios: antes de dormir, después de un mensaje que dolió, durante una conversación que sigue repitiéndose, o después de una semana que te mostró algo en silencio.",
      "items": [
        {
          "title": "Cuando un mensaje se convierte en toda una historia",
          "body": "Escribe el pensamiento crudo. Miravelys ayuda a separar las palabras del mensaje del significado que tu mente añadió alrededor de ellas.",
          "tag": "Get Clear"
        },
        {
          "title": "Cuando tu cuerpo está demasiado ruidoso para pensar con claridad",
          "body": "La app puede pausar la indagación y guiarte primero a Calm Now, para que el cuerpo no se vea forzado a resolver una historia mientras está activado.",
          "tag": "Calm Now"
        },
        {
          "title": "Cuando la noche hace que todo se sienta más pesado",
          "body": "Sleep Now mantiene el tono más suave, ayuda a aparcar el bucle y evita arrastrarte a un análisis pesado antes de dormir.",
          "tag": "Sleep Now"
        },
        {
          "title": "Cuando la misma creencia sigue volviendo",
          "body": "Weekly Mirror refleja patrones solo con evidencia suficiente, y cada reflexión sigue siendo editable, humilde y corregible.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Prueba emocional sin hype falso",
      "title": "La promesa es pequeña, creíble y repetible.",
      "intro": "Estas tarjetas de momento muestran el tipo de cambio que Miravelys está construido para apoyar: de una verdad emocional fusionada hacia un siguiente paso más pequeño, más amable y más específico.",
      "items": [
        {
          "before": "Antes: “Sé que quizá estoy exagerando, pero todavía se siente completamente cierto.”",
          "after": "Después: “Parte de esto es un sentimiento. Parte es una historia. Puedo responder al hecho, no al miedo.”"
        },
        {
          "before": "Antes: “Si duermo ahora, perderé el control del problema.”",
          "after": "Después: “Anoté el siguiente paso. Puedo dejar que la noche sea noche.”"
        },
        {
          "before": "Antes: “Esto sigue pasando, así que tal vez así soy yo.”",
          "after": "Después: “Este patrón apareció más de una vez. Es información, no identidad.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Posicionamiento claro",
      "title": "Miravelys no intenta ser todo. Eso es parte de la confianza.",
      "intro": "Los límites claros son parte de la confianza. Miravelys explica lo que apoya — reflexión, anclaje, conciencia de patrones — y lo que no pretende hacer.",
      "items": [
        {
          "title": "No es un diario que guarda todo para siempre",
          "body": "Es un espacio guiado de claridad. Puedes conservar, corregir, ocultar o borrar lo que no encaja."
        },
        {
          "title": "No es terapia, diagnóstico o certeza espiritual",
          "body": "No nombra tus heridas, no etiqueta tu identidad ni reclama una verdad absoluta sobre ti."
        },
        {
          "title": "No es una máquina de rachas",
          "body": "Sin bucles de culpa, sin urgencia manipuladora, sin presión de productividad falsa. Vuelve porque ayuda, no porque te avergüence."
        },
        {
          "title": "Un compañero privado de comprensión",
          "body": "Te ayuda a notar qué es real, qué está añadido, qué te calma y qué apoya realmente tu siguiente paso."
        }
      ]
    },
    "beta": {
      "eyebrow": "Una forma más suave de empezar",
      "title": "Empieza con una frase honesta. La app puede encontrarte ahí.",
      "body": "Únete al acceso anticipado para recibir actualizaciones de lanzamiento y noticias de la beta privada. La invitación es deliberadamente calmada: sin presión, sin rachas, sin urgencia emocional.",
      "placeholder": "Email para noticias de lanzamiento",
      "button": "Acceso anticipado",
      "success": "Gracias — tu solicitud de lanzamiento se guardó en este dispositivo. Si se abrió la app de correo, envía el mensaje para que podamos recibirlo.",
      "emailError": "Por favor, introduce una dirección de email válida.",
      "mailtoSubject": "Acceso anticipado Miravelys",
      "mailtoBody": "Por favor, añade {email} a las actualizaciones de acceso anticipado de Miravelys.",
      "privacy": "Sin presión, sin tono de spam, sin manipulación emocional. Solo actualizaciones del producto cuando Miravelys esté listo."
    },
    "sticky": {
      "appStore": "Descargar Miravelys",
      "mockups": "Dentro de la app",
      "explore": "Empieza con un momento claro",
      "earlyAccess": "Acceso anticipado",
      "privacy": "Cómo funciona la privacidad"
    }
  },
  "pt": {
    "scenarios": {
      "eyebrow": "Onde o Miravelys ajuda",
      "title": "A app é construída para momentos reais, não rotinas perfeitas.",
      "intro": "O Miravelys começa onde os momentos emocionais ordinários realmente acontecem: antes de dormir, depois de uma mensagem que magoou, durante uma conversa que continua a repetir-se, ou depois de uma semana que te mostrou algo em silêncio.",
      "items": [
        {
          "title": "Quando uma mensagem se torna uma história inteira",
          "body": "Escreve o pensamento cru. O Miravelys ajuda a separar as palavras da mensagem do significado que a mente acrescentou à volta delas.",
          "tag": "Get Clear"
        },
        {
          "title": "Quando o corpo está demasiado barulhento para pensar com clareza",
          "body": "A app pode pausar a investigação e guiar-te primeiro para o Calm Now, para que o corpo não seja forçado a resolver uma história enquanto está ativado.",
          "tag": "Calm Now"
        },
        {
          "title": "Quando a noite faz tudo parecer mais pesado",
          "body": "O Sleep Now mantém o tom mais suave, ajuda a estacionar o loop e evita arrastar-te para uma análise pesada antes de dormir.",
          "tag": "Sleep Now"
        },
        {
          "title": "Quando a mesma crença continua a voltar",
          "body": "O Weekly Mirror reflete padrões apenas com evidência suficiente, e cada reflexão permanece editável, humilde e corrigível.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Prova emocional sem hype falso",
      "title": "A promessa é pequena, credível e repetível.",
      "intro": "Estes cartões de momento mostram o tipo de mudança que o Miravelys foi construído para apoiar: de uma verdade emocional fundida para um próximo passo mais pequeno, mais gentil e mais específico.",
      "items": [
        {
          "before": "Antes: “Sei que talvez esteja a exagerar, mas ainda me parece completamente verdade.”",
          "after": "Depois: “Parte disto é um sentimento. Parte é uma história. Posso responder ao facto, não ao medo.”"
        },
        {
          "before": "Antes: “Se dormir agora, vou perder o controlo do problema.”",
          "after": "Depois: \"Escrevi o próximo passo. Posso deixar que a noite seja noite.\""
        },
        {
          "before": "Antes: “Isto continua a acontecer, por isso talvez seja assim que eu sou.”",
          "after": "Depois: \"Este padrão apareceu mais do que uma vez. É informação, não identidade.\""
        }
      ]
    },
    "positioning": {
      "eyebrow": "Posicionamento claro",
      "title": "O Miravelys não tenta ser tudo. Isso faz parte da confiança.",
      "intro": "Limites claros fazem parte da confiança. O Miravelys explica o que apoia — reflexão, ancoragem, consciência de padrões — e o que não pretende fazer.",
      "items": [
        {
          "title": "Não é um diário que guarda tudo para sempre",
          "body": "É um espaço guiado de clareza. Podes guardar, corrigir, ocultar ou apagar o que não combina."
        },
        {
          "title": "Não é terapia, diagnóstico ou certeza espiritual",
          "body": "Não nomeia as tuas feridas, não rotula a tua identidade nem reclama uma verdade absoluta sobre ti."
        },
        {
          "title": "Não é uma máquina de sequências",
          "body": "Sem ciclos de culpa, sem urgência manipuladora, sem pressão falsa de produtividade. Volta porque ajuda, não porque te envergonha."
        },
        {
          "title": "Um companheiro privado de compreensão",
          "body": "Ajuda-te a notar o que é real, o que foi acrescentado, o que te acalma e o que realmente apoia o teu próximo passo."
        }
      ]
    },
    "beta": {
      "eyebrow": "Uma forma mais suave de começar",
      "title": "Começa com uma frase honesta. A app pode encontrar-te aí.",
      "body": "Junta-te ao acesso antecipado para receber atualizações de lançamento e notícias da beta privada. O convite é deliberadamente calmo: sem pressão, sem sequências, sem urgência emocional.",
      "placeholder": "Email para notícias de lançamento",
      "button": "Acesso antecipado",
      "success": "Obrigado — o teu pedido de lançamento foi guardado neste dispositivo. Se a app de email abriu, envia a mensagem para que a possamos receber.",
      "emailError": "Por favor, introduz um endereço de email válido.",
      "mailtoSubject": "Acesso antecipado Miravelys",
      "mailtoBody": "Por favor, adiciona {email} às atualizações de acesso antecipado do Miravelys.",
      "privacy": "Sem pressão, sem tom de spam, sem manipulação emocional. Apenas atualizações do produto quando o Miravelys estiver pronto."
    },
    "sticky": {
      "appStore": "Baixar Miravelys",
      "mockups": "Dentro da app",
      "explore": "Começa com um momento claro",
      "earlyAccess": "Acesso antecipado",
      "privacy": "Como funciona a privacidade"
    }
  }
};

export function resolveExperience(lang) {
  return experienceCopy[lang] ?? experienceCopy.en;
}
