// Generated by Miravelys product-accurate website audit pass.

export const experienceCopy = {
  "en": {
    "scenarios": {
      "eyebrow": "Where Miravelys helps",
      "title": "The app is designed around real moments, not perfect routines.",
      "intro": "Miravelys begins where ordinary emotional moments actually happen: before sleep, after a message that hurt, during a conversation that keeps replaying, or after a week that quietly showed you something.",
      "items": [
        {
          "title": "When one message becomes a whole story",
          "body": "Write the raw thought. Miravelys helps separate the words in the message from the meaning your mind added around them.",
          "tag": "Get Clear"
        },
        {
          "title": "When your body is too loud to think clearly",
          "body": "The app can pause inquiry and guide you into Calm Now first, so the body is not forced to solve a story while activated.",
          "tag": "Calm Now"
        },
        {
          "title": "When night makes everything feel heavier",
          "body": "Sleep Now keeps the tone softer, helps park the loop, and avoids dragging you into heavy analysis before bed.",
          "tag": "Sleep Now"
        },
        {
          "title": "When the same belief keeps returning",
          "body": "Weekly Mirror reflects patterns only with enough evidence, and every reflection stays editable, humble, and correctable.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Emotional proof without fake hype",
      "title": "The promise is small, believable, and repeatable.",
      "intro": "These moment cards show the kind of shift Miravelys is built to support: from one fused emotional truth toward a smaller, kinder, more specific next step.",
      "items": [
        {
          "before": "Before: “I know I’m overreacting, but it still feels completely true.”",
          "after": "After: “Part of this is a feeling. Part is a story. I can answer the fact, not the fear.”"
        },
        {
          "before": "Before: “If I sleep now, I’ll lose control of the problem.”",
          "after": "After: “I wrote the next step down. I can let the night be night.”"
        },
        {
          "before": "Before: “This keeps happening, so maybe this is just who I am.”",
          "after": "After: “This pattern appeared more than once. It is information, not an identity.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Clear positioning",
      "title": "Miravelys is not trying to be everything. That is part of the trust.",
      "intro": "Clear boundaries are part of the trust. Miravelys explains what it supports — reflection, grounding, pattern awareness — and what it does not claim to do.",
      "items": [
        {
          "title": "Not a diary that stores everything forever",
          "body": "It is a guided clarity space. You can keep, correct, hide, or delete what does not fit."
        },
        {
          "title": "Not therapy, diagnosis, or spiritual certainty",
          "body": "It does not name your trauma, label your identity, or claim absolute truth about you."
        },
        {
          "title": "Not a streak machine",
          "body": "No guilt loops, no manipulative urgency, no fake productivity pressure. Return because it helps, not because it shames you."
        },
        {
          "title": "A private understanding companion",
          "body": "It helps you notice what is real, what is added, what calms you, and what actually supports your next step."
        }
      ]
    },
    "beta": {
      "eyebrow": "A softer way to begin",
      "title": "Start with one honest line. The app can meet you there.",
      "body": "Join early access for launch updates and private beta news. The invitation is calm on purpose: no pressure, no streaks, no emotional urgency.",
      "placeholder": "Email for launch updates",
      "button": "Join early access",
      "success": "Thank you — your launch request was saved on this device. If the mail app opened, send the message so we can receive it.",
      "emailError": "Please enter a valid email address.",
      "mailtoSubject": "Miravelys early access",
      "mailtoBody": "Please add {email} to Miravelys early access updates.",
      "privacy": "No pressure, no spam tone, no emotional manipulation. Just product updates when Miravelys is ready."
    },
    "sticky": {
      "appStore": "Join early access",
      "mockups": "Inside the app",
      "explore": "Begin with one clear moment",
      "earlyAccess": "Join early access",
      "privacy": "How privacy works"
    }
  },
  "ru": {
    "scenarios": {
      "eyebrow": "Где помогает Miravelys",
      "title": "Приложение создано вокруг реальных моментов, а не идеальных привычек.",
      "intro": "Miravelys начинается там, где обычные эмоциональные моменты действительно происходят: перед сном, после зацепившего сообщения, во время разговора, который снова прокручивается, или после недели, которая тихо что-то показала.",
      "items": [
        {
          "title": "Когда одно сообщение превращается в целую историю",
          "body": "Запиши сырую мысль. Miravelys помогает отделить слова в сообщении от смысла, который ум добавил вокруг них.",
          "tag": "Get Clear"
        },
        {
          "title": "Когда тело слишком громкое, чтобы ясно думать",
          "body": "Приложение может остановить inquiry и сначала направить в Calm Now, чтобы тело не пыталось решать историю в состоянии напряжения.",
          "tag": "Calm Now"
        },
        {
          "title": "Когда ночью всё кажется тяжелее",
          "body": "Sleep Now делает тон мягче, помогает отложить петлю мыслей и не втягивает в тяжёлый анализ перед сном.",
          "tag": "Sleep Now"
        },
        {
          "title": "Когда одно и то же убеждение возвращается снова",
          "body": "Weekly Mirror показывает паттерны только при достаточных доказательствах, а любое отражение остаётся редактируемым, скромным и исправляемым.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Эмоциональное доказательство без фальшивого хайпа",
      "title": "Обещание маленькое, правдоподобное и повторяемое.",
      "intro": "Эти карточки показывают сдвиг, который Miravelys должен поддерживать: от слитого эмоционального «это правда» к более маленькому, доброму и конкретному следующему шагу.",
      "items": [
        {
          "before": "До: «Я понимаю, что, возможно, преувеличиваю, но это всё равно кажется полностью правдой».",
          "after": "После: «Часть этого — чувство. Часть — история. Я могу ответить на факт, а не на страх»."
        },
        {
          "before": "До: «Если я сейчас усну, я потеряю контроль над проблемой».",
          "after": "После: «Я записал следующий шаг. Ночь может быть ночью»."
        },
        {
          "before": "До: «Это повторяется, значит, наверное, это просто я такой».",
          "after": "После: «Этот паттерн появлялся не раз. Это информация, а не личность»."
        }
      ]
    },
    "positioning": {
      "eyebrow": "Ясное позиционирование",
      "title": "Miravelys не пытается быть всем сразу. В этом и есть часть доверия.",
      "intro": "Чёткие границы — часть доверия. Miravelys объясняет, что поддерживает: размышление, заземление, замечание паттернов, — и чего не обещает.",
      "items": [
        {
          "title": "Не дневник, который хранит всё навсегда",
          "body": "Это направляемое пространство ясности. Ты можешь оставить, исправить, скрыть или удалить то, что не подходит."
        },
        {
          "title": "Не терапия, диагноз и не духовная окончательность",
          "body": "Приложение не называет твою травму, не навешивает ярлык личности и не заявляет абсолютную правду о тебе."
        },
        {
          "title": "Не машина стриков",
          "body": "Без чувства вины, манипулятивной срочности и фальшивого давления продуктивности. Возвращайся потому, что помогает, а не потому, что стыдно."
        },
        {
          "title": "Приватный спутник понимания",
          "body": "Он помогает замечать, что реально, что добавлено умом, что тебя успокаивает и что действительно поддерживает следующий шаг."
        }
      ]
    },
    "beta": {
      "eyebrow": "Более мягкое начало",
      "title": "Начни с одной честной строки. Приложение встретит тебя там.",
      "body": "Присоединяйтесь к раннему доступу, чтобы получать новости запуска и приватной беты. Приглашение намеренно спокойное: без давления, streaks и эмоциональной срочности.",
      "placeholder": "Email для новостей о запуске",
      "button": "Присоединиться",
      "success": "Спасибо — запрос на запуск сохранён на этом устройстве. Если открылось почтовое приложение, отправьте письмо, чтобы мы его получили.",
      "privacy": "Без давления, спама и эмоциональных манипуляций. Только новости продукта, когда Miravelys будет готов.",
      "emailError": "Введите корректный адрес электронной почты.",
      "mailtoSubject": "Ранний доступ Miravelys",
      "mailtoBody": "Добавьте, пожалуйста, {email} в список раннего доступа Miravelys."
    },
    "sticky": {
      "appStore": "Ранний доступ",
      "mockups": "Внутри приложения",
      "explore": "Начни с одного ясного момента",
      "earlyAccess": "Ранний доступ",
      "privacy": "Как работает приватность"
    }
  },
  "ro": {
    "scenarios": {
      "eyebrow": "Unde ajută Miravelys",
      "title": "Aplicația este construită pentru momente reale, nu pentru rutine perfecte.",
      "intro": "Miravelys începe acolo unde apar de fapt momentele emoționale obișnuite: înainte de somn, după un mesaj care a durut, în urma unei conversații care se repetă în minte sau după o săptămână care ți-a arătat ceva în liniște.",
      "items": [
        {
          "title": "Când un mesaj devine o poveste întreagă",
          "body": "Scrie gândul brut. Miravelys te ajută să separi cuvintele din mesaj de sensul pe care mintea l-a adăugat în jurul lor.",
          "tag": "Get Clear"
        },
        {
          "title": "Când corpul este prea zgomotos ca să gândești clar",
          "body": "Aplicația poate opri inquiry-ul și te poate duce întâi în Calm Now, ca trupul să nu fie forțat să rezolve o poveste când este activat.",
          "tag": "Calm Now"
        },
        {
          "title": "Când noaptea face totul să pară mai greu",
          "body": "Sleep Now păstrează tonul mai blând, te ajută să lași bucla deoparte și evită analiza grea înainte de culcare.",
          "tag": "Sleep Now"
        },
        {
          "title": "Când aceeași convingere revine",
          "body": "Weekly Mirror reflectă tipare doar cu suficiente dovezi, iar fiecare reflecție rămâne editabilă, modestă și corectabilă.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Dovadă emoțională fără exagerare falsă",
      "title": "Promisiunea este mică, credibilă și repetabilă.",
      "intro": "Aceste carduri arată schimbarea pe care Miravelys este construit să o susțină: de la un adevăr emoțional amestecat la un pas următor mai mic, mai blând și mai precis.",
      "items": [
        {
          "before": "Înainte: „Știu că poate exagerez, dar tot se simte complet adevărat.”",
          "after": "După: „O parte este emoție. O parte este poveste. Pot răspunde faptului, nu fricii.”"
        },
        {
          "before": "Înainte: „Dacă adorm acum, pierd controlul asupra problemei.”",
          "after": "După: „Am scris următorul pas. Pot lăsa noaptea să fie noapte.”"
        },
        {
          "before": "Înainte: „Se tot repetă, deci poate asta sunt eu.”",
          "after": "După: „Acest tipar a apărut de mai multe ori. Este informație, nu identitate.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Poziționare clară",
      "title": "Miravelys nu încearcă să fie totul. Asta face parte din încredere.",
      "intro": "Granițele clare fac parte din încredere. Miravelys explică ce susține — reflecție, ancorare, observarea tiparelor — și ce nu pretinde să facă.",
      "items": [
        {
          "title": "Nu este un jurnal care păstrează totul pentru totdeauna",
          "body": "Este un spațiu ghidat de claritate. Poți păstra, corecta, ascunde sau șterge ce nu se potrivește."
        },
        {
          "title": "Nu este terapie, diagnostic sau certitudine spirituală",
          "body": "Nu numește trauma, nu etichetează identitatea și nu pretinde adevăr absolut despre tine."
        },
        {
          "title": "Nu este o mașină de streak-uri",
          "body": "Fără vinovăție, urgență manipulativă sau presiune falsă de productivitate. Revii pentru că ajută, nu pentru că te rușinează."
        },
        {
          "title": "Un companion privat de înțelegere",
          "body": "Te ajută să observi ce este real, ce este adăugat, ce te calmează și ce îți susține cu adevărat următorul pas."
        }
      ]
    },
    "beta": {
      "eyebrow": "Un început mai blând",
      "title": "Începe cu o singură propoziție sinceră. Aplicația te poate întâlni acolo.",
      "body": "Intră în accesul timpuriu pentru noutăți despre lansare și beta privată. Invitația rămâne calmă intenționat: fără presiune, fără streak-uri, fără urgență emoțională.",
      "placeholder": "Email pentru noutăți despre lansare",
      "button": "Intră în acces timpuriu",
      "success": "Mulțumim — cererea ta a fost salvată pe acest dispozitiv. Dacă s-a deschis aplicația de email, trimite mesajul ca să îl primim.",
      "privacy": "Fără presiune, fără spam, fără manipulare emoțională. Doar noutăți despre produs când Miravelys este gata.",
      "emailError": "Introdu o adresă de email validă.",
      "mailtoSubject": "Acces timpuriu Miravelys",
      "mailtoBody": "Te rog adaugă {email} la actualizările de acces timpuriu Miravelys."
    },
    "sticky": {
      "appStore": "Acces timpuriu",
      "mockups": "În aplicație",
      "explore": "Începe cu un moment clar",
      "earlyAccess": "Acces timpuriu",
      "privacy": "Cum funcționează confidențialitatea"
    }
  },
  "fr": {
    "scenarios": {
      "eyebrow": "Là où Miravelys aide",
      "title": "L’application est conçue autour de vrais moments, pas de routines parfaites.",
      "intro": "Miravelys commence là où les moments émotionnels ordinaires arrivent vraiment : avant de dormir, après un message qui a blessé, après une conversation qui tourne encore, ou après une semaine qui a discrètement montré quelque chose.",
      "items": [
        {
          "title": "Quand un message devient toute une histoire",
          "body": "Écrivez la pensée brute. Miravelys aide à séparer les mots du message du sens que l’esprit a ajouté autour d’eux.",
          "tag": "Get Clear"
        },
        {
          "title": "Quand le corps est trop bruyant pour penser clairement",
          "body": "L’application peut mettre l’exploration en pause et vous guider d’abord vers Calm Now, pour ne pas forcer le corps à résoudre une histoire en état d’activation.",
          "tag": "Calm Now"
        },
        {
          "title": "Quand la nuit rend tout plus lourd",
          "body": "Sleep Now garde un ton plus doux, aide à poser la boucle de pensée, et évite de lancer une analyse lourde avant le coucher.",
          "tag": "Sleep Now"
        },
        {
          "title": "Quand la même croyance revient",
          "body": "Weekly Mirror reflète les schémas seulement avec assez de preuves, et chaque reflet reste modifiable, humble et corrigeable.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Preuve émotionnelle sans fausse exagération",
      "title": "La promesse est petite, crédible et répétable.",
      "intro": "Ces cartes montrent le changement que Miravelys cherche à soutenir : passer d’une vérité émotionnelle mélangée à un prochain pas plus petit, plus doux et plus précis.",
      "items": [
        {
          "before": "Avant : « Je sais que j’exagère peut-être, mais ça semble totalement vrai. »",
          "after": "Après : « Une partie est une émotion. Une partie est une histoire. Je peux répondre au fait, pas à la peur. »"
        },
        {
          "before": "Avant : « Si je dors maintenant, je perds le contrôle du problème. »",
          "after": "Après : « J’ai écrit la prochaine étape. Je peux laisser la nuit être la nuit. »"
        },
        {
          "before": "Avant : « Ça revient sans cesse, donc c’est peut-être juste qui je suis. »",
          "after": "Après : « Ce schéma est apparu plus d’une fois. C’est une information, pas une identité. »"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Positionnement clair",
      "title": "Miravelys n’essaie pas d’être tout. C’est aussi ce qui le rend digne de confiance.",
      "intro": "Des limites claires font partie de la confiance. Miravelys explique ce qu’il soutient — réflexion, ancrage, attention aux motifs — et ce qu’il ne prétend pas faire.",
      "items": [
        {
          "title": "Pas un journal qui garde tout pour toujours",
          "body": "C’est un espace guidé de clarté. Vous pouvez garder, corriger, masquer ou supprimer ce qui ne vous correspond pas."
        },
        {
          "title": "Pas une thérapie, un diagnostic ou une certitude spirituelle",
          "body": "Il ne nomme pas votre trauma, ne colle pas d’étiquette identitaire et ne prétend pas connaître une vérité absolue sur vous."
        },
        {
          "title": "Pas une machine à séries",
          "body": "Pas de culpabilité, pas d’urgence manipulatrice, pas de fausse pression de productivité. Revenez parce que cela aide, pas parce que cela vous fait honte."
        },
        {
          "title": "Un compagnon privé de compréhension",
          "body": "Il aide à voir ce qui est réel, ce qui est ajouté, ce qui vous apaise et ce qui soutient vraiment votre prochain pas."
        }
      ]
    },
    "beta": {
      "eyebrow": "Une manière plus douce de commencer",
      "title": "Commencez par une seule phrase honnête. L’application peut vous rejoindre là.",
      "body": "Rejoins l’accès anticipé pour recevoir les nouvelles du lancement et de la bêta privée. L’invitation reste volontairement calme : pas de pression, pas de séries, pas d’urgence émotionnelle.",
      "placeholder": "E-mail pour les nouvelles du lancement",
      "button": "Rejoindre l’accès anticipé",
      "success": "Merci — ta demande de lancement a été enregistrée sur cet appareil. Si l’app Mail s’est ouverte, envoie le message pour que nous le recevions.",
      "privacy": "Pas de pression, pas de spam, pas de manipulation émotionnelle. Seulement des nouvelles du produit quand Miravelys sera prêt.",
      "emailError": "Saisis une adresse e-mail valide.",
      "mailtoSubject": "Accès anticipé Miravelys",
      "mailtoBody": "Merci d'ajouter {email} aux mises à jour d'accès anticipé Miravelys."
    },
    "sticky": {
      "appStore": "Accès anticipé",
      "mockups": "Dans l’app",
      "explore": "Commence par un moment clair",
      "earlyAccess": "Accès anticipé",
      "privacy": "Comment fonctionne la confidentialité"
    }
  },
  "hi": {
    "scenarios": {
      "eyebrow": "Miravelys कहाँ मदद करता है",
      "title": "ऐप perfect routines के लिए नहीं, real moments के लिए बनाया गया है।",
      "intro": "Miravelys वहीं शुरू होता है जहाँ रोज़मर्रा के भावनात्मक पल सच में आते हैं: सोने से पहले, किसी चोट पहुँचाने वाले message के बाद, replay होती conversation के बीच, या ऐसी week के बाद जिसने चुपचाप कुछ दिखाया।",
      "items": [
        {
          "title": "जब एक message पूरी कहानी बन जाता है",
          "body": "कच्चा thought लिखें। Miravelys आपके लिखे words और मन द्वारा जोड़े गए meaning को अलग देखने में मदद करता है।",
          "tag": "Get Clear"
        },
        {
          "title": "जब body इतनी loud हो कि साफ़ सोचना मुश्किल हो",
          "body": "ऐप inquiry को pause करके पहले Calm Now में ले जा सकता है, ताकि activated body को story solve करने के लिए force न किया जाए।",
          "tag": "Calm Now"
        },
        {
          "title": "जब रात हर चीज़ को भारी बना देती है",
          "body": "Sleep Now tone को softer रखता है, loop को park करने में मदद करता है और सोने से पहले heavy analysis में नहीं खींचता।",
          "tag": "Sleep Now"
        },
        {
          "title": "जब वही belief बार-बार लौटता है",
          "body": "Weekly Mirror patterns को तभी दिखाता है जब enough evidence हो, और हर reflection editable, humble और correctable रहता है।",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Fake hype के बिना emotional proof",
      "title": "Promise छोटा, believable और repeatable है।",
      "intro": "ये moment cards वह बदलाव दिखाते हैं जिसे Miravelys support करना चाहता है: एक fused emotional truth से छोटे, नरम और ज़्यादा specific next step तक।",
      "items": [
        {
          "before": "पहले: “मुझे पता है शायद मैं overreact कर रहा/रही हूँ, लेकिन यह अभी पूरी तरह सच लगता है।”",
          "after": "बाद में: “इसका एक हिस्सा feeling है। एक हिस्सा story है। मैं fear नहीं, fact को जवाब दे सकता/सकती हूँ।”"
        },
        {
          "before": "पहले: “अगर मैं अभी सो गया/गई, तो problem पर control खो दूँगा/दूँगी।”",
          "after": "बाद में: “मैंने next step लिख दिया है। अब रात को रात रहने दे सकता/सकती हूँ।”"
        },
        {
          "before": "पहले: “यह बार-बार होता है, शायद यही मैं हूँ।”",
          "after": "बाद में: “यह pattern एक से ज़्यादा बार दिखा है। यह information है, identity नहीं।”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Clear positioning",
      "title": "Miravelys सब कुछ बनने की कोशिश नहीं करता। यही trust का हिस्सा है।",
      "intro": "स्पष्ट सीमाएँ भरोसे का हिस्सा हैं। Miravelys बताता है कि यह क्या support करता है — reflection, grounding, patterns देखना — और क्या दावा नहीं करता।",
      "items": [
        {
          "title": "ऐसी diary नहीं जो सब कुछ हमेशा रखे",
          "body": "यह guided clarity space है। जो fit नहीं होता, आप उसे keep, correct, hide या delete कर सकते हैं।"
        },
        {
          "title": "Therapy, diagnosis या spiritual certainty नहीं",
          "body": "यह आपके trauma को name नहीं करता, identity label नहीं लगाता और आपके बारे में absolute truth claim नहीं करता।"
        },
        {
          "title": "Streak machine नहीं",
          "body": "No guilt loops, no manipulative urgency, no fake productivity pressure. वापस आएँ क्योंकि मदद मिलती है, shame के कारण नहीं।"
        },
        {
          "title": "एक private understanding companion",
          "body": "यह मदद करता है देखने में कि क्या real है, क्या added है, क्या calm करता है और next step को सच में क्या support करता है।"
        }
      ]
    },
    "beta": {
      "eyebrow": "शुरू करने का नरम तरीका",
      "title": "एक honest line से शुरू करें। App वहीं आपसे मिल सकता है।",
      "body": "Launch updates और private beta news के लिए early access में जुड़ें। Invite जानबूझकर शांत है: कोई pressure नहीं, कोई streaks नहीं, कोई emotional urgency नहीं।",
      "placeholder": "Launch updates के लिए email",
      "button": "Early access जुड़ें",
      "success": "धन्यवाद — आपकी launch request इस device पर saved है। अगर mail app खुली है, message भेज दें ताकि हमें मिल सके।",
      "privacy": "No pressure, no spam tone, no emotional manipulation. Miravelys ready होने पर सिर्फ़ product updates।",
      "emailError": "कृपया एक मान्य ईमेल पता दर्ज करें।",
      "mailtoSubject": "Miravelys शीघ्र पहुँच",
      "mailtoBody": "कृपया {email} को Miravelys शीघ्र पहुँच अपडेट में जोड़ें।"
    },
    "sticky": {
      "appStore": "Early access",
      "mockups": "ऐप के अंदर",
      "explore": "एक स्पष्ट पल से शुरू करें",
      "earlyAccess": "शीघ्र पहुँच",
      "privacy": "गोपनीयता कैसे काम करती है"
    }
  },
  "zh": {
    "scenarios": {
      "eyebrow": "Miravelys 适用的时刻",
      "title": "这款应用围绕真实时刻设计，而不是完美日程。",
      "intro": "Miravelys 从普通情绪时刻真正发生的地方开始：睡前、被一条消息刺痛之后、反复回想一段对话时，或一周结束后突然看见了什么。",
      "items": [
        {
          "title": "当一条消息变成一整个故事",
          "body": "写下最原始的念头。Miravelys 帮你把消息里的文字，和大脑围绕它添加的意义分开。",
          "tag": "Get Clear"
        },
        {
          "title": "当身体太吵，无法清楚思考",
          "body": "应用可以暂停探询，先引导你进入 Calm Now，让身体不必在被激活时强行解决一个故事。",
          "tag": "Calm Now"
        },
        {
          "title": "当夜晚让一切显得更沉重",
          "body": "Sleep Now 会保持更柔和的语气，帮助你放下循环念头，避免在睡前进入沉重分析。",
          "tag": "Sleep Now"
        },
        {
          "title": "当同一个信念不断回来",
          "body": "Weekly Mirror 只在证据足够时反映模式，并且每个反映都保持可编辑、谦逊和可纠正。",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "没有虚假夸张的情绪证明",
      "title": "承诺很小，但可信、可重复。",
      "intro": "这些时刻卡展示 Miravelys 想支持的转变：从混在一起的情绪真实感，走向更小、更温柔、更具体的下一步。",
      "items": [
        {
          "before": "之前：“我知道我可能反应过度，但它现在还是感觉完全真实。”",
          "after": "之后：“其中一部分是感受，一部分是故事。我可以回应事实，而不是恐惧。”"
        },
        {
          "before": "之前：“如果我现在睡觉，就会失去对问题的控制。”",
          "after": "之后：“我已经写下下一步。可以让夜晚只是夜晚。”"
        },
        {
          "before": "之前：“这总是发生，也许这就是我。”",
          "after": "之后：“这个模式出现过不止一次。它是信息，不是身份。”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "清晰定位",
      "title": "Miravelys 不试图成为一切。这本身也是信任的一部分。",
      "intro": "清晰边界是信任的一部分。Miravelys 会说明它支持什么——反思、回到身体、看见模式——也说明它不声称做什么。",
      "items": [
        {
          "title": "不是一个永远保存一切的日记",
          "body": "它是一个被引导的清晰空间。不适合你的内容可以保留、修改、隐藏或删除。"
        },
        {
          "title": "不是治疗、诊断或精神确定性",
          "body": "它不会命名你的创伤，不会给身份贴标签，也不会声称掌握关于你的绝对真相。"
        },
        {
          "title": "不是连续打卡机器",
          "body": "没有内疚循环，没有操控式紧迫感，也没有虚假的效率压力。回来是因为它有帮助，而不是因为被羞辱。"
        },
        {
          "title": "一个私密的理解伴侣",
          "body": "它帮助你看见什么是真实的，什么是添加的，什么让你平静，以及什么真正支持下一步。"
        }
      ]
    },
    "beta": {
      "eyebrow": "更柔和的开始方式",
      "title": "从一句诚实的话开始。应用可以在那里与你相遇。",
      "body": "加入早期访问，接收上线与私人测试消息。这个邀请刻意保持平静：没有压力、没有连续打卡、没有情绪化催促。",
      "placeholder": "用于接收发布更新的邮箱",
      "button": "加入早期访问",
      "success": "谢谢——你的上线请求已保存在此设备上。如果邮件应用已打开，请发送邮件，让我们收到。",
      "privacy": "不施压，不垃圾邮件，不做情绪操控。只在 Miravelys 准备好时发送产品更新。",
      "emailError": "请输入有效的电子邮件地址。",
      "mailtoSubject": "Miravelys 早期访问",
      "mailtoBody": "请将 {email} 加入 Miravelys 早期访问更新列表。"
    },
    "sticky": {
      "appStore": "早期访问",
      "mockups": "应用内体验",
      "explore": "从一个清晰的时刻开始",
      "earlyAccess": "加入早期访问",
      "privacy": "隐私如何运作"
    }
  },
  "de": {
    "scenarios": {
      "eyebrow": "Wo Miravelys hilft",
      "title": "Die App ist für echte Momente gemacht, nicht für perfekte Routinen.",
      "intro": "Miravelys beginnt dort, wo gewöhnliche emotionale Momente wirklich entstehen: vor dem Schlafen, nach einer verletzenden Nachricht, während ein Gespräch immer wieder auftaucht oder nach einer Woche, die leise etwas gezeigt hat.",
      "items": [
        {
          "title": "Wenn eine Nachricht zu einer ganzen Geschichte wird",
          "body": "Schreibe den rohen Gedanken auf. Miravelys hilft, die Worte in der Nachricht von der Bedeutung zu trennen, die dein Kopf darum gebaut hat.",
          "tag": "Get Clear"
        },
        {
          "title": "Wenn der Körper zu laut ist, um klar zu denken",
          "body": "Die App kann Inquiry pausieren und dich zuerst zu Calm Now führen, damit der Körper keine Geschichte lösen muss, während er aktiviert ist.",
          "tag": "Calm Now"
        },
        {
          "title": "Wenn die Nacht alles schwerer wirken lässt",
          "body": "Sleep Now hält den Ton weicher, hilft, die Gedankenschleife abzulegen, und vermeidet schwere Analyse vor dem Schlafen.",
          "tag": "Sleep Now"
        },
        {
          "title": "Wenn dieselbe Überzeugung wiederkommt",
          "body": "Weekly Mirror spiegelt Muster nur mit genug Belegen, und jede Spiegelung bleibt bearbeitbar, bescheiden und korrigierbar.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Emotionale Glaubwürdigkeit ohne falschen Hype",
      "title": "Das Versprechen ist klein, glaubwürdig und wiederholbar.",
      "intro": "Diese Momentkarten zeigen die Veränderung, die Miravelys unterstützen soll: von einer verschmolzenen emotionalen Wahrheit zu einem kleineren, freundlicheren und genaueren nächsten Schritt.",
      "items": [
        {
          "before": "Vorher: „Ich weiß, dass ich vielleicht überreagiere, aber es fühlt sich trotzdem völlig wahr an.”",
          "after": "Nachher: „Ein Teil davon ist Gefühl. Ein Teil ist Geschichte. Ich kann auf die Tatsache reagieren, nicht auf die Angst.”"
        },
        {
          "before": "Vorher: „Wenn ich jetzt schlafe, verliere ich die Kontrolle über das Problem.”",
          "after": "Nachher: „Ich habe den nächsten Schritt aufgeschrieben. Ich kann die Nacht Nacht sein lassen.”"
        },
        {
          "before": "Vorher: „Das passiert immer wieder, also bin ich vielleicht einfach so.”",
          "after": "Nachher: „Dieses Muster ist mehr als einmal aufgetaucht. Es ist Information, keine Identität.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Klare Positionierung",
      "title": "Miravelys versucht nicht, alles zu sein. Genau das schafft Vertrauen.",
      "intro": "Klare Grenzen gehören zum Vertrauen. Miravelys erklärt, was es unterstützt — Reflexion, Erdung, Musterbewusstsein — und was es nicht zu leisten behauptet.",
      "items": [
        {
          "title": "Kein Tagebuch, das alles für immer speichert",
          "body": "Es ist ein geführter Raum für Klarheit. Was nicht passt, kannst du behalten, korrigieren, ausblenden oder löschen."
        },
        {
          "title": "Keine Therapie, Diagnose oder spirituelle Gewissheit",
          "body": "Es benennt kein Trauma, klebt keine Identitätsetiketten auf und behauptet keine absolute Wahrheit über dich."
        },
        {
          "title": "Keine Streak-Maschine",
          "body": "Keine Schuldschleifen, keine manipulative Dringlichkeit, kein falscher Produktivitätsdruck. Du kommst zurück, weil es hilft, nicht weil es dich beschämt."
        },
        {
          "title": "Ein privater Begleiter für Verständnis",
          "body": "Er hilft zu erkennen, was real ist, was ergänzt wurde, was dich beruhigt und was deinen nächsten Schritt wirklich unterstützt."
        }
      ]
    },
    "beta": {
      "eyebrow": "Ein sanfterer Anfang",
      "title": "Beginne mit einer ehrlichen Zeile. Die App kann dich dort abholen.",
      "body": "Tritt dem frühen Zugang bei, um Neuigkeiten zum Start und zur privaten Beta zu erhalten. Die Einladung bleibt bewusst ruhig: kein Druck, keine Streaks, keine emotionale Dringlichkeit.",
      "placeholder": "E-Mail für Launch-Updates",
      "button": "Frühen Zugang erhalten",
      "success": "Danke — deine Startanfrage wurde auf diesem Gerät gespeichert. Wenn sich die Mail-App geöffnet hat, sende die Nachricht, damit wir sie erhalten.",
      "privacy": "Kein Druck, kein Spam-Ton, keine emotionale Manipulation. Nur Produktupdates, wenn Miravelys bereit ist.",
      "emailError": "Bitte gib eine gültige E-Mail-Adresse ein.",
      "mailtoSubject": "Miravelys Frühzugang",
      "mailtoBody": "Bitte füge {email} zu den Miravelys-Frühzugang-Updates hinzu."
    },
    "sticky": {
      "appStore": "Früher Zugang",
      "mockups": "In der App",
      "explore": "Beginne mit einem klaren Moment",
      "earlyAccess": "Frühzugang",
      "privacy": "So funktioniert Privatsphäre"
    }
  },
  "ja": {
    "scenarios": {
      "eyebrow": "Miravelys が役立つ場面",
      "title": "このアプリは、完璧なルーティンではなく、現実の瞬間を中心に設計されています。",
      "intro": "Miravelys は、ふつうの感情の瞬間が実際に起こる場所から始まります。眠る前、傷ついたメッセージのあと、会話が何度も頭に戻るとき、あるいは一週間が静かに何かを見せてくれたあと。",
      "items": [
        {
          "title": "ひとつのメッセージが大きな物語になるとき",
          "body": "そのままの思考を書いてください。Miravelys は、メッセージの言葉と、心がその周りに付け足した意味を分ける手助けをします。",
          "tag": "Get Clear"
        },
        {
          "title": "体が強く反応して、はっきり考えられないとき",
          "body": "アプリは inquiry を一度止め、まず Calm Now に案内できます。反応している体に、物語を解決させようとしません。",
          "tag": "Calm Now"
        },
        {
          "title": "夜になるとすべてが重く感じるとき",
          "body": "Sleep Now はトーンをやわらかく保ち、思考のループをいったん置き、寝る前に重い分析へ引き込みません。",
          "tag": "Sleep Now"
        },
        {
          "title": "同じ信念が何度も戻ってくるとき",
          "body": "Weekly Mirror は十分な根拠があるときだけパターンを映し返し、その内容は常に編集可能で、控えめで、修正できます。",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "偽りの誇張ではない感情的な証拠",
      "title": "約束は小さく、信じやすく、繰り返せるものです。",
      "intro": "このカードは、Miravelys が支えたい変化を示します。ひとつに固まった感情的な「本当」から、より小さく、やさしく、具体的な次の一歩へ。",
      "items": [
        {
          "before": "Before：「大げさに反応しているのかもしれない。でも今は完全に本当のように感じる。」",
          "after": "After：「これは感情の部分と、物語の部分がある。恐れではなく、事実に返事できる。」"
        },
        {
          "before": "Before：「今眠ったら、この問題をコントロールできなくなる。」",
          "after": "After：「次の一歩を書いた。夜を夜のままにしておける。」"
        },
        {
          "before": "Before：「何度も起きるなら、これが自分なのかもしれない。」",
          "after": "After：「このパターンは複数回出ている。これは情報であって、アイデンティティではない。」"
        }
      ]
    },
    "positioning": {
      "eyebrow": "明確な位置づけ",
      "title": "Miravelys はすべてになろうとはしません。それも信頼の一部です。",
      "intro": "明確な境界は信頼の一部です。Miravelys は、支えること──内省、グラウンディング、パターンへの気づき──と、主張しないことをはっきり伝えます。",
      "items": [
        {
          "title": "すべてを永遠に保存する日記ではありません",
          "body": "導かれた明晰さのスペースです。合わないものは残す、直す、隠す、消すことができます。"
        },
        {
          "title": "治療、診断、スピリチュアルな断定ではありません",
          "body": "トラウマを名づけたり、アイデンティティを決めつけたり、あなたについて絶対の真実を主張したりしません。"
        },
        {
          "title": "連続記録を追わせる機械ではありません",
          "body": "罪悪感のループも、操作的な急かしも、偽の生産性プレッシャーもありません。恥ではなく、役に立つから戻ってくる設計です。"
        },
        {
          "title": "私的な理解の伴走者です",
          "body": "何が現実で、何が付け足され、何が落ち着かせ、何が次の一歩を本当に支えるのかに気づく手助けをします。"
        }
      ]
    },
    "beta": {
      "eyebrow": "よりやさしい始め方",
      "title": "正直な一文から始めてください。アプリはそこから寄り添えます。",
      "body": "公開情報とプライベートベータの案内を受け取るために、早期アクセスに参加してください。招待は意図的に静かです。プレッシャーも、連続記録も、感情を急かす表現もありません。",
      "placeholder": "ローンチ情報を受け取るメール",
      "button": "早期アクセスに参加",
      "success": "ありがとうございます。公開リクエストはこのデバイスに保存されました。メールアプリが開いた場合は、送信して私たちに届くようにしてください。",
      "privacy": "プレッシャーもスパム調も感情操作もありません。Miravelys の準備ができたときの製品情報だけです。",
      "emailError": "有効なメールアドレスを入力してください。",
      "mailtoSubject": "Miravelys 早期アクセス",
      "mailtoBody": "{email} を Miravelys の早期アクセス更新に追加してください。"
    },
    "sticky": {
      "appStore": "早期アクセス",
      "mockups": "アプリの中",
      "explore": "ひとつの明確な瞬間から始める",
      "earlyAccess": "早期アクセス",
      "privacy": "プライバシーの仕組み"
    }
  },
  "es": {
    "scenarios": {
      "eyebrow": "Dónde ayuda Miravelys",
      "title": "La app está diseñada para momentos reales, no para rutinas perfectas.",
      "intro": "Miravelys empieza donde los momentos emocionales cotidianos realmente ocurren: antes de dormir, después de un mensaje que dolió, en una conversación que vuelve una y otra vez o tras una semana que te mostró algo en silencio.",
      "items": [
        {
          "title": "Cuando un mensaje se convierte en toda una historia",
          "body": "Escribe el pensamiento en bruto. Miravelys ayuda a separar las palabras del mensaje del significado que tu mente añadió alrededor.",
          "tag": "Get Clear"
        },
        {
          "title": "Cuando el cuerpo está demasiado alto para pensar claro",
          "body": "La app puede pausar la indagación y llevarte primero a Calm Now, para que el cuerpo no tenga que resolver una historia mientras está activado.",
          "tag": "Calm Now"
        },
        {
          "title": "Cuando la noche hace que todo pese más",
          "body": "Sleep Now mantiene un tono más suave, ayuda a aparcar el bucle y evita empujarte a un análisis pesado antes de dormir.",
          "tag": "Sleep Now"
        },
        {
          "title": "Cuando la misma creencia vuelve una y otra vez",
          "body": "Weekly Mirror refleja patrones solo con suficiente evidencia, y cada reflejo sigue siendo editable, humilde y corregible.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Prueba emocional sin hype falso",
      "title": "La promesa es pequeña, creíble y repetible.",
      "intro": "Estas tarjetas muestran el cambio que Miravelys está diseñado para apoyar: de una verdad emocional mezclada a un siguiente paso más pequeño, amable y específico.",
      "items": [
        {
          "before": "Antes: “Sé que estoy exagerando, pero aun así se siente completamente cierto.”",
          "after": "Después: “Parte de esto es una emoción. Parte es una historia. Puedo responder al hecho, no al miedo.”"
        },
        {
          "before": "Antes: “Si duermo ahora, perderé el control del problema.”",
          "after": "Después: “Escribí el siguiente paso. Puedo dejar que la noche sea noche.”"
        },
        {
          "before": "Antes: “Esto sigue pasando, así que quizá esto es simplemente lo que soy.”",
          "after": "Después: “Este patrón apareció más de una vez. Es información, no identidad.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Posicionamiento claro",
      "title": "Miravelys no intenta serlo todo. Eso también genera confianza.",
      "intro": "Los límites claros son parte de la confianza. Miravelys explica lo que apoya — reflexión, anclaje, conciencia de patrones — y lo que no pretende hacer.",
      "items": [
        {
          "title": "No es un diario que guarda todo para siempre",
          "body": "Es un espacio guiado de claridad. Puedes guardar, corregir, ocultar o borrar lo que no encaje."
        },
        {
          "title": "No es terapia, diagnóstico ni certeza espiritual",
          "body": "No nombra tu trauma, no etiqueta tu identidad ni afirma una verdad absoluta sobre ti."
        },
        {
          "title": "No es una máquina de rachas",
          "body": "Sin culpa, sin urgencia manipuladora, sin falsa presión de productividad. Vuelves porque ayuda, no porque te avergüenza."
        },
        {
          "title": "Un compañero privado de comprensión",
          "body": "Te ayuda a notar qué es real, qué se añadió, qué te calma y qué apoya de verdad tu próximo paso."
        }
      ]
    },
    "beta": {
      "eyebrow": "Una forma más suave de empezar",
      "title": "Empieza con una línea honesta. La app puede encontrarte ahí.",
      "body": "Únete al acceso anticipado para recibir noticias del lanzamiento y de la beta privada. La invitación es tranquila a propósito: sin presión, sin rachas, sin urgencia emocional.",
      "placeholder": "Email para novedades del lanzamiento",
      "button": "Unirme al acceso anticipado",
      "success": "Gracias — tu solicitud de lanzamiento se guardó en este dispositivo. Si se abrió tu app de correo, envía el mensaje para que podamos recibirlo.",
      "privacy": "Sin presión, sin tono de spam, sin manipulación emocional. Solo novedades del producto cuando Miravelys esté listo.",
      "emailError": "Introduce una dirección de correo válida.",
      "mailtoSubject": "Acceso anticipado Miravelys",
      "mailtoBody": "Por favor añade {email} a las actualizaciones de acceso anticipado de Miravelys."
    },
    "sticky": {
      "appStore": "Acceso anticipado",
      "mockups": "Dentro de la app",
      "explore": "Empieza con un momento claro",
      "earlyAccess": "Acceso anticipado",
      "privacy": "Cómo funciona la privacidad"
    }
  },
  "pt": {
    "scenarios": {
      "eyebrow": "Onde o Miravelys ajuda",
      "title": "O app foi desenhado para momentos reais, não para rotinas perfeitas.",
      "intro": "Miravelys começa onde os momentos emocionais comuns realmente acontecem: antes de dormir, depois de uma mensagem que magoou, durante uma conversa que volta à cabeça ou depois de uma semana que mostrou algo em silêncio.",
      "items": [
        {
          "title": "Quando uma mensagem vira uma história inteira",
          "body": "Escreva o pensamento bruto. Miravelys ajuda a separar as palavras da mensagem do significado que a mente acrescentou ao redor delas.",
          "tag": "Get Clear"
        },
        {
          "title": "Quando o corpo está alto demais para pensar com clareza",
          "body": "O app pode pausar a investigação e levar-te primeiro para Calm Now, para que o corpo não seja forçado a resolver uma história enquanto está ativado.",
          "tag": "Calm Now"
        },
        {
          "title": "Quando a noite deixa tudo mais pesado",
          "body": "Sleep Now mantém o tom mais suave, ajuda a estacionar o loop e evita puxar-te para uma análise pesada antes de dormir.",
          "tag": "Sleep Now"
        },
        {
          "title": "Quando a mesma crença continua voltando",
          "body": "Weekly Mirror reflete padrões apenas com evidência suficiente, e cada reflexão continua editável, humilde e corrigível.",
          "tag": "Weekly Mirror"
        }
      ]
    },
    "proof": {
      "eyebrow": "Prova emocional sem hype falso",
      "title": "A promessa é pequena, crível e repetível.",
      "intro": "Estes cartões mostram a mudança que Miravelys foi criado para apoiar: de uma verdade emocional misturada para um próximo passo menor, mais gentil e mais específico.",
      "items": [
        {
          "before": "Antes: “Eu sei que talvez esteja exagerando, mas ainda parece completamente verdade.”",
          "after": "Depois: “Parte disso é sentimento. Parte é história. Posso responder ao fato, não ao medo.”"
        },
        {
          "before": "Antes: “Se eu dormir agora, vou perder o controle do problema.”",
          "after": "Depois: “Eu escrevi o próximo passo. Posso deixar a noite ser noite.”"
        },
        {
          "before": "Antes: “Isso continua acontecendo, então talvez isso seja quem eu sou.”",
          "after": "Depois: “Esse padrão apareceu mais de uma vez. É informação, não identidade.”"
        }
      ]
    },
    "positioning": {
      "eyebrow": "Posicionamento claro",
      "title": "Miravelys não tenta ser tudo. Isso também faz parte da confiança.",
      "intro": "Limites claros fazem parte da confiança. Miravelys explica o que apoia — reflexão, enraizamento, percepção de padrões — e o que não promete fazer.",
      "items": [
        {
          "title": "Não é um diário que guarda tudo para sempre",
          "body": "É um espaço guiado de clareza. Podes manter, corrigir, ocultar ou apagar o que não combina."
        },
        {
          "title": "Não é terapia, diagnóstico nem certeza espiritual",
          "body": "Ele não nomeia seu trauma, não rotula sua identidade e não afirma uma verdade absoluta sobre ti."
        },
        {
          "title": "Não é uma máquina de sequências",
          "body": "Sem culpa, sem urgência manipuladora, sem falsa pressão de produtividade. Volte porque ajuda, não porque envergonha."
        },
        {
          "title": "Um companheiro privado de compreensão",
          "body": "Ajuda-te a notar o que é real, o que foi acrescentado, o que acalma e o que realmente apoia o próximo passo."
        }
      ]
    },
    "beta": {
      "eyebrow": "Uma forma mais suave de começar",
      "title": "Comece com uma linha honesta. O app pode encontrar-te ali.",
      "body": "Junta-te ao acesso antecipado para receber notícias do lançamento e da beta privada. O convite é calmo de propósito: sem pressão, sem streaks, sem urgência emocional.",
      "placeholder": "Email para novidades do lançamento",
      "button": "Juntar ao acesso antecipado",
      "success": "Obrigado — o teu pedido de lançamento foi guardado neste dispositivo. Se a app de email abriu, envia a mensagem para podermos recebê-lo.",
      "privacy": "Sem pressão, sem tom de spam, sem manipulação emocional. Apenas novidades do produto quando Miravelys estiver pronto.",
      "emailError": "Introduz um endereço de email válido.",
      "mailtoSubject": "Acesso antecipado Miravelys",
      "mailtoBody": "Por favor adiciona {email} às atualizações de acesso antecipado Miravelys."
    },
    "sticky": {
      "appStore": "Acesso antecipado",
      "mockups": "Dentro da app",
      "explore": "Começa com um momento claro",
      "earlyAccess": "Acesso antecipado",
      "privacy": "Como funciona a privacidade"
    }
  }
};

export function resolveExperience(lang) {
  return experienceCopy[lang] ?? experienceCopy.en;
}
