// Generated by Miravelys story-driven website content pass.

export const marketingCopy = {
  "en": {
    "editorial": {
      "eyebrow": "Made for real life",
      "title": "Miravelys is for the moments people usually carry alone.",
      "lead": "It is for the late-night spiral, the message you keep rereading, the heavy chest before sleep, the family tension that stayed with you longer than expected, and the quiet wish to understand what is actually happening inside you.",
      "paragraphs": [
        "Instead of asking you to perform wellness, Miravelys gives you a calm place to tell the truth as it feels right now. One honest line is enough. From there, the app helps you slow the moment down, separate what happened from what your mind added, and find a response that feels kinder and more real.",
        "Over time, Miravelys becomes more personal without becoming invasive. It notices whether your body needs calming before questions, whether night needs softness instead of analysis, and whether a pattern has appeared often enough to reflect back to you with humility."
      ],
      "highlights": [
        "Warm, human guidance instead of pushy self-help.",
        "A local-first companion that stays correctable.",
        "Built for ordinary life, not only dramatic moments."
      ]
    },
    "gallery": {
      "eyebrow": "Real life, held gently",
      "title": "Miravelys should feel like something you can return to after life happens.",
      "intro": "Miravelys carries one promise through every feature: warmth, privacy, clarity, and enough calm to listen to what is happening inside.",
      "items": [
        {
          "title": "Clarity should lead back to life, not away from it",
          "body": "Warmth, connection, and ordinary joy are part of the promise. Miravelys is not about becoming detached from life. It is about returning to it with more space inside you.",
          "alt": "A joyful group of diverse friends outdoors at golden hour"
        },
        {
          "title": "Built for home, relationships, and real evenings",
          "body": "Some of the hardest moments happen in everyday life: tense conversations, emotional carryover, tired family evenings, and the feeling that your mind has made the situation bigger than it is.",
          "alt": "A warm multigenerational family gathered together at home"
        },
        {
          "title": "Gentle enough for night. Clear enough for change",
          "body": "Miravelys can help you settle before sleep, park a looping thought, and notice what your mind is adding to the scene. When you want it, the questions can become deeper and more direct.",
          "alt": "A lively group of diverse friends sharing an outdoor café table"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Inside the product",
      "title": "Each screen supports one moment in the journey.",
      "body": "Select a screen to preview the app in your language. Every mockup matches a real feature — write, separate, calm, rest, reflect — not decoration.",
      "points": [
        "Get Clear — write what touched, triggered, or tightened your body.",
        "Truth Line — separate event, emotion, body signal, story, belief, and unknown.",
        "Home — four gentle doorways when the body needs calm first.",
        "Weekly Mirror — notice repeated patterns without turning them into identity."
      ]
    }
  },
  "ru": {
    "editorial": {
      "eyebrow": "Создано для настоящей жизни",
      "title": "Miravelys — для тех моментов, которые люди обычно несут в одиночку.",
      "lead": "Это для ночной спирали мыслей, для сообщения, которое перечитываешь снова и снова, для тяжести в груди перед сном, для семейного напряжения, которое осталось с тобой дольше, чем ты ожидал, и для тихого желания понять, что на самом деле происходит внутри.",
      "paragraphs": [
        "Вместо того чтобы заставлять тебя «правильно заниматься осознанностью», Miravelys даёт спокойное место, где можно назвать правду так, как она ощущается сейчас. Достаточно одной честной строки. Дальше приложение помогает замедлить момент, отделить то, что произошло, от того, что дорисовал ум, и найти более мягкий и более реальный отклик.",
        "Со временем Miravelys становится более личным, не становясь навязчивым. Оно замечает, нужно ли сначала успокоить тело, нужен ли ночи не разбор, а мягкость, и повторяется ли какой-то паттерн достаточно часто, чтобы бережно показать его тебе."
      ],
      "highlights": [
        "Тёплый человеческий тон вместо навязчивой самопомощи.",
        "Local-first спутник, которого можно поправлять.",
        "Создано для обычной жизни, а не только для драматичных моментов."
      ]
    },
    "gallery": {
      "eyebrow": "Настоящая жизнь, бережно удержанная",
      "title": "Miravelys должен ощущаться как место, куда можно вернуться после событий жизни.",
      "intro": "Miravelys несёт одно обещание во всех функциях: тепло, приватность, ясность и достаточно спокойствия, чтобы услышать, что происходит внутри.",
      "items": [
        {
          "title": "Ясность должна возвращать к жизни, а не уводить от неё",
          "body": "Тепло, связь и обычная радость — часть смысла Miravelys. Приложение не о том, чтобы отстраниться от жизни. Оно о том, чтобы вернуться к ней с большим внутренним пространством.",
          "alt": "Радостная группа друзей разных национальностей на улице в золотой час"
        },
        {
          "title": "Создано для дома, отношений и настоящих вечеров",
          "body": "Самые трудные моменты часто происходят в повседневной жизни: напряжённые разговоры, эмоциональный осадок, уставшие семейные вечера и ощущение, что ум сделал ситуацию больше, чем она есть.",
          "alt": "Тёплая многонациональная семья нескольких поколений дома"
        },
        {
          "title": "Достаточно мягко для ночи. Достаточно ясно для перемен",
          "body": "Miravelys помогает успокоиться перед сном, отложить навязчивую мысль и заметить, что именно ум добавляет к происходящему. А когда ты готов, вопросы могут стать глубже и прямее.",
          "alt": "Живая компания друзей разных национальностей за столиком уличного кафе"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Внутри продукта",
      "title": "Каждый экран поддерживает один момент в пути.",
      "body": "Выбери экран, чтобы увидеть приложение на своём языке. Каждый макет соответствует реальной функции — записать, разделить, успокоить, отдохнуть, увидеть повтор — а не декорации.",
      "points": [
        "Get Clear — запиши то, что задело, вызвало реакцию или свело тело.",
        "Truth Line — отдели событие, эмоцию, сигнал тела, историю, убеждение и неизвестное.",
        "Home — четыре мягких входа, когда телу сначала нужен покой.",
        "Weekly Mirror — замечай паттерны, не превращая их в личность."
      ]
    }
  },
  "ro": {
    "editorial": {
      "eyebrow": "Creat pentru viața reală",
      "title": "Miravelys este pentru momentele pe care oamenii le duc, de obicei, singuri.",
      "lead": "Este pentru spirala de gânduri de seară, pentru mesajul pe care îl recitești de prea multe ori, pentru greutatea din piept înainte de somn, pentru tensiunea din familie care a rămas cu tine mai mult decât credeai și pentru dorința liniștită de a înțelege ce se întâmplă cu adevărat în tine.",
      "paragraphs": [
        "În loc să te facă să „performez” starea de bine, Miravelys îți oferă un loc calm în care poți spune adevărul exact așa cum se simte acum. O singură propoziție sinceră este suficientă. De acolo, aplicația te ajută să încetinești momentul, să separi ce s-a întâmplat de ceea ce mintea a adăugat și să găsești un răspuns mai blând și mai real.",
        "Cu timpul, Miravelys devine mai personal fără să devină intruziv. Observă dacă trupul tău are nevoie întâi de calm, dacă noaptea are nevoie de blândețe în loc de analiză și dacă un tipar apare destul de des încât să ți-l reflecte cu modestie."
      ],
      "highlights": [
        "Ghidare caldă și umană, nu dezvoltare personală agresivă.",
        "Un companion local-first care rămâne corectabil.",
        "Creat pentru viața obișnuită, nu doar pentru momente dramatice."
      ]
    },
    "gallery": {
      "eyebrow": "Viață reală, ținută blând",
      "title": "Miravelys trebuie să se simtă ca un loc la care poți reveni după ce viața se întâmplă.",
      "intro": "Miravelys păstrează aceeași promisiune în fiecare funcție: căldură, intimitate, claritate și destul calm ca să asculți ce se întâmplă în interior.",
      "items": [
        {
          "title": "Claritatea ar trebui să te aducă înapoi la viață, nu să te îndepărteze de ea",
          "body": "Căldura, conexiunea și bucuria obișnuită fac parte din promisiunea Miravelys. Aplicația nu este despre a te detașa de viață. Este despre a te întoarce la ea cu mai mult spațiu înăuntrul tău.",
          "alt": "Un grup vesel de prieteni diverși afară, la lumina caldă a serii"
        },
        {
          "title": "Creat pentru casă, relații și seri reale",
          "body": "Unele dintre cele mai grele momente apar în viața de zi cu zi: conversații tensionate, încărcătură emoțională rămasă, seri obosite în familie și senzația că mintea a făcut situația mai mare decât este.",
          "alt": "O familie caldă, din mai multe generații, adunată acasă"
        },
        {
          "title": "Destul de blând pentru noapte. Destul de clar pentru schimbare",
          "body": "Miravelys te poate ajuta să te liniștești înainte de somn, să lași deoparte un gând repetitiv și să observi ce anume adaugă mintea la scenă. Iar când vrei, întrebările pot deveni mai profunde și mai directe.",
          "alt": "Un grup viu de prieteni diverși la o masă de cafenea în aer liber"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "În interiorul produsului",
      "title": "Fiecare ecran susține un moment din călătorie.",
      "body": "Alege un ecran pentru a previzualiza aplicația în limba ta. Fiecare mockup corespunde unei funcții reale — scrie, separă, calmează, odihnește-te, reflectează — nu decor.",
      "points": [
        "Get Clear — scrie ce te-a atins, declanșat sau strâns corpul.",
        "Truth Line — separă evenimentul, emoția, semnalul corpului, povestea, convingerea și necunoscutul.",
        "Home — patru uși blânde când corpul are nevoie mai întâi de calm.",
        "Weekly Mirror — observă tipare fără să le transformi în identitate."
      ]
    }
  },
  "fr": {
    "editorial": {
      "eyebrow": "Conçu pour la vraie vie",
      "title": "Miravelys s’adresse aux moments que l’on porte souvent seul.",
      "lead": "C’est pour la spirale du soir, pour le message que l’on relit sans fin, pour le poids dans la poitrine avant de dormir, pour la tension familiale qui reste plus longtemps que prévu, et pour ce désir discret de comprendre ce qui se passe vraiment en soi.",
      "paragraphs": [
        "Au lieu de vous demander de “bien faire le bien-être”, Miravelys vous offre un endroit calme où dire la vérité telle qu’elle se présente maintenant. Une seule phrase honnête suffit. À partir de là, l’application vous aide à ralentir le moment, à séparer ce qui s’est passé de ce que l’esprit a ajouté, et à trouver une réponse plus douce et plus juste.",
        "Avec le temps, Miravelys devient plus personnel sans devenir intrusif. Il remarque si votre corps a d’abord besoin d’être apaisé, si la nuit appelle de la douceur plutôt que de l’analyse, et si un schéma revient assez souvent pour vous être reflété avec humilité."
      ],
      "highlights": [
        "Une guidance chaleureuse et humaine, sans ton de développement personnel agressif.",
        "Un compagnon local-first qui reste corrigeable.",
        "Conçu pour la vie ordinaire, pas seulement pour les grands drames."
      ]
    },
    "gallery": {
      "eyebrow": "La vraie vie, tenue avec douceur",
      "title": "Miravelys doit donner l’impression d’un lieu où revenir après ce que la vie provoque.",
      "intro": "Miravelys porte une même promesse dans chaque fonction : chaleur, intimité, clarté et assez de calme pour écouter ce qui se passe à l’intérieur.",
      "items": [
        {
          "title": "La clarté doit ramener vers la vie, pas en éloigner",
          "body": "La chaleur, le lien et la joie simple font partie de la promesse. Miravelys ne cherche pas à vous détacher de la vie. Il aide à y revenir avec plus d’espace intérieur.",
          "alt": "Un groupe joyeux d’amis de différentes origines à l’extérieur, à l’heure dorée"
        },
        {
          "title": "Pensé pour la maison, les relations et les vraies soirées",
          "body": "Certains des moments les plus difficiles arrivent dans la vie ordinaire : conversations tendues, retombée émotionnelle, soirées de famille fatigantes, et impression que l’esprit a agrandi la situation.",
          "alt": "Une famille chaleureuse de plusieurs générations réunie à la maison"
        },
        {
          "title": "Assez doux pour la nuit. Assez clair pour le changement",
          "body": "Miravelys peut vous aider à vous poser avant le sommeil, à mettre de côté une pensée en boucle et à voir ce que votre esprit ajoute à la scène. Et quand vous le souhaitez, les questions peuvent devenir plus profondes et plus directes.",
          "alt": "Un groupe vivant d’amis de différentes origines autour d’une table de café en plein air"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Dans le produit",
      "title": "Chaque écran soutient un moment du parcours.",
      "body": "Choisis un écran pour prévisualiser l’app dans ta langue. Chaque mockup correspond à une vraie fonction — écrire, séparer, calmer, se reposer, réfléchir — pas à la décoration.",
      "points": [
        "Get Clear — écris ce qui vous a blessé, déclenché ou serré le corps.",
        "Truth Line — séparez l’événement, l’émotion, le signal du corps, l’histoire, la croyance et l’inconnu.",
        "Home — quatre portes douces quand le corps a besoin de calme d’abord.",
        "Weekly Mirror — remarquez les motifs sans en faire une identité."
      ]
    }
  },
  "hi": {
    "editorial": {
      "eyebrow": "असल ज़िंदगी के लिए बनाया गया",
      "title": "Miravelys उन पलों के लिए है जिन्हें लोग अक्सर अकेले लेकर चलते हैं।",
      "lead": "यह देर रात की विचारों वाली उलझन के लिए है, उस संदेश के लिए जिसे आप बार-बार पढ़ते रहते हैं, सोने से पहले सीने के भारीपन के लिए, परिवार के तनाव के लिए जो उम्मीद से ज़्यादा देर तक साथ रह जाता है, और उस शांत इच्छा के लिए कि भीतर वास्तव में क्या चल रहा है, यह समझा जा सके।",
      "paragraphs": [
        "आपसे “wellness” को सही ढंग से निभाने की अपेक्षा करने के बजाय, Miravelys आपको एक शांत जगह देता है जहाँ आप सच को वैसा कह सकते हैं जैसा वह अभी महसूस हो रहा है। एक ईमानदार पंक्ति ही काफी है। वहाँ से ऐप उस पल को धीमा करने, जो हुआ उसे और जो मन ने जोड़ दिया उसे अलग करने, और एक अधिक दयालु और अधिक सच्चा उत्तर खोजने में मदद करता है।",
        "समय के साथ Miravelys अधिक व्यक्तिगत हो जाता है, लेकिन दखल देने वाला नहीं। यह पहचानता है कि क्या आपके शरीर को सवालों से पहले शांत होने की ज़रूरत है, क्या रात को विश्लेषण से अधिक कोमलता चाहिए, और क्या कोई पैटर्न इतनी बार दिख रहा है कि उसे विनम्रता के साथ आपको वापस दिखाया जा सके।"
      ],
      "highlights": [
        "धक्का देने वाली self-help के बजाय गर्म और मानवीय मार्गदर्शन।",
        "एक local-first साथी जिसे आप सुधार सकते हैं।",
        "सिर्फ़ नाटकीय पलों के लिए नहीं, रोज़मर्रा की ज़िंदगी के लिए बनाया गया।"
      ]
    },
    "gallery": {
      "eyebrow": "असल जीवन, नरमी से थामा हुआ",
      "title": "Miravelys ऐसा महसूस होना चाहिए जहाँ जीवन घटने के बाद लौटा जा सके।",
      "intro": "Miravelys हर अनुभव में वही वादा निभाता है: गर्माहट, privacy, clarity और इतना calm कि भीतर क्या हो रहा है सुना जा सके।",
      "items": [
        {
          "title": "स्पष्टता आपको जीवन से दूर नहीं, वापस उसी में ले जाए",
          "body": "ये चित्र गर्मजोशी, जुड़ाव और साधारण खुशी दिखाते हैं। Miravelys जीवन से अलग हो जाने के बारे में नहीं है। यह जीवन में वापस लौटने के बारे में है—अपने भीतर थोड़ी और जगह के साथ।",
          "alt": "सुनहरी रोशनी में बाहर खुश diverse दोस्तों का एक समूह"
        },
        {
          "title": "घर, रिश्तों और असली शामों के लिए बनाया गया",
          "body": "कई कठिन पल रोज़मर्रा की ज़िंदगी में आते हैं: तनावपूर्ण बातचीत, भावनात्मक असर, थकी हुई पारिवारिक शामें, और यह एहसास कि मन ने स्थिति को उससे बड़ा बना दिया है जितनी वह वास्तव में है।",
          "alt": "घर में साथ बैठा एक गर्मजोशी भरा बहु-पीढ़ी परिवार"
        },
        {
          "title": "रात के लिए पर्याप्त कोमल। बदलाव के लिए पर्याप्त स्पष्ट",
          "body": "Miravelys आपको सोने से पहले शांत होने, बार-बार लौटने वाले विचार को थोड़ी देर के लिए रखने, और यह देखने में मदद कर सकता है कि आपका मन इस दृश्य में क्या जोड़ रहा है। और जब आप चाहें, सवाल और गहरे व सीधे हो सकते हैं।",
          "alt": "खुले कैफ़े में बैठे diverse दोस्तों का एक जीवंत समूह"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "उत्पाद के अंदर",
      "title": "हर स्क्रीन यात्रा के एक पल को सहारा देती है।",
      "body": "अपनी भाषा में ऐप देखने के लिए स्क्रीन चुनें। हर mockup एक असली फ़ीचर से जुड़ा है — लिखना, अलग करना, शांत करना, आराम, देखना — सजावट नहीं।",
      "points": [
        "Get Clear — वह लिखें जो आपको छू गया, trigger किया या शरीर को कस दिया।",
        "Truth Line — घटना, भाव, शरीर के संकेत, कहानी, belief और unknown अलग करें।",
        "Home — चार कोमल दरवाज़े जब शरीर को पहले शांति चाहिए।",
        "Weekly Mirror — सबूत के साथ पैटर्न देखें, बिना उन्हें पहचान बनाए।"
      ]
    }
  },
  "zh": {
    "editorial": {
      "eyebrow": "为真实生活而设计",
      "title": "Miravelys 适合那些人们通常独自承受的时刻。",
      "lead": "它适合深夜反复打转的思绪，适合那条你一遍遍重看的消息，适合睡前胸口的沉重，适合停留太久的家庭紧张感，也适合那种安静却真切的愿望：想弄明白自己内心究竟发生了什么。",
      "paragraphs": [
        "Miravelys 不会要求你“表现得很会自我疗愈”。它给你的是一个平静的空间，让你按此刻真实的感受说出事实。一句诚实的话就够了。接下来，应用会帮助你把这一刻放慢，把真正发生的事和大脑后来添加的内容分开，并找到一个更温和、更真实的回应。",
        "随着使用，Miravelys 会变得更了解你，但不会变得冒犯。它会察觉你的身体是否需要先安定下来，夜晚是否更需要柔和而不是分析，以及某个模式是否已经反复出现到足以被谦逊地反映给你。"
      ],
      "highlights": [
        "温暖而有人味的引导，而不是强推式自助口吻。",
        "以本地优先为核心，并且始终允许你纠正。",
        "为日常生活而造，而不只为戏剧化时刻服务。"
      ]
    },
    "gallery": {
      "eyebrow": "真实生活，被温柔承托",
      "title": "Miravelys 应该像生活发生之后可以回来的地方。",
      "intro": "Miravelys 在每个功能里都承载同一个承诺：温暖、私密、清晰，以及足够的平静去聆听内在正在发生什么。",
      "items": [
        {
          "title": "清晰感应当把人带回生活，而不是带离生活",
          "body": "温度、连接和日常的喜悦是 Miravelys 承诺的一部分。它并不是让人从生活中抽离，而是帮助你带着更多内在空间回到生活里。",
          "alt": "一群不同族裔的朋友在户外金色时刻开心相聚"
        },
        {
          "title": "为家庭、关系与真实夜晚而设计",
          "body": "很多艰难时刻都发生在普通生活里：紧张的对话、 lingering 的情绪余波、疲惫的家庭夜晚，以及那种“大脑把事情越想越大”的感觉。",
          "alt": "一个温暖的多代同堂家庭在家中相聚"
        },
        {
          "title": "足够温柔，适合夜晚；足够清晰，能够带来改变",
          "body": "Miravelys 可以帮助你在睡前安定下来，把反复循环的念头先放一边，并看见你的大脑又给眼前的情境添加了什么。当你准备好了，问题也可以更深入、更直接。",
          "alt": "一群不同族裔的朋友在户外咖啡桌旁轻松交流"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "产品内部",
      "title": "每个屏幕都支撑旅程中的一个时刻。",
      "body": "点选屏幕，用你的语言预览应用。每个 mockup 都对应真实功能——写下、分开、安抚、休息、回看——而不是装饰。",
      "points": [
        "Get Clear — 写下那些刺痛、触发或让你身体发紧的东西。",
        "Truth Line — 分开事件、情绪、身体信号、故事、信念与未知。",
        "Home — 当身体需要先平静时，四个温和的入口。",
        "Weekly Mirror — 看见重复模式，但不把它们变成身份。"
      ]
    }
  },
  "de": {
    "editorial": {
      "eyebrow": "Für das echte Leben gemacht",
      "title": "Miravelys ist für die Momente da, die Menschen meist allein mit sich tragen.",
      "lead": "Für die Gedankenspirale in der Nacht, für die Nachricht, die man immer wieder liest, für die Schwere in der Brust vor dem Schlafen, für familiäre Spannung, die länger nachwirkt als gedacht, und für den stillen Wunsch zu verstehen, was im Inneren eigentlich los ist.",
      "paragraphs": [
        "Statt von dir zu verlangen, Wohlbefinden “richtig” zu performen, gibt dir Miravelys einen ruhigen Ort, an dem du die Wahrheit so benennen kannst, wie sie sich gerade anfühlt. Eine ehrliche Zeile reicht. Von dort aus hilft dir die App, den Moment zu verlangsamen, das Geschehene von dem zu trennen, was der Kopf hinzugedichtet hat, und eine freundlichere, realere Antwort zu finden.",
        "Mit der Zeit wird Miravelys persönlicher, ohne aufdringlich zu werden. Es bemerkt, ob dein Körper erst Beruhigung braucht, ob die Nacht eher Sanftheit als Analyse verlangt und ob ein Muster oft genug auftaucht, um es dir mit Bescheidenheit zurückzuspiegeln."
      ],
      "highlights": [
        "Warme, menschliche Begleitung statt aufdringlicher Selbsthilfe.",
        "Ein local-first Begleiter, der jederzeit korrigierbar bleibt.",
        "Für den Alltag gebaut, nicht nur für dramatische Ausnahmemomente."
      ]
    },
    "gallery": {
      "eyebrow": "Echtes Leben, behutsam gehalten",
      "title": "Miravelys soll sich anfühlen wie ein Ort, zu dem man nach dem Leben zurückkehren kann.",
      "intro": "Miravelys trägt dieses Versprechen durch jede Funktion: Wärme, Privatheit, Klarheit und genug Ruhe, um dem Inneren zuzuhören.",
      "items": [
        {
          "title": "Klarheit sollte zurück ins Leben führen, nicht davon weg",
          "body": "Wärme, Verbindung und alltägliche Freude gehören zum Versprechen von Miravelys. Die App geht nicht darum, sich vom Leben zu lösen. Sie hilft, mit mehr innerem Raum zu ihm zurückzukehren.",
          "alt": "Eine fröhliche Gruppe vielfältiger Freunde im Freien zur goldenen Stunde"
        },
        {
          "title": "Für Zuhause, Beziehungen und echte Abende gemacht",
          "body": "Viele schwere Momente entstehen im normalen Alltag: angespannte Gespräche, emotionaler Nachhall, müde Familienabende und das Gefühl, dass der eigene Kopf die Lage größer gemacht hat, als sie ist.",
          "alt": "Eine warme Familie mit mehreren Generationen, die zuhause zusammensitzt"
        },
        {
          "title": "Sanft genug für die Nacht. Klar genug für Veränderung",
          "body": "Miravelys kann dir helfen, vor dem Schlafen zur Ruhe zu kommen, einen kreisenden Gedanken abzulegen und zu bemerken, was dein Kopf zur Situation dazuerfindet. Wenn du willst, können die Fragen später tiefer und direkter werden.",
          "alt": "Eine lebendige Gruppe vielfältiger Freunde an einem Tisch im Straßencafé"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Im Produkt",
      "title": "Jeder Bildschirm stützt einen Moment auf dem Weg.",
      "body": "Wähle einen Bildschirm, um die App in deiner Sprache zu sehen. Jedes Mockup gehört zu einer echten Funktion — schreiben, trennen, beruhigen, ruhen, reflektieren — nicht zur Dekoration.",
      "points": [
        "Get Clear — schreibe auf, was dich berührt, auslöst oder den Körper verkrampft.",
        "Truth Line — trenne Ereignis, Emotion, Körpersignal, Geschichte, Überzeugung und Unbekanntes.",
        "Home — vier sanfte Eingänge, wenn der Körper zuerst Ruhe braucht.",
        "Weekly Mirror — erkenne Muster, ohne sie zur Identität zu machen."
      ]
    }
  },
  "ja": {
    "editorial": {
      "eyebrow": "現実の暮らしのために",
      "title": "Miravelys は、人がふつう一人で抱えがちな時間のためのものです。",
      "lead": "夜に頭の中で考えが渦を巻くとき、何度も読み返してしまうメッセージがあるとき、眠る前に胸が重いとき、家族の緊張が思ったより長く残っているとき、そして自分の内側で本当は何が起きているのか静かに理解したいときのためにあります。",
      "paragraphs": [
        "Miravelys は、うまく“ウェルネスらしく振る舞う”ことを求めません。今感じているままの真実を、落ち着いた場所で言葉にできるようにします。正直な一文で十分です。そこからアプリは、その瞬間を少しゆっくりにし、実際に起きたことと心が付け足したことを分け、よりやさしく、より本当らしい反応を見つける手助けをします。",
        "使い続けるほど、Miravelys は押しつけがましくならないまま、よりあなたに合っていきます。問いの前に体を落ち着かせる必要があるか、夜には分析よりやわらかさが必要か、あるパターンが十分に繰り返されているかを見て、控えめに映し返します。"
      ],
      "highlights": [
        "押しつける自己啓発ではなく、あたたかく人間的なガイダンス。",
        "ローカルファーストで、いつでも修正できる伴走者。",
        "特別に劇的な瞬間だけでなく、ふつうの毎日のために設計。"
      ]
    },
    "gallery": {
      "eyebrow": "日常をやさしく支える",
      "title": "Miravelys は、日常のあとに戻ってこられる場所のように感じられるべきです。",
      "intro": "Miravelys はすべての機能を通して同じ約束を持っています。温かさ、プライバシー、明晰さ、そして内側で起きていることを聴けるだけの静けさ。",
      "items": [
        {
          "title": "明晰さは、人生から離すのではなく、人生へ戻すものであってほしい",
          "body": "あたたかさ、つながり、そして日常のよろこびは Miravelys の約束の一部です。人生から距離を取るためのものではありません。心の中に少し余白を持って、もう一度人生に戻るためのものです。",
          "alt": "ゴールデンアワーの屋外で笑顔を見せる多様な友人たち"
        },
        {
          "title": "家、関係性、そして本当の夜のために",
          "body": "いちばん難しい瞬間の多くは、日常の中で起こります。ぎこちない会話、感情の尾を引く時間、疲れた家族の夜、そして頭の中で状況が実際より大きくなってしまう感覚。",
          "alt": "家で集う、あたたかな多世代の家族"
        },
        {
          "title": "夜には十分やさしく、変化には十分はっきり",
          "body": "Miravelys は、眠る前に気持ちを落ち着かせ、ぐるぐる回る思考をいったん置き、心が場面に何を付け足しているのかに気づく手助けをします。そして必要なら、問いはもっと深く、もっと率直にもできます。",
          "alt": "屋外カフェのテーブルで会話を楽しむ多様な友人たち"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "プロダクトの中",
      "title": "それぞれの画面が、旅のひとつの瞬間を支えます。",
      "body": "画面を選んで、自分の言語でアプリをプレビュー。各モックアップは飾りではなく、書く・分ける・落ち着く・休む・振り返るという実際の機能に対応しています。",
      "points": [
        "Get Clear — 心を刺したもの、トリガーになったもの、身体を締め付けたものを書く。",
        "Truth Line — 出来事・感情・身体の信号・物語・信念・未知を分ける。",
        "Home — 身体が先に落ち着きを必要とするときの、4つのやさしい入口。",
        "Weekly Mirror — パターンに気づく。でも、それを自己像にはしない。"
      ]
    }
  },
  "es": {
    "editorial": {
      "eyebrow": "Hecho para la vida real",
      "title": "Miravelys es para esos momentos que la gente suele llevar sola.",
      "lead": "Es para la espiral nocturna, para ese mensaje que vuelves a leer una y otra vez, para el peso en el pecho antes de dormir, para la tensión familiar que se quedó contigo más de lo esperado y para el deseo silencioso de entender qué está pasando de verdad dentro de ti.",
      "paragraphs": [
        "En lugar de pedirte que \"performes\" el bienestar, Miravelys te ofrece un lugar tranquilo donde nombrar la verdad tal como se siente ahora. Una sola frase honesta es suficiente. A partir de ahí, la aplicación te ayuda a ralentizar el momento, separar lo que ocurrió de lo que la mente añadió, y encontrar una respuesta más amable y más real.",
        "Con el tiempo, Miravelys se vuelve más personal sin llegar a ser invasivo. Nota si tu cuerpo necesita calma antes de las preguntas, si la noche necesita suavidad en lugar de análisis, y si un patrón ha aparecido lo suficiente como para reflejártelo con humildad."
      ],
      "highlights": [
        "Guía cálida y humana, en lugar de autoayuda empujona.",
        "Un compañero local-first que sigue siendo corregible.",
        "Construido para la vida cotidiana, no solo para momentos dramáticos."
      ]
    },
    "gallery": {
      "eyebrow": "Vida real, sostenida con suavidad",
      "title": "Miravelys debería sentirse como un lugar al que puedes volver después de que la vida pase.",
      "intro": "Miravelys mantiene una misma promesa en cada función: calidez, privacidad, claridad y la calma suficiente para escuchar lo que está pasando dentro.",
      "items": [
        {
          "title": "La claridad debería devolverte a la vida, no alejarte de ella",
          "body": "La calidez, la conexión y la alegría cotidiana son parte de la promesa. Miravelys no se trata de desconectarte de la vida. Se trata de volver a ella con más espacio interior.",
          "alt": "Un grupo alegre de amigos diversos al aire libre a la hora dorada"
        },
        {
          "title": "Hecho para el hogar, las relaciones y las noches de verdad",
          "body": "Algunos de los momentos más difíciles ocurren en la vida diaria: conversaciones tensas, arrastre emocional, noches familiares cansadas y la sensación de que la mente ha agrandado la situación.",
          "alt": "Una familia cálida de varias generaciones reunida en casa"
        },
        {
          "title": "Lo bastante suave para la noche. Lo bastante claro para el cambio",
          "body": "Miravelys puede ayudarte a calmarte antes de dormir, a apartar un pensamiento en bucle y a notar qué está añadiendo tu mente a la escena. Cuando lo desees, las preguntas pueden volverse más profundas y directas.",
          "alt": "Un grupo animado de amigos diversos alrededor de una mesa de café al aire libre"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Dentro del producto",
      "title": "Cada pantalla sostiene un momento del recorrido.",
      "body": "Selecciona una pantalla para previsualizar la app en tu idioma. Cada mockup corresponde a una función real — escribir, separar, calmar, descansar, reflexionar — no a decoración.",
      "points": [
        "Get Clear — escribe lo que te tocó, desencadenó o tensó el cuerpo.",
        "Truth Line — separa evento, emoción, señal del cuerpo, historia, creencia y desconocido.",
        "Home — cuatro puertas suaves cuando el cuerpo necesita calma primero.",
        "Weekly Mirror — nota patrones sin convertirlos en identidad."
      ]
    }
  },
  "pt": {
    "editorial": {
      "eyebrow": "Feito para a vida real",
      "title": "Miravelys é para esses momentos que as pessoas costumam carregar sozinhas.",
      "lead": "É para a espiral noturna, para essa mensagem que relês vezes sem conta, para o peso no peito antes de dormir, para a tensão familiar que ficou contigo mais tempo do que esperavas e para o desejo silencioso de perceber o que está realmente a acontecer dentro de ti.",
      "paragraphs": [
        "Em vez de te pedir para \"performares\" o bem-estar, o Miravelys oferece-te um lugar calmo onde podes nomear a verdade tal como ela se sente agora. Uma frase honesta é suficiente. A partir daí, a app ajuda-te a abrandar o momento, separar o que aconteceu do que a mente acrescentou, e encontrar uma resposta mais gentil e mais real.",
        "Com o tempo, o Miravelys torna-se mais pessoal sem se tornar invasivo. Percebe se o teu corpo precisa primeiro de calma, se a noite pede suavidade em vez de análise, e se um padrão apareceu vezes suficientes para te ser reflectido com humildade."
      ],
      "highlights": [
        "Orientação calorosa e humana, em vez de autoajuda agressiva.",
        "Um companheiro local-first que continua corrigível.",
        "Construído para a vida ordinária, não só para momentos dramáticos."
      ]
    },
    "gallery": {
      "eyebrow": "Vida real, acolhida com suavidade",
      "title": "O Miravelys deve sentir-se como um lugar para onde regressar depois de a vida acontecer.",
      "intro": "O Miravelys mantém uma só promessa em cada funcionalidade: calor, privacidade, clareza e calma suficiente para ouvir o que está a acontecer dentro.",
      "items": [
        {
          "title": "A clareza deve levar de volta à vida, não afastar dela",
          "body": "O calor, a ligação e a alegria quotidiana fazem parte da promessa. O Miravelys não é sobre te desligares da vida. É sobre regressares a ela com mais espaço interior.",
          "alt": "Um grupo alegre de amigos diversos ao ar livre na hora dourada"
        },
        {
          "title": "Feito para casa, relações e noites reais",
          "body": "Alguns dos momentos mais difíceis acontecem na vida quotidiana: conversas tensas, ressaca emocional, noites familiares cansadas e a sensação de que a mente fez a situação maior do que ela é.",
          "alt": "Uma família calorosa de várias gerações reunida em casa"
        },
        {
          "title": "Suave o suficiente para a noite. Claro o suficiente para a mudança",
          "body": "O Miravelys pode ajudar-te a acalmar antes de dormir, a deixar de lado um pensamento em loop e a notar o que a tua mente está a acrescentar à cena. Quando quiseres, as perguntas podem tornar-se mais profundas e directas.",
          "alt": "Um grupo animado de amigos diversos à mesa de um café ao ar livre"
        }
      ]
    },
    "mockupsBridge": {
      "eyebrow": "Dentro do produto",
      "title": "Cada ecrã sustenta um momento da jornada.",
      "body": "Escolhe um ecrã para pré-visualizar a app no teu idioma. Cada mockup corresponde a uma função real — escrever, separar, acalmar, descansar, reflectir — não decoração.",
      "points": [
        "Get Clear — escreve o que te tocou, desencadeou ou apertou o corpo.",
        "Truth Line — separa evento, emoção, sinal do corpo, história, crença e desconhecido.",
        "Home — quatro portas suaves quando o corpo precisa primeiro de calma.",
        "Weekly Mirror — percebe padrões sem os transformar em identidade."
      ]
    }
  }
};

export function resolveMarketingCopy(lang) {
  return marketingCopy[lang] ?? marketingCopy.en;
}

export default marketingCopy;
