const en = {
  hero: { deviceLabel: 'Miravelys product story' },
  journey: { progressAria: 'Miravelys product story — fixed phone screen changes as you scroll' },
  scenes: {
    overview: {
      eyebrow: 'What Miravelys is',
      title: 'A private companion for moments that feel bigger inside than they looked outside.',
      body: 'Miravelys is for the moment that looked small outside, but became a whole story inside. It helps you write what feels true, separate the layers, and choose whether you need calm, clarity, sleep, or a smaller next step.',
      cta: 'Begin the product story',
      before: 'One moment feels like everything',
      after: 'A softer place to begin',
      feeling: '“Something happened, and now my whole inner world feels loud.”',
      shift: 'Start with the moment you have, not the perfect words.',
    },
    writeInside: {
      eyebrow: 'Write it down',
      title: 'Write what touched you, triggered you, tightened your body, or kept returning in your mind.',
      body: 'In Get Clear, you can write emotions, beliefs, body reactions, repeated thoughts, fears, or one messy sentence. Miravelys treats that entry as a beginning, not a performance.',
      cta: 'See Get Clear',
      before: 'The thought keeps circling',
      after: 'It has a private place to land',
      feeling: '“I know this may be exaggerated, but it still feels real.”',
      shift: 'Write honestly first. Understand gently after.',
    },
    separateLayers: {
      eyebrow: 'Separate the layers',
      title: 'Separate the event, emotion, body signal, mind story, possible belief, and unknown.',
      body: 'Truth Line helps slow the moment down. It separates what happened from the body reaction, the emotion, the meaning your mind added, possible belief candidates, and what is still unknown.',
      cta: 'Explore Truth Line',
      before: 'Everything feels fused together',
      after: 'The pieces have space',
      feeling: 'A pause becomes proof. A fear becomes a fact. A story begins to feel like identity.',
      shift: 'When the layers separate, the next step can become kinder.',
    },
    patternsOverTime: {
      eyebrow: 'Notice patterns',
      title: 'Over time, repeated notes may reveal old protections and repeated inner stories, without turning them into identity.',
      body: 'Weekly Mirror looks for themes only when there is enough evidence. It may help you notice repeated beliefs or emotional loops, while keeping every pattern humble, editable, and separate from identity.',
      cta: 'See Weekly Mirror',
      before: '“This keeps happening. Maybe this is just me.”',
      after: 'Information, not identity',
      feeling: 'A repeated belief starts to sound like a life sentence.',
      shift: 'Notice what repeats without turning it into who you are.',
    },
    calmFirst: {
      eyebrow: 'Calm the body first',
      title: 'Sometimes the first step is not analysis.',
      body: 'Four Gentle Doorways offers breathing, feeling awareness, meditation, sleep support, and energy alignment so the body can settle before the mind tries to understand everything.',
      doorsAriaLabel: 'Four gentle doorways',
      cta: 'See the doorways',
      before: 'The body is too loud for clarity',
      after: 'A softer nervous system',
      feeling: 'You do not need more words yet. You need a little more ground.',
      shift: 'Breathe, feel, slow down, then look again.',
      doors: [
        { label: 'Breathe With Me', hint: 'When your body needs to slow down first' },
        { label: 'Meditate With Me', hint: 'When you need quiet attention, not fixing' },
        { label: 'Sleep With Me', hint: 'When the night needs softness, not dissection' },
        { label: 'Align Your Energy', hint: 'When you want to return to yourself more gently' },
      ],
    },
    soundsAndSleep: {
      eyebrow: 'Sleep and sounds',
      title: 'Unique Miravelys audio spaces are for moments when there are too many words in the head and the body needs somewhere softer to land.',
      body: 'Miravelys includes calming sounds created for its world. They support breathing, meditation, sleep, and moments when the body needs a softer space more than another explanation.',
      cta: 'See Sleep With Me',
      before: 'Night makes the story heavier',
      after: 'Tomorrow can wait',
      feeling: '“If I stop thinking now, I will lose control of the problem.”',
      shift: 'Let the body land before the mind continues.',
    },
    privacyControl: {
      eyebrow: 'Privacy and control',
      title: 'Miravelys does not label you. It helps you notice what may be repeating, while you decide what fits.',
      body: 'The app does not diagnose, decide who you are, or claim final certainty. It is local-first by design, correction-friendly, and careful with uncertainty.',
      cta: 'See the privacy promise',
      before: 'Apps that guess too much',
      after: 'A companion that stays correctable',
      feeling: 'You want support, not a system that defines you.',
      shift: 'Not therapy. Not diagnosis. A private conversation with yourself.',
    },
  },
  trust: {
    eyebrow: 'Trust',
    title: 'Private by design. Humble by nature.',
    body: 'Miravelys helps organize what you share, shows uncertainty, and lets you correct what does not fit.',
    notTherapy: 'Not diagnosis. Not therapy. A clearer conversation with yourself.',
  },
  finale: {
    eyebrow: 'Start here',
    title: 'Begin with one clear moment.',
    body: 'No streaks. No pressure. No performance. Just a private place for what feels tangled.',
    primary: 'Download Miravelys',
    secondary: 'Early access',
  },
};

const ru = {
  hero: { deviceLabel: 'История продукта Miravelys' },
  journey: { progressAria: 'История продукта Miravelys — экран в телефоне меняется при прокрутке' },
  scenes: {
    overview: { eyebrow: 'Что такое Miravelys', title: 'Личный спутник для моментов, которые внутри кажутся больше, чем выглядели снаружи.', body: 'Miravelys — для того момента, который снаружи выглядел мелким, а внутри стал целой историей. Он помогает записать то, что кажется правдой, разделить слои и выбрать: нужен ли покой, ясность, сон или маленький следующий шаг.', cta: 'Начать историю продукта', before: 'Один момент кажется всем', after: 'Более мягкое начало', feeling: '«Что-то произошло, и внутри стало слишком громко.»', shift: 'Начни с того момента, который есть, а не с идеальных слов.' },
    writeInside: { eyebrow: 'Записать', title: 'Запиши то, что задело, вызвало реакцию, свело тело или крутилось в голове.', body: 'В "Внести ясность" можно записать эмоцию, убеждение, реакцию тела, повторяющуюся мысль, страх или одну спутанную фразу. Miravelys воспринимает это как начало, а не как выступление.', cta: 'Смотреть "Внести ясность"', before: 'Мысль ходит кругами', after: 'У неё есть личное место', feeling: '«Я знаю, что это может быть преувеличением, но оно всё равно кажется настоящим.»', shift: 'Сначала напиши честно. Потом пойми бережно.' },
    separateLayers: { eyebrow: 'Разделить слои', title: 'Отдели событие, эмоцию, сигнал тела, историю ума, возможное убеждение и неизвестное.', body: '"Линия ясности" помогает замедлить момент. Он отделяет то, что произошло, от реакции тела, эмоции, смысла, который добавил ум, возможных убеждений и того, что пока неизвестно.', cta: 'Открыть "Линия ясности"', before: 'Всё слилось вместе', after: 'У частей появляется пространство', feeling: 'Пауза становится доказательством. Страх становится фактом. История начинает казаться личностью.', shift: 'Когда слои разделены, следующий шаг может стать добрее.' },
    patternsOverTime: { eyebrow: 'Замечать паттерны', title: 'Со временем повторяющиеся записи могут показать старые защиты и повторяющиеся внутренние истории — без превращения их в личность.', body: '"Еженедельное зеркало" ищет темы только при достаточных основаниях. Он может помочь заметить повторяющиеся убеждения или эмоциональные петли, но оставляет каждый паттерн скромным, редактируемым и отдельным от личности.', cta: 'Смотреть "Еженедельное зеркало"', before: '«Это повторяется. Может, это просто я.»', after: 'Информация, а не личность', feeling: 'Повторяющееся убеждение начинает звучать как приговор.', shift: 'Замечай то, что повторяется, не превращая это в то, кто ты.' },
    calmFirst: { eyebrow: 'Сначала тело', title: 'Иногда первый шаг — не анализ.', body: '"Четыре мягких дверных проема" предлагает дыхание, внимание к ощущениям, медитацию, поддержку сна и мягкое выравнивание энергии, чтобы тело успело успокоиться до того, как ум попытается всё понять.', doorsAriaLabel: 'Четыре мягких входа', cta: 'Смотреть входы', before: 'Телу слишком громко для ясности', after: 'Более мягкая нервная система', feeling: 'Тебе пока не нужны новые слова. Тебе нужно немного больше опоры.', shift: 'Дыши, почувствуй тело, замедлись — потом посмотри снова.', doors: [{ label: '"Дыши со мной"', hint: 'Когда телу сначала нужно замедлиться' }, { label: '"Медитируй со мной"', hint: 'Когда нужно тихое внимание, а не исправление' }, { label: '"Засыпай со мной"', hint: 'Когда ночи нужна мягкость' }, { label: '"Выровняйте свою энергию"', hint: 'Когда хочется мягче вернуться к себе' }] },
    soundsAndSleep: { eyebrow: 'Сон и звуки', title: 'Уникальные аудиопространства Miravelys — для моментов, когда в голове слишком много слов и телу нужно мягкое место для приземления.', body: 'В Miravelys есть успокаивающие звуки, созданные специально для его мира. Они поддерживают дыхание, медитацию, сон и моменты, когда телу нужен мягкий простор больше, чем новое объяснение.', cta: 'Смотреть "Засыпай со мной"', before: 'Ночь делает историю тяжелее', after: 'Завтра может подождать', feeling: '«Если я перестану думать, я потеряю контроль над проблемой.»', shift: 'Позволь телу приземлиться, прежде чем ум продолжит.' },
    privacyControl: { eyebrow: 'Приватность и контроль', title: 'Miravelys не навешивает ярлыков. Он помогает заметить то, что может повторяться, а решать, что подходит, остаётся за тобой.', body: 'Приложение не ставит диагнозы, не решает, кто ты, и не заявляет абсолютную истину. Оно local-first по замыслу, дружелюбно к исправлениям и осторожно с неопределённостью.', cta: 'Смотреть обещание приватности', before: 'Приложения, которые слишком много угадывают', after: 'Спутник, которого можно исправлять', feeling: 'Тебе нужна поддержка, а не система, которая определяет тебя.', shift: 'Не терапия. Не диагноз. Личный разговор с собой.' },
  },
  trust: { eyebrow: 'Доверие', title: 'Приватность по замыслу. Скромность по природе.', body: 'Miravelys помогает организовать то, чем ты поделился, показывает неопределённость и позволяет исправлять то, что не подходит.', notTherapy: 'Не диагноз. Не терапия. Более ясный разговор с собой.' },
  finale: { eyebrow: 'Начни здесь', title: 'Начни с одного ясного момента.', body: 'Без серий. Без давления. Без выступления. Просто личное место для того, что запуталось.', primary: 'Скачать Miravelys', secondary: 'Ранний доступ' },
};

const ro = {
  hero: { deviceLabel: 'Povestea produsului Miravelys' },
  journey: { progressAria: 'Povestea produsului Miravelys — ecranul din telefon se schimbă la derulare' },
  scenes: {
    overview: { eyebrow: 'Ce este Miravelys', title: 'Un companion privat pentru momente care par mai mari în interior decât arătau afară.', body: 'Miravelys este pentru momentul care afară părea mic, dar înăuntru a devenit o poveste întreagă. Te ajută să scrii ce se simte adevărat, să separi straturile și să alegi dacă ai nevoie de calm, claritate, somn sau un pas următor mai mic.', cta: 'Începe povestea produsului', before: 'Un moment pare totul', after: 'Un început mai blând', feeling: '„S-a întâmplat ceva, iar în interior totul e prea zgomotos.”', shift: 'Începe cu momentul pe care îl ai, nu cu cuvinte perfecte.' },
    writeInside: { eyebrow: 'Scrie', title: 'Scrie ce te-a atins, ce a declanșat, ce ți-a strâns corpul sau ce a tot revenit în minte.', body: 'În "Linie clară" poți scrie emoții, convingeri, reacții ale corpului, gânduri repetate, frici sau o propoziție dezordonată. Miravelys tratează asta ca un început, nu ca o performanță.', cta: 'Vezi "Linie clară"', before: 'Gândul se învârte', after: 'Are un loc privat unde să cadă', feeling: '„Știu că poate exagerez, dar încă se simte real.”', shift: 'Scrie sincer întâi. Înțelege blând după.' },
    separateLayers: { eyebrow: 'Separă straturile', title: 'Separă evenimentul, emoția, semnalul corpului, povestea minții, convingerea posibilă și necunoscutul.', body: '"Linie clară" încetinește momentul. Separă ce s-a întâmplat de reacția corpului, emoție, sensul adăugat de minte, posibile convingeri și ce rămâne necunoscut.', cta: 'Explorează "Linie clară"', before: 'Totul pare lipit laolaltă', after: 'Părțile au spațiu', feeling: 'O pauză devine dovadă. O frică devine fapt. O poveste începe să pară identitate.', shift: 'Când straturile se separă, următorul pas poate deveni mai blând.' },
    patternsOverTime: { eyebrow: 'Observă tipare', title: 'În timp, notele repetate pot dezvălui vechi protecții și povești interioare repetate, fără să le transforme în identitate.', body: '"Oglinda săptămânală" caută teme doar când există suficiente indicii. Te poate ajuta să observi convingeri repetate sau bucle emoționale, păstrând fiecare tipar modest, editabil și separat de identitate.', cta: 'Vezi "Oglinda săptămânală"', before: '„Asta se repetă. Poate așa sunt eu."', after: 'Informație, nu identitate', feeling: 'O convingere repetată începe să sune ca o sentință.', shift: 'Observă ce se repetă fără să transformi asta în cine ești.' },
    calmFirst: { eyebrow: 'Mai întâi corpul', title: 'Uneori primul pas nu este analiza.', body: '"Patru intrări blânde" oferă respirație, atenție la senzații, meditație, sprijin pentru somn și aliniere blândă a energiei, ca trupul să se așeze înainte ca mintea să încerce să înțeleagă tot.', doorsAriaLabel: 'Patru uși blânde', cta: 'Vezi ușile', before: 'Corpul e prea zgomotos pentru claritate', after: 'Un sistem nervos mai moale', feeling: 'Nu ai nevoie de mai multe cuvinte încă. Ai nevoie de puțin mai mult pământ.', shift: 'Respiră, simte, încetinește, apoi privește din nou.', doors: [{ label: '"Respiră cu mine"', hint: 'Când corpul trebuie să încetinească întâi' }, { label: '"Meditează cu mine"', hint: 'Când ai nevoie de atenție liniștită' }, { label: '"Dormi cu mine"', hint: 'Când noaptea are nevoie de blândețe' }, { label: '"Aliniază-ți energia"', hint: 'Când vrei să revii la tine mai blând' }] },
    soundsAndSleep: { eyebrow: 'Somn și sunete', title: 'Spațiile audio unice Miravelys sunt pentru momentele în care sunt prea multe cuvinte în cap și corpul are nevoie de un loc mai moale unde să se așeze.', body: 'Miravelys include sunete calmante create pentru lumea lui. Ele susțin respirația, meditația, somnul și momentele când corpul are nevoie de un spațiu mai blând decât de o nouă explicație.', cta: 'Vezi "Dormi cu mine"', before: 'Noaptea face povestea mai grea', after: 'Mâine poate aștepta', feeling: '„Dacă mă opresc din gândit, pierd controlul problemei.”', shift: 'Lasă corpul să aterizeze înainte ca mintea să continue.' },
    privacyControl: { eyebrow: 'Confidențialitate și control', title: 'Miravelys nu te etichetează. Te ajută să observi ce s-ar putea repeta, în timp ce tu decizi ce se potrivește.', body: 'Aplicația nu diagnostichează, nu decide cine ești și nu pretinde adevăr absolut. Este local-first, ușor de corectat și atentă cu incertitudinea.', cta: 'Vezi promisiunea de confidențialitate', before: 'Aplicații care ghicesc prea mult', after: 'Un companion corectabil', feeling: 'Vrei sprijin, nu un sistem care te definește.', shift: 'Nu terapie. Nu diagnostic. O conversație privată cu tine.' },
  },
  trust: { eyebrow: 'Încredere', title: 'Privat prin design. Modest prin natură.', body: 'Miravelys ajută la organizarea a ceea ce împărtășești, arată incertitudinea și te lasă să corectezi ce nu se potrivește.', notTherapy: 'Nu diagnostic. Nu terapie. O conversație mai clară cu tine.' },
  finale: { eyebrow: 'Începe aici', title: 'Începe cu un moment clar.', body: 'Fără serii. Fără presiune. Fără performanță. Doar un loc privat pentru ce se simte încâlcit.', primary: 'Descarcă Miravelys', secondary: 'Acces timpuriu' },
};

const fr = {
  hero: { deviceLabel: 'Histoire produit de Miravelys' },
  journey: { progressAria: 'Histoire produit Miravelys — l’écran du téléphone change au défilement' },
  scenes: {
    overview: { eyebrow: 'Ce qu’est Miravelys', title: 'Un compagnon privé pour les moments qui semblent plus grands à l’intérieur qu’ils ne paraissaient dehors.', body: 'Miravelys est pour le moment qui avait l’air petit dehors, mais qui est devenu toute une histoire à l’intérieur. Il vous aide à écrire ce qui semble vrai, à séparer les couches et à choisir si vous avez besoin de calme, de clarté, de sommeil ou d’un prochain pas plus petit.', cta: 'Commencer l’histoire du produit', before: 'Un moment semble devenir tout', after: 'Un début plus doux', feeling: '« Quelque chose s’est passé, et tout mon monde intérieur est devenu bruyant. »', shift: 'Commencez avec le moment réel, pas avec des mots parfaits.' },
    writeInside: { eyebrow: 'Écrire', title: 'Écrivez ce qui vous a blessé, déclenché, serré le corps ou tourné en boucle dans l’esprit.', body: 'Dans "Ligne claire", vous pouvez écrire émotions, croyances, réactions du corps, pensées répétées, peurs ou une phrase confuse. Miravelys l’accueille comme un début, pas comme une performance.', cta: 'Voir "Ligne claire"', before: 'La pensée tourne en boucle', after: 'Elle a un lieu privé où se poser', feeling: '« Je sais que c’est peut-être exagéré, mais cela semble encore réel. »', shift: 'Écrire honnêtement d’abord. Comprendre doucement ensuite.' },
    separateLayers: { eyebrow: 'Séparer les couches', title: 'Séparez l’événement, l’émotion, le signal du corps, l’histoire de l’esprit, la croyance possible et l’inconnu.', body: '"Ligne claire" ralentit le moment. Il sépare ce qui s’est passé de la réaction du corps, de l’émotion, du sens ajouté par l’esprit, des croyances possibles et de ce qui reste inconnu.', cta: 'Explorer "Ligne claire"', before: 'Tout semble fusionné', after: 'Les pièces ont de l’espace', feeling: 'Une pause devient une preuve. Une peur devient un fait. Une histoire commence à ressembler à une identité.', shift: 'Quand les couches se séparent, le prochain pas peut devenir plus doux.' },
    patternsOverTime: { eyebrow: 'Remarquer les schémas', title: 'Avec le temps, les notes répétées peuvent révéler de vieilles protections et des histoires intérieures répétées — sans en faire une identité.', body: '"Miroir hebdomadaire" cherche des thèmes seulement lorsqu’il y a assez d’indices. Il peut aider à remarquer des croyances répétées ou des boucles émotionnelles, tout en gardant chaque schéma humble, modifiable et séparé de l’identité.', cta: 'Voir "Miroir hebdomadaire"', before: '« Cela revient encore. Peut-être que c’est moi. »', after: 'Une information, pas une identité', feeling: 'Une croyance répétée commence à sonner comme une condamnation.', shift: 'Remarquez ce qui se répète sans en faire qui vous êtes.' },
    calmFirst: { eyebrow: 'Calmer le corps d’abord', title: 'Parfois, le premier pas n’est pas l’analyse.', body: '"Quatre portes douces" propose respiration, attention aux sensations, méditation, soutien au sommeil et alignement doux de l’énergie, pour que le corps puisse se poser avant que l’esprit tente de tout comprendre.', doorsAriaLabel: 'Quatre portes douces', cta: 'Voir les portes', before: 'Le corps est trop bruyant pour la clarté', after: 'Un système nerveux plus doux', feeling: 'Vous n’avez pas encore besoin de plus de mots. Vous avez besoin d’un peu plus d’ancrage.', shift: 'Respirer, sentir, ralentir, puis regarder à nouveau.', doors: [{ label: '"Respire avec moi"', hint: 'Quand le corps doit d’abord ralentir' }, { label: '"Médite avec moi"', hint: 'Quand vous avez besoin d’attention calme' }, { label: '"Dors avec moi"', hint: 'Quand la nuit a besoin de douceur' }, { label: '"Alignez votre énergie"', hint: 'Quand vous voulez revenir à vous doucement' }] },
    soundsAndSleep: { eyebrow: 'Sommeil et sons', title: 'Les espaces sonores uniques de Miravelys sont pour les moments où il y a trop de mots dans la tête et où le corps a besoin d’un lieu plus doux pour atterrir.', body: 'Miravelys inclut des sons apaisants créés pour son univers. Ils soutiennent la respiration, la méditation, le sommeil et les moments où le corps a besoin d’un espace plus doux qu’une autre explication.', cta: 'Voir "Dors avec moi"', before: 'La nuit alourdit l’histoire', after: 'Demain peut attendre', feeling: '« Si j’arrête de penser, je vais perdre le contrôle du problème. »', shift: 'Laissez le corps se poser avant que l’esprit continue.' },
    privacyControl: { eyebrow: 'Confidentialité et contrôle', title: 'Miravelys ne vous étiquette pas. Il vous aide à remarquer ce qui se répète peut-être, pendant que vous décidez de ce qui vous correspond.', body: 'L’application ne diagnostique pas, ne décide pas qui vous êtes et ne revendique pas de vérité absolue. Elle est local-first, facile à corriger et prudente avec l’incertitude.', cta: 'Voir la promesse de confidentialité', before: 'Des apps qui devinent trop', after: 'Un compagnon corrigeable', feeling: 'Vous voulez du soutien, pas un système qui vous définit.', shift: 'Pas une thérapie. Pas un diagnostic. Une conversation privée avec vous-même.' },
  },
  trust: { eyebrow: 'Confiance', title: 'Privé par design. Humble par nature.', body: 'Miravelys aide à organiser ce que vous partagez, montre l’incertitude et vous laisse corriger ce qui ne convient pas.', notTherapy: 'Pas un diagnostic. Pas une thérapie. Une conversation plus claire avec vous-même.' },
  finale: { eyebrow: 'Commencer ici', title: 'Commencez avec un moment clair.', body: 'Pas de séries. Pas de pression. Pas de performance. Juste un lieu privé pour ce qui semble emmêlé.', primary: 'Télécharger Miravelys', secondary: 'Accès anticipé' },
};

const hi = {
  hero: { deviceLabel: 'Miravelys product story' },
  journey: { progressAria: 'Miravelys product story — scroll करते समय phone screen बदलती है' },
  scenes: {
    overview: { eyebrow: 'Miravelys क्या है', title: 'उन पलों के लिए private companion जो बाहर दिखने से ज़्यादा अंदर बड़े लगते हैं।', body: 'Miravelys उस पल के लिए है जो बाहर से छोटा लगा, लेकिन अंदर पूरी कहानी बन गया। यह आपको जो सच लगता है उसे लिखने, परतें अलग करने और फिर चुनने में मदद करता है कि आपको शांति, स्पष्टता, नींद या एक छोटा अगला कदम चाहिए।', cta: 'Product story शुरू करें', before: 'एक पल सब कुछ लगने लगता है', after: 'शुरुआत करने की नरम जगह', feeling: '“कुछ हुआ, और अंदर सब बहुत loud हो गया।”', shift: 'Perfect words नहीं, अभी जो moment है उससे शुरू करें.' },
    writeInside: { eyebrow: 'लिखें', title: 'वह लिखें जो आपको छू गया, trigger किया, शरीर को कस दिया, या दिमाग में बार-बार लौटता रहा।', body: '"स्पष्ट रेखा" में आप emotions, beliefs, body reactions, repeated thoughts, fears या एक messy sentence लिख सकते हैं। Miravelys इसे performance नहीं, शुरुआत मानता है।', cta: '"स्पष्ट रेखा" देखें', before: 'Thought घूमता रहता है', after: 'उसे land करने की private जगह मिलती है', feeling: '“मुझे पता है यह exaggerated हो सकता है, पर अभी real लगता है।”', shift: 'पहले honestly लिखें। फिर gently समझें.' },
    separateLayers: { eyebrow: 'Layers अलग करें', title: 'घटना, भाव, शरीर के संकेत, मन की कहानी, संभावित belief और unknown को अलग करें।', body: '"स्पष्ट रेखा" moment को धीमा करता है। यह जो हुआ, body reaction, emotion, mind ने जो meaning जोड़ा, possible belief और जो अभी unknown है — उन्हें अलग देखने में मदद करता है।', cta: '"स्पष्ट रेखा" देखें', before: 'सब कुछ एक साथ मिल जाता है', after: 'हर हिस्से को space मिलता है', feeling: 'Pause proof बन जाता है। Fear fact बन जाता है। Story identity जैसी लगने लगती है।', shift: 'Layers अलग हों तो अगला कदम kinder हो सकता है.' },
    patternsOverTime: { eyebrow: 'Patterns notice करें', title: 'समय के साथ, दोहराए गए notes पुरानी protections और दोहराई गई inner कहानियाँ दिखा सकते हैं — बिना उन्हें पहचान बनाए।', body: '"साप्ताहिक दर्पण" themes तभी दिखाता है जब पर्याप्त evidence हो। यह repeated beliefs या emotional loops notice करने में मदद कर सकता है, पर हर pattern humble, editable और identity से अलग रहता है।', cta: '"साप्ताहिक दर्पण" देखें', before: '“यह फिर हो रहा है। शायद मैं ऐसी ही हूँ।”', after: 'Information, identity नहीं', feeling: 'Repeated belief life sentence जैसा लगने लगता है।', shift: 'जो repeat होता है उसे देखें, पर उसे अपना पूरा self न बना दें.' },
    calmFirst: { eyebrow: 'पहले body calm', title: 'कभी-कभी पहला step analysis नहीं होता।', body: '"चार कोमल प्रवेश द्वार" breathing, feeling awareness, meditation, sleep support और gentle energy alignment देता है, ताकि mind सब समझने से पहले body settle कर सके।', doorsAriaLabel: 'चार gentle doorways', cta: 'Doorways देखें', before: 'Body clarity के लिए बहुत loud है', after: 'Softer nervous system', feeling: 'अभी और words नहीं चाहिए। थोड़ी जमीन चाहिए।', shift: 'Breathe करें, feel करें, slow down करें, फिर देखें.', doors: [{ label: '"मेरे साथ साँस लें"', hint: 'जब body को पहले slow होना हो' }, { label: '"मेरे साथ ध्यान करें"', hint: 'जब quiet attention चाहिए' }, { label: '"मेरे साथ सोएं"', hint: 'जब night को softness चाहिए' }, { label: '"अपनी ऊर्जा को संरेखित करें"', hint: 'जब आप gently अपने पास लौटना चाहें' }] },
    soundsAndSleep: { eyebrow: 'Sleep और sounds', title: 'Miravelys के unique audio spaces उन पलों के लिए हैं जब सिर में बहुत सारे शब्द हों और शरीर को land करने के लिए कहीं नरम चाहिए।', body: 'Miravelys में calming sounds हैं जो इसी world के लिए बनाए गए हैं। वे breathing, meditation, sleep और उन moments को support करते हैं जब body को एक और explanation से ज़्यादा softer space चाहिए।', cta: '"मेरे साथ सोएं" देखें', before: 'Night story को heavy बना देती है', after: 'Tomorrow wait कर सकता है', feeling: '“अगर मैंने सोचना बंद किया, तो problem पर control खो दूँगा।”', shift: 'Mind continue करे उससे पहले body को land करने दें.' },
    privacyControl: { eyebrow: 'Privacy और control', title: 'Miravelys आपको label नहीं करता। यह आपको यह notice करने में मदद करता है कि क्या repeat हो सकता है, जबकि आप तय करते हैं कि क्या सही है।', body: 'App diagnose नहीं करता, यह decide नहीं करता कि आप कौन हैं, और final certainty claim नहीं करता। यह local-first, correction-friendly और uncertainty के साथ careful है।', cta: 'Privacy promise देखें', before: 'Apps जो बहुत guess करते हैं', after: 'Correctable companion', feeling: 'आपको support चाहिए, define करने वाला system नहीं।', shift: 'Therapy नहीं। Diagnosis नहीं। अपने साथ private conversation.' },
  },
  trust: { eyebrow: 'Trust', title: 'Private by design. Humble by nature.', body: 'Miravelys आपकी shared बातों को organize करता है, uncertainty दिखाता है और जो fit नहीं होता उसे correct करने देता है।', notTherapy: 'Diagnosis नहीं। Therapy नहीं। अपने साथ clearer conversation.' },
  finale: { eyebrow: 'यहाँ से शुरू करें', title: 'एक clear moment से शुरू करें.', body: 'No streaks. No pressure. No performance. बस tangled चीज़ों के लिए private जगह.', primary: 'Miravelys डाउनलोड करें', secondary: 'Early access' },
};

const zh = {
  hero: { deviceLabel: 'Miravelys 产品故事' },
  journey: { progressAria: 'Miravelys 产品故事——滚动时手机内的屏幕会变化' },
  scenes: {
    overview: { eyebrow: 'Miravelys 是什么', title: '为那些在外表看起来很小、内心却感觉更大的片刻而设的私人陪伴。', body: 'Miravelys 为那个外在看起来很小、在心里却变成一整套故事的时刻而生。你可以写下当下感觉真实的东西，把层次分开，然后选择：你需要平静、清晰、睡眠，还是一个更小的下一步。', cta: '开始产品故事', before: '一个时刻像变成了全部', after: '一个更柔软的开始', feeling: '“发生了一件事，然后我的内在世界变得很吵。”', shift: '从真实的这一刻开始，而不是从完美的语言开始。' },
    writeInside: { eyebrow: '写下来', title: '写下那些刺痛你的、触发你的、让你身体发紧的，或反复回到脑中的东西。', body: '在 "清晰线索" 里，你可以写情绪、信念、身体反应、重复的想法、恐惧，或一句混乱的话。Miravelys 把它当作开始，而不是表现。', cta: '查看 "清晰线索"', before: '想法一直打转', after: '它有了一个私密落点', feeling: '“我知道这也许被放大了，但它现在仍然很真实。”', shift: '先诚实写下，再温柔理解。' },
    separateLayers: { eyebrow: '分开层次', title: '把事件、情绪、身体信号、头脑故事、可能的信念和未知分开。', body: '"清晰线索" 帮你放慢这一刻。它把发生的事、身体反应、情绪、头脑添加的意义、可能的信念，以及仍然未知的部分分开。', cta: '探索 "清晰线索"', before: '一切都混在一起', after: '每一部分都有了空间', feeling: '一次停顿变成证据。一个恐惧变成事实。一个故事开始像身份。', shift: '当层次被分开，下一步可以更温柔。' },
    patternsOverTime: { eyebrow: '看见模式', title: '随着时间推移，重复的记录可能揭示旧有的防御和重复的内心故事——而不把它们变成身份。', body: '"每周镜子" 只在有足够依据时寻找主题。它可以帮助你看见重复的信念或情绪循环，同时让每个模式保持谦逊、可编辑，并与身份分开。', cta: '查看 "每周镜子"', before: '“这又发生了。也许这就是我。”', after: '信息，不是身份', feeling: '一个重复的信念开始听起来像终身判决。', shift: '看见重复的东西，但不要把它变成你是谁。' },
    calmFirst: { eyebrow: '先安顿身体', title: '有时第一步不是分析。', body: '"四个温柔的门口" 提供呼吸、感受觉察、冥想、睡眠支持和温柔的能量回到自身，让身体先安定下来，再让头脑尝试理解一切。', doorsAriaLabel: '四个温柔入口', cta: '查看入口', before: '身体太吵，无法清晰', after: '更柔软的神经系统', feeling: '你现在不需要更多语言。你需要更多落地感。', shift: '呼吸，感受，慢下来，然后再看。', doors: [{ label: '"与我呼吸"', hint: '当身体需要先慢下来' }, { label: '"与我一起冥想"', hint: '当你需要安静注意力' }, { label: '"和我一起入睡"', hint: '当夜晚需要柔软' }, { label: '"调整你的能量"', hint: '当你想更温柔地回到自己' }] },
    soundsAndSleep: { eyebrow: '睡眠与声音', title: 'Miravelys 独特的音频空间，专为脑海中词语太多、身体需要一个更柔软的落点的时刻而设。', body: 'Miravelys 包含为这个世界特别创造的平静声音。它们支持呼吸、冥想、睡眠，以及身体需要柔软空间多过另一个解释的时刻。', cta: '查看 "和我一起入睡"', before: '夜晚让故事更重', after: '明天可以等待', feeling: '“如果我现在停止思考，我会失去对问题的控制。”', shift: '让身体先落地，再让头脑继续。' },
    privacyControl: { eyebrow: '隐私与控制', title: 'Miravelys 不会给你贴标签。它帮助你留意什么可能在重复，而你决定什么合适。', body: '这个 app 不诊断，不决定你是谁，也不宣称绝对真理。它默认本地优先，欢迎修正，并谨慎处理不确定性。', cta: '查看隐私承诺', before: '过度猜测你的 app', after: '可以被修正的陪伴', feeling: '你需要支持，而不是被一个系统定义。', shift: '不是治疗。不是诊断。是一场与自己的私密对话。' },
  },
  trust: { eyebrow: '信任', title: '隐私设计。天生谦逊。', body: 'Miravelys 帮助整理你分享的内容，显示不确定性，并让你修正不合适的内容。', notTherapy: '不是诊断。不是治疗。与自己更清晰的对话。' },
  finale: { eyebrow: '从这里开始', title: '从一个清晰时刻开始。', body: '没有打卡。没有压力。没有表现。只是一个给纠结之物的私密空间。', primary: '下载 Miravelys', secondary: '早期访问' },
};

const de = {
  hero: { deviceLabel: 'Miravelys Produktgeschichte' },
  journey: { progressAria: 'Miravelys Produktgeschichte — der Bildschirm im festen Telefon wechselt beim Scrollen' },
  scenes: {
    overview: { eyebrow: 'Was Miravelys ist', title: 'Ein privater Begleiter für Momente, die innen größer wirken, als sie außen aussahen.', body: 'Miravelys ist für den Moment, der von außen klein aussah, aber innen zur ganzen Geschichte wurde. Es hilft dir aufzuschreiben, was sich wahr anfühlt, die Ebenen zu trennen und zu wählen: ob du Ruhe, Klarheit, Schlaf oder einen kleineren nächsten Schritt brauchst.', cta: 'Produktgeschichte beginnen', before: 'Ein Moment fühlt sich wie alles an', after: 'Ein weicherer Anfang', feeling: '„Etwas ist passiert, und innen ist alles laut geworden.“', shift: 'Beginne mit dem Moment, den du hast, nicht mit perfekten Worten.' },
    writeInside: { eyebrow: 'Aufschreiben', title: 'Schreibe auf, was dich berührt, auslöst, den Körper verkrampft oder immer wieder im Kopf herumging.', body: 'In "Klare Linie" kannst du Emotionen, Überzeugungen, Körperreaktionen, wiederkehrende Gedanken, Ängste oder einen chaotischen Satz schreiben. Miravelys behandelt das als Anfang, nicht als Leistung.', cta: '"Klare Linie" ansehen', before: 'Der Gedanke kreist weiter', after: 'Er hat einen privaten Ort zum Landen', feeling: '„Ich weiß, es könnte übertrieben sein, aber es fühlt sich trotzdem echt an.“', shift: 'Erst ehrlich schreiben. Danach sanft verstehen.' },
    separateLayers: { eyebrow: 'Ebenen trennen', title: 'Trenne Ereignis, Emotion, Körpersignal, Gedankengeschichte, mögliche Überzeugung und Unbekanntes.', body: '"Klare Linie" verlangsamt den Moment. Es trennt das Geschehene von Körperreaktion, Emotion, hinzugefügter Bedeutung, möglichen Überzeugungen und dem, was noch unbekannt ist.', cta: '"Klare Linie" entdecken', before: 'Alles fühlt sich verschmolzen an', after: 'Die Teile bekommen Raum', feeling: 'Eine Pause wird zum Beweis. Eine Angst wird zur Tatsache. Eine Geschichte fühlt sich wie Identität an.', shift: 'Wenn Ebenen getrennt sind, kann der nächste Schritt freundlicher werden.' },
    patternsOverTime: { eyebrow: 'Muster bemerken', title: 'Mit der Zeit können sich wiederholende Notizen alte Schutzmechanismen und wiederholte innere Geschichten zeigen — ohne sie zur Identität zu machen.', body: '"Wöchentlicher Spiegel" sucht Themen nur mit genügend Anhaltspunkten. Es kann helfen, wiederkehrende Überzeugungen oder emotionale Schleifen zu bemerken, während jedes Muster bescheiden, editierbar und von Identität getrennt bleibt.', cta: '"Wöchentlicher Spiegel" ansehen', before: '„Das passiert immer wieder. Vielleicht bin das einfach ich.“', after: 'Information, keine Identität', feeling: 'Eine wiederholte Überzeugung klingt langsam wie ein Urteil.', shift: 'Bemerke, was sich wiederholt, ohne es zu dem zu machen, wer du bist.' },
    calmFirst: { eyebrow: 'Zuerst den Körper beruhigen', title: 'Manchmal ist der erste Schritt nicht Analyse.', body: '"Vier sanfte Türen" bietet Atmung, Körperwahrnehmung, Meditation, Schlafunterstützung und sanfte Energie-Ausrichtung, damit der Körper sich setzen kann, bevor der Geist alles verstehen will.', doorsAriaLabel: 'Vier sanfte Eingänge', cta: 'Eingänge ansehen', before: 'Der Körper ist zu laut für Klarheit', after: 'Ein weicheres Nervensystem', feeling: 'Du brauchst noch keine weiteren Worte. Du brauchst etwas mehr Boden.', shift: 'Atmen, fühlen, langsamer werden, dann noch einmal schauen.', doors: [{ label: '"Atme mit mir"', hint: 'Wenn der Körper zuerst langsamer werden muss' }, { label: '"Meditiere mit mir"', hint: 'Wenn du stille Aufmerksamkeit brauchst' }, { label: '"Schlaf mit mir"', hint: 'Wenn die Nacht Weichheit braucht' }, { label: '"Richten Sie Ihre Energie aus"', hint: 'Wenn du sanfter zu dir zurück möchtest' }] },
    soundsAndSleep: { eyebrow: 'Schlaf und Klänge', title: 'Die einzigartigen Miravelys-Audio-Räume sind für Momente, in denen zu viele Worte im Kopf sind und der Körper einen weicheren Ort zum Landen braucht.', body: 'Miravelys enthält beruhigende Klänge, die für diese Welt geschaffen wurden. Sie unterstützen Atmung, Meditation, Schlaf und Momente, in denen der Körper mehr weichen Raum braucht als eine weitere Erklärung.', cta: '"Schlaf mit mir" ansehen', before: 'Die Nacht macht die Geschichte schwerer', after: 'Morgen kann warten', feeling: '„Wenn ich jetzt aufhöre zu denken, verliere ich die Kontrolle über das Problem.“', shift: 'Lass den Körper landen, bevor der Geist weitermacht.' },
    privacyControl: { eyebrow: 'Privatsphäre und Kontrolle', title: 'Miravelys kennzeichnet dich nicht. Es hilft dir zu bemerken, was sich vielleicht wiederholt, während du entscheidest, was passt.', body: 'Die App diagnostiziert nicht, entscheidet nicht, wer du bist, und behauptet keine absolute Wahrheit. Sie ist lokal zuerst, korrekturfreundlich und vorsichtig mit Unsicherheit.', cta: 'Datenschutzversprechen ansehen', before: 'Apps, die zu viel raten', after: 'Ein korrigierbarer Begleiter', feeling: 'Du willst Unterstützung, kein System, das dich definiert.', shift: 'Keine Therapie. Keine Diagnose. Ein privates Gespräch mit dir selbst.' },
  },
  trust: { eyebrow: 'Vertrauen', title: 'Privat gestaltet. Von Natur aus bescheiden.', body: 'Miravelys hilft, das zu ordnen, was du teilst, zeigt Unsicherheit und lässt dich korrigieren, was nicht passt.', notTherapy: 'Keine Diagnose. Keine Therapie. Ein klareres Gespräch mit dir selbst.' },
  finale: { eyebrow: 'Hier beginnen', title: 'Beginne mit einem klaren Moment.', body: 'Keine Serien. Kein Druck. Keine Leistung. Nur ein privater Ort für das, was sich verworren anfühlt.', primary: 'Miravelys laden', secondary: 'Früher Zugang' },
};

const es = {
  hero: { deviceLabel: 'Historia del producto Miravelys' },
  journey: { progressAria: 'Historia del producto Miravelys — la pantalla del teléfono cambia al desplazarse' },
  scenes: {
    overview: { eyebrow: 'Qué es Miravelys', title: 'Un compañero privado para momentos que se sienten más grandes por dentro de lo que parecían por fuera.', body: 'Miravelys es para el momento que por fuera parecía pequeño, pero por dentro se convirtió en toda una historia. Te ayuda a escribir lo que se siente verdadero, separar las capas y elegir si necesitas calma, claridad, sueño o un siguiente paso más pequeño.', cta: 'Comenzar la historia del producto', before: 'Un momento se siente como todo', after: 'Un comienzo más suave', feeling: '“Algo pasó, y ahora mi mundo interior está demasiado ruidoso.”', shift: 'Empieza con el momento que tienes, no con palabras perfectas.' },
    writeInside: { eyebrow: 'Escríbelo', title: 'Escribe lo que te tocó, lo que desencadenó, lo que te tensó el cuerpo o no dejaba de volver a tu mente.', body: 'En "Línea clara" puedes escribir emociones, creencias, reacciones del cuerpo, pensamientos repetidos, miedos o una frase desordenada. Miravelys lo trata como un comienzo, no como una actuación.', cta: 'Ver "Línea clara"', before: 'El pensamiento sigue girando', after: 'Tiene un lugar privado donde aterrizar', feeling: '“Sé que quizá es exagerado, pero todavía se siente real.”', shift: 'Escribe con honestidad primero. Comprende con suavidad después.' },
    separateLayers: { eyebrow: 'Separa las capas', title: 'Separa el evento, la emoción, la señal del cuerpo, la historia de la mente, la creencia posible y lo desconocido.', body: '"Línea clara" ayuda a ralentizar el momento. Separa lo que ocurrió de la reacción del cuerpo, la emoción, el significado añadido por la mente, posibles creencias y lo que sigue desconocido.', cta: 'Explorar "Línea clara"', before: 'Todo se siente unido', after: 'Las partes tienen espacio', feeling: 'Una pausa se vuelve prueba. Un miedo se vuelve hecho. Una historia empieza a sentirse como identidad.', shift: 'Cuando las capas se separan, el siguiente paso puede ser más amable.' },
    patternsOverTime: { eyebrow: 'Nota patrones', title: 'Con el tiempo, las notas repetidas pueden revelar viejas protecciones e historias interiores repetidas, sin convertirlas en identidad.', body: '"Espejo semanal" busca temas solo cuando hay suficiente evidencia. Puede ayudarte a notar creencias repetidas o bucles emocionales, manteniendo cada patrón humilde, editable y separado de la identidad.', cta: 'Ver "Espejo semanal"', before: '“Esto sigue pasando. Tal vez soy así.”', after: 'Información, no identidad', feeling: 'Una creencia repetida empieza a sonar como una sentencia.', shift: 'Nota lo que se repite sin convertirlo en quien eres.' },
    calmFirst: { eyebrow: 'Primero calma el cuerpo', title: 'A veces el primer paso no es analizar.', body: '"Cuatro puertas suaves" ofrece respiración, conciencia de sensaciones, meditación, apoyo para el sueño y alineación suave de energía para que el cuerpo pueda asentarse antes de que la mente intente entenderlo todo.', doorsAriaLabel: 'Cuatro puertas suaves', cta: 'Ver las puertas', before: 'El cuerpo está demasiado ruidoso para la claridad', after: 'Un sistema nervioso más suave', feeling: 'Todavía no necesitas más palabras. Necesitas un poco más de suelo.', shift: 'Respira, siente, baja el ritmo y mira otra vez.', doors: [{ label: '"Respira conmigo"', hint: 'Cuando el cuerpo necesita ir más despacio primero' }, { label: '"Medita conmigo"', hint: 'Cuando necesitas atención tranquila' }, { label: '"Duerme conmigo"', hint: 'Cuando la noche necesita suavidad' }, { label: '"Alinea tu energía"', hint: 'Cuando quieres volver a ti con más suavidad' }] },
    soundsAndSleep: { eyebrow: 'Sueño y sonidos', title: 'Los espacios de audio únicos de Miravelys son para momentos en los que hay demasiadas palabras en la cabeza y el cuerpo necesita un lugar más suave donde aterrizar.', body: 'Miravelys incluye sonidos calmantes creados para su mundo. Apoyan la respiración, la meditación, el sueño y los momentos en los que el cuerpo necesita un espacio más suave que otra explicación.', cta: 'Ver "Duerme conmigo"', before: 'La noche vuelve la historia más pesada', after: 'Mañana puede esperar', feeling: '“Si dejo de pensar ahora, perderé el control del problema.”', shift: 'Deja que el cuerpo aterrice antes de que la mente continúe.' },
    privacyControl: { eyebrow: 'Privacidad y control', title: 'Miravelys no te etiqueta. Te ayuda a notar qué puede estar repitiéndose, mientras tú decides qué encaja.', body: 'La app no diagnostica, no decide quién eres ni afirma una verdad absoluta. Es local-first por diseño, abierta a correcciones y cuidadosa con la incertidumbre.', cta: 'Ver la promesa de privacidad', before: 'Apps que adivinan demasiado', after: 'Un compañero corregible', feeling: 'Quieres apoyo, no un sistema que te defina.', shift: 'No es terapia. No es diagnóstico. Una conversación privada contigo.' },
  },
  trust: { eyebrow: 'Confianza', title: 'Privada por diseño. Humilde por naturaleza.', body: 'Miravelys ayuda a organizar lo que compartes, muestra incertidumbre y te permite corregir lo que no encaja.', notTherapy: 'No diagnóstico. No terapia. Una conversación más clara contigo.' },
  finale: { eyebrow: 'Empieza aquí', title: 'Empieza con un momento claro.', body: 'Sin rachas. Sin presión. Sin actuación. Solo un lugar privado para lo que se siente enredado.', primary: 'Descargar Miravelys', secondary: 'Acceso anticipado' },
};

const pt = {
  hero: { deviceLabel: 'História do produto Miravelys' },
  journey: { progressAria: 'História do produto Miravelys — a tela dentro do telefone muda ao rolar' },
  scenes: {
    overview: { eyebrow: 'O que é o Miravelys', title: 'Um companion privado para momentos que parecem maiores por dentro do que pareciam por fora.', body: 'Miravelys é para o momento que por fora parecia pequeno, mas por dentro virou uma história inteira. Ele ajuda-te a escrever o que parece verdadeiro, separar as camadas e escolher se precisas de calma, clareza, sono ou um próximo passo mais pequeno.', cta: 'Começar a história do produto', before: 'Um momento parece virar tudo', after: 'Um começo mais suave', feeling: '“Algo aconteceu, e agora meu mundo interior está barulhento.”', shift: 'Começa com o momento que tens, não com palavras perfeitas.' },
    writeInside: { eyebrow: 'Escreve', title: 'Escreve o que te tocou, desencadeou, apertou o corpo ou ficou a repetir-se na mente.', body: 'No "Linha clara", podes escrever emoções, crenças, reações do corpo, pensamentos repetidos, medos ou uma frase bagunçada. Miravelys trata isso como começo, não como performance.', cta: 'Ver "Linha clara"', before: 'O pensamento continua circulando', after: 'Ele tem um lugar privado para pousar', feeling: '“Eu sei que talvez seja exagerado, mas ainda parece real.”', shift: 'Escreve com honestidade primeiro. Entende com suavidade depois.' },
    separateLayers: { eyebrow: 'Separar camadas', title: 'Separa o evento, a emoção, o sinal do corpo, a história da mente, a crença possível e o desconhecido.', body: '"Linha clara" ajuda a desacelerar o momento. Ele separa o que aconteceu da reação do corpo, da emoção, do significado acrescentado pela mente, de possíveis crenças e do que ainda é desconhecido.', cta: 'Explorar "Linha clara"', before: 'Tudo parece misturado', after: 'As partes ganham espaço', feeling: 'Uma pausa vira prova. Um medo vira fato. Uma história começa a parecer identidade.', shift: 'Quando as camadas se separam, o próximo passo pode ficar mais gentil.' },
    patternsOverTime: { eyebrow: 'Perceber padrões', title: 'Ao longo do tempo, notas repetidas podem revelar velhas proteções e histórias interiores repetidas — sem as transformar em identidade.', body: '"Espelho semanal" procura temas apenas quando há evidência suficiente. Ele pode ajudar-te a notar crenças repetidas ou ciclos emocionais, mantendo cada padrão humilde, editável e separado da identidade.', cta: 'Ver "Espelho semanal"', before: '“Isso continua acontecendo. Talvez eu seja assim.”', after: 'Informação, não identidade', feeling: 'Uma crença repetida começa a soar como sentença.', shift: 'Percebe o que se repete sem transformar isso em quem és.' },
    calmFirst: { eyebrow: 'Acalmar o corpo primeiro', title: 'Às vezes o primeiro passo não é analisar.', body: '"Quatro portas suaves" oferece respiração, consciência das sensações, meditação, apoio ao sono e alinhamento suave de energia para que o corpo possa se assentar antes que a mente tente entender tudo.', doorsAriaLabel: 'Quatro portas suaves', cta: 'Ver as portas', before: 'O corpo está barulhento demais para clareza', after: 'Um sistema nervoso mais suave', feeling: 'Ainda não precisas de mais palavras. Precisas de um pouco mais de chão.', shift: 'Respira, sente, desacelera e olha de novo.', doors: [{ label: '"Respire comigo"', hint: 'Quando o corpo precisa desacelerar primeiro' }, { label: '"Medite comigo"', hint: 'Quando precisas de atenção quieta' }, { label: '"Durma comigo"', hint: 'Quando a noite precisa de suavidade' }, { label: '"Alinhe sua energia"', hint: 'Quando queres voltar a ti com mais gentileza' }] },
    soundsAndSleep: { eyebrow: 'Sono e sons', title: 'Os espaços de áudio únicos do Miravelys são para os momentos em que as palavras na cabeça são demasiadas e o corpo precisa de um lugar mais suave onde pousar.', body: 'Miravelys inclui sons calmantes criados para o seu mundo. Eles apoiam respiração, meditação, sono e momentos em que o corpo precisa de um espaço mais suave do que outra explicação.', cta: 'Ver "Durma comigo"', before: 'A noite deixa a história mais pesada', after: 'Amanhã pode esperar', feeling: '“Se eu parar de pensar agora, vou perder o controle do problema.”', shift: 'Deixa o corpo pousar antes que a mente continue.' },
    privacyControl: { eyebrow: 'Privacidade e controle', title: 'O Miravelys não te etiqueta. Ajuda-te a notar o que pode estar a repetir-se, enquanto tu decides o que combina.', body: 'O app não diagnostica, não decide quem és e não afirma verdade absoluta. Ele é local-first por design, aceita correções e trata a incerteza com cuidado.', cta: 'Ver promessa de privacidade', before: 'Apps que adivinham demais', after: 'Um companheiro corrigível', feeling: 'Queres apoio, não um sistema que te define.', shift: 'Não é terapia. Não é diagnóstico. Uma conversa privada contigo.' },
  },
  trust: { eyebrow: 'Confiança', title: 'Privado por design. Humilde por natureza.', body: 'Miravelys ajuda a organizar o que partilhas, mostra incerteza e permite corrigir o que não combina.', notTherapy: 'Não é diagnóstico. Não é terapia. Uma conversa mais clara contigo.' },
  finale: { eyebrow: 'Comece aqui', title: 'Comece com um momento claro.', body: 'Sem sequências. Sem pressão. Sem performance. Apenas um lugar privado para o que parece emaranhado.', primary: 'Baixar Miravelys', secondary: 'Acesso antecipado' },
};

const ja = {
  hero: { deviceLabel: 'Miravelys のプロダクトストーリー' },
  journey: { progressAria: 'Miravelys のプロダクトストーリー — スクロールすると固定された電話の中の画面が変わります' },
  scenes: {
    overview: { eyebrow: 'Miravelys とは', title: '外側より内側で大きく感じる瞬間のための、プライベートな companion。', body: 'ある瞬間が、外からは小さく見えたのに、内側では一つの大きな物語になった。そんなときのための Miravelys です。今ほんとうに感じていることを書き、層を分け、必要なのが落ち着きか、明晰さか、睡眠か、それとも小さな次の一歩かを選びます。', cta: 'プロダクトストーリーを始める', before: '一つの瞬間がすべてのように感じる', after: 'やわらかく始められる場所', feeling: '「何かが起きて、内側がとても騒がしくなった。」', shift: '完璧な言葉ではなく、今ある瞬間から始める。' },
    writeInside: { eyebrow: '書き留める', title: '心を刺したもの、トリガーになったもの、身体を締め付けたもの、何度も頭に戻ってきたことを書き留める。', body: '"明確なライン" では、感情、信念、身体の反応、繰り返す思考、恐れ、またはまとまらない一文を書くことができます。Miravelys はそれを成果ではなく、始まりとして受け止めます。', cta: '"明確なライン" を見る', before: '思考が回り続ける', after: 'それが降り立つ私的な場所がある', feeling: '「大げさかもしれない。でも今はまだ本当に感じる。」', shift: 'まず正直に書く。あとでやさしく理解する。' },
    separateLayers: { eyebrow: '層を分ける', title: '出来事・感情・身体の信号・心の物語・ありうる信念・未知を分けて見る。', body: '"明確なライン" はその瞬間をゆっくりにします。起きたこと、身体の反応、感情、心が加えた意味、可能性のある信念、そしてまだわからないことを分けて見せます。', cta: '"明確なライン" を見る', before: 'すべてが一つに溶けている', after: 'それぞれに空間が生まれる', feeling: '沈黙が証拠になる。恐れが事実になる。物語が自己像のように感じられる。', shift: '層が分かれると、次の一歩はもっとやさしくなる。' },
    patternsOverTime: { eyebrow: 'パターンに気づく', title: '時間をかけて、繰り返された記録は古い防衛や繰り返される内面の物語を示すことがある——それを自己像に変えずに。', body: '"ウィークリーミラー" は十分な根拠があるときだけテーマを探します。繰り返す信念や感情のループに気づく手助けをしながら、すべてのパターンを謙虚で編集可能なものとして、アイデンティティから切り離します。', cta: '"ウィークリーミラー" を見る', before: '「またこれが起きた。たぶん私はこういう人なんだ。」', after: 'アイデンティティではなく情報', feeling: '繰り返す信念が、判決のように聞こえ始める。', shift: '繰り返すものに気づく。でも、それを自分そのものにしない。' },
    calmFirst: { eyebrow: 'まず身体を落ち着ける', title: '最初の一歩が分析ではないこともあります。', body: '"4つの優しい入り口" は、呼吸、感覚への気づき、瞑想、睡眠サポート、やさしいエネルギーの整えを通して、心がすべてを理解しようとする前に身体が落ち着く手助けをします。', doorsAriaLabel: '四つのやさしい入口', cta: '入口を見る', before: '身体が騒がしすぎて明晰さに届かない', after: 'よりやわらかな神経系', feeling: '今はまだ言葉はいらない。もう少し地面が必要。', shift: '呼吸して、感じて、ゆっくりして、もう一度見る。', doors: [{ label: '"一緒に呼吸"', hint: '身体がまずゆっくりになる必要があるとき' }, { label: '"一緒に瞑想しましょう"', hint: '静かな注意が必要なとき' }, { label: '"一緒に眠る"', hint: '夜にやさしさが必要なとき' }, { label: '"エネルギーを整える"', hint: 'もっとやさしく自分に戻りたいとき' }] },
    soundsAndSleep: { eyebrow: '睡眠と音', title: 'Miravelys の独自のオーディオ空間は、頭の中に言葉が多すぎて、身体がよりやわらかい着地場所を必要とする瞬間のためのもの。', body: 'Miravelys には、この世界のために作られた落ち着きの音があります。呼吸、瞑想、睡眠、そして身体が別の説明よりもやわらかな空間を必要とする瞬間を支えます。', cta: '"一緒に眠る" を見る', before: '夜は物語を重くする', after: '明日は待てる', feeling: '「今考えるのをやめたら、問題をコントロールできなくなる。」', shift: '心が続ける前に、身体を着地させる。' },
    privacyControl: { eyebrow: 'プライバシーとコントロール', title: 'Miravelys はあなたにラベルを貼りません。何が繰り返されているかに気づく手助けをし、何が合うかを決めるのはあなたです。', body: 'このアプリは診断せず、あなたが誰かを決めず、絶対的な真実を主張しません。ローカルファーストで、修正しやすく、不確実性を大切に扱います。', cta: 'プライバシーの約束を見る', before: '推測しすぎるアプリ', after: '修正できる伴走者', feeling: '必要なのは支えであり、自分を定義するシステムではありません。', shift: 'セラピーではない。診断ではない。自分との私的な対話。' },
  },
  trust: { eyebrow: '信頼', title: 'プライベート設計。謙虚な性質。', body: 'Miravelys は共有したことを整理し、不確実性を示し、合わないものを修正できるようにします。', notTherapy: '診断ではない。セラピーではない。自分とのより明確な対話。' },
  finale: { eyebrow: 'ここから', title: '一つの明確な瞬間から始める。', body: '連続記録なし。プレッシャーなし。成果なし。ただ、絡まったもののための私的な場所。', primary: 'Miravelys をダウンロード', secondary: '早期アクセス' },
};

const presentationCopy = { en, ru, ro, fr, hi, zh, de, es, pt, ja };

export function resolvePresentation(lang) {
  return presentationCopy[lang] || presentationCopy.en;
}

export { presentationCopy };
export default presentationCopy;
