// Generated by Miravelys product-accurate website audit pass.

export const en = {
  "hero": {
    "deviceLabel": "Miravelys interactive guide"
  },
  "journey": {
    "progressAria": "Miravelys product tour — phone screen changes as you scroll"
  },
  "scenes": {
    "overview": {
      "eyebrow": "What Miravelys is",
      "title": "A safe place to untangle your hardest moments.",
      "body": "Sometimes a small event can trigger a massive spiral of anxiety. Miravelys helps you write down what you're feeling, separate facts from fears, and figure out your next step.",
      "cta": "Begin the tour",
      "before": "The problem feels huge",
      "after": "A safe place to start",
      "feeling": "“Something triggered me, and now my mind won't stop racing.”",
      "shift": "Start with whatever you're feeling right now."
    },
    "writeInside": {
      "eyebrow": "Write it down",
      "title": "Write down exactly what's bothering you.",
      "body": "Using the \"Get Clear\" feature, you can write down your raw emotions, physical reactions, or fears. You don't need to be perfectly logical—just get it out of your head.",
      "cta": "See Get Clear",
      "before": "The thought is stuck on repeat",
      "after": "It's finally out of your head",
      "feeling": "“I know I might be overreacting, but it feels so real right now.”",
      "shift": "Get it out of your head first. Make sense of it later."
    },
    "separateLayers": {
      "eyebrow": "Separate the layers",
      "title": "Separate the facts from your anxiety.",
      "body": "When you're overwhelmed, everything feels like one big disaster. The app helps you separate what actually happened from the anxious stories your mind is inventing.",
      "cta": "Explore Truth Line",
      "before": "Everything is tangled together",
      "after": "The facts are clear",
      "feeling": "Your fears start to feel like facts. A single mistake feels like it defines your whole identity.",
      "shift": "Once you break the moment down, it becomes much easier to handle."
    },
    "patternsOverTime": {
      "eyebrow": "Notice patterns",
      "title": "Notice your emotional patterns over time.",
      "body": "The \"Weekly Mirror\" feature gently points out recurring themes in your journal entries. It helps you recognize emotional triggers and unhelpful beliefs without judging you.",
      "cta": "See Weekly Mirror",
      "before": "“Why does this keep happening?”",
      "after": "Helpful insights",
      "feeling": "“Is there something wrong with me?”",
      "shift": "See your patterns as helpful information, not as a permanent flaw."
    },
    "calmFirst": {
      "eyebrow": "Calm the body first",
      "title": "Calm your nervous system first.",
      "body": "When you are highly anxious, trying to analyze your thoughts makes it worse. We offer guided breathing, meditation, and sleep support so your body can calm down first.",
      "doorsAriaLabel": "Four soothing options",
      "cta": "See the doorways",
      "before": "Your heart is racing",
      "after": "A calmer nervous system",
      "feeling": "You don't need to solve the problem right now. You just need to breathe.",
      "shift": "Calm your body down, then look at the problem again.",
      "doors": [
        {
          "label": "Breathe With Me",
          "hint": "When you need to slow your heart rate"
        },
        {
          "label": "Meditate With Me",
          "hint": "When you need to quiet your mind"
        },
        {
          "label": "Sleep With Me",
          "hint": "When you just need to rest"
        },
        {
          "label": "Align Your Energy",
          "hint": "When you need to feel grounded"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Sleep and sounds",
      "title": "Relaxing sounds for sleepless nights.",
      "body": "When your mind won't shut off at night, the app sets the heavy questions aside. We offer calming soundscapes designed to help you let go of your thoughts and fall asleep.",
      "cta": "See Sleep With Me",
      "before": "Lying awake overthinking",
      "after": "Ready to rest",
      "feeling": "“If I stop worrying about this problem, I'll lose control.”",
      "shift": "Let your body rest tonight. The problem can wait until tomorrow."
    },
    "privacyControl": {
      "eyebrow": "Privacy and control",
      "title": "You are always in control of your data.",
      "body": "The app will never try to diagnose you or put a label on you. All your entries are stored securely on your device, and you can edit or delete anything at any time.",
      "cta": "See the privacy promise",
      "before": "Apps that collect your data",
      "after": "100% private and secure",
      "feeling": "You want a helpful tool, not an algorithm that judges you.",
      "shift": "This isn't therapy or a diagnosis. It's a completely private space for you."
    }
  },
  "trust": {
    "eyebrow": "Trust",
    "title": "Completely private. Completely yours.",
    "body": "Miravelys never uploads your private journal entries without your permission. You can delete anything permanently.",
    "notTherapy": "Not therapy. Not a diagnosis. Just a tool for your mind."
  },
  "finale": {
    "eyebrow": "Start here",
    "title": "Take the first step.",
    "body": "No pressure. No tracking streaks. Just a private place to untangle your thoughts when you need it.",
    "primary": "Download Miravelys",
    "secondary": "Early access"
  }
};
export const ru = {
  "hero": {
    "deviceLabel": "Интерактивное руководство Miravelys"
  },
  "journey": {
    "progressAria": "Тур по продукту Miravelys — экран телефона меняется при прокрутке"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Что такое Miravelys",
      "title": "Безопасное место, чтобы распутать самые тяжелые моменты.",
      "body": "Иногда маленькое событие может запустить огромную спираль тревоги. Miravelys помогает вам записать то, что вы чувствуете, отделить факты от страхов и понять, что делать дальше.",
      "cta": "Начать тур",
      "before": "Проблема кажется огромной",
      "after": "Безопасное место для старта",
      "feeling": "«Что-то выбило меня из колеи, и теперь мысли не остановить.»",
      "shift": "Начните с того, что вы чувствуете прямо сейчас."
    },
    "writeInside": {
      "eyebrow": "Записать",
      "title": "Запишите именно то, что вас беспокоит.",
      "body": "Используя \"Внести ясность\", вы можете записать свои эмоции, телесные реакции или страхи. Вам не нужно быть идеально логичным — просто выбросьте это из головы.",
      "cta": "Смотреть \"Внести ясность\"",
      "before": "Мысль застряла на повторе",
      "after": "Она наконец-то вышла из головы",
      "feeling": "«Я знаю, что могу преувеличивать, но сейчас это кажется таким реальным.»",
      "shift": "Сначала выплесните это. Разберетесь позже."
    },
    "separateLayers": {
      "eyebrow": "Разделить слои",
      "title": "Отделите факты от вашей тревоги.",
      "body": "Когда вас накрывает с головой, всё кажется одной большой катастрофой. Приложение помогает отделить то, что на самом деле произошло, от тревожных историй, которые придумывает ваш ум.",
      "cta": "Открыть Линию ясности",
      "before": "Всё спуталось в один клубок",
      "after": "Факты ясны",
      "feeling": "Ваши страхи начинают казаться фактами. Одна ошибка ощущается так, будто она определяет всю вашу личность.",
      "shift": "Как только вы разложите момент на части, с ним станет гораздо легче справиться."
    },
    "patternsOverTime": {
      "eyebrow": "Замечать паттерны",
      "title": "Замечайте свои эмоциональные паттерны со временем.",
      "body": "\"Зеркало\" бережно подсвечивает повторяющиеся темы в ваших записях. Оно помогает распознать эмоциональные триггеры и мешающие убеждения без какого-либо осуждения.",
      "cta": "Смотреть Зеркало",
      "before": "«Почему это происходит снова и снова?»",
      "after": "Полезные наблюдения",
      "feeling": "«Со мной что-то не так?»",
      "shift": "Воспринимайте свои паттерны как полезную информацию, а не как ваш вечный недостаток."
    },
    "calmFirst": {
      "eyebrow": "Сначала тело",
      "title": "Сначала успокойте нервную систему.",
      "body": "Когда вы сильно тревожитесь, попытки анализировать свои мысли делают только хуже. Мы предлагаем дыхательные практики, медитацию и поддержку сна, чтобы ваше тело могло успокоиться до того, как вы начнете действовать.",
      "doorsAriaLabel": "Четыре успокаивающих варианта",
      "cta": "Смотреть варианты",
      "before": "Сердце бешено бьется",
      "after": "Спокойная нервная система",
      "feeling": "Вам не нужно решать проблему прямо сейчас. Вам просто нужно подышать.",
      "shift": "Успокойте тело, а затем взгляните на проблему снова.",
      "doors": [
        {
          "label": "Дыши со мной",
          "hint": "Когда нужно замедлить сердцебиение"
        },
        {
          "label": "Медитируй со мной",
          "hint": "Когда нужно успокоить ум"
        },
        {
          "label": "Засыпай со мной",
          "hint": "Когда нужно просто отдохнуть"
        },
        {
          "label": "Выровняйте свою энергию",
          "hint": "Когда нужно почувствовать опору"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Сон и звуки",
      "title": "Расслабляющие звуки для бессонных ночей.",
      "body": "Когда ночью ваш мозг отказывается отключаться, приложение откладывает тяжелые вопросы в сторону. Мы предлагаем успокаивающие звуки, созданные, чтобы помочь вам отпустить мысли и уснуть.",
      "cta": "Смотреть Засыпай со мной",
      "before": "Лежите без сна из-за навязчивых мыслей",
      "after": "Готовы к отдыху",
      "feeling": "«Если я перестану беспокоиться об этой проблеме, я потеряю контроль.»",
      "shift": "Позвольте телу отдохнуть сегодня. Проблема может подождать до завтра."
    },
    "privacyControl": {
      "eyebrow": "Приватность и контроль",
      "title": "Вы всегда контролируете свои данные.",
      "body": "Приложение никогда не будет ставить вам диагнозы или вешать на вас ярлыки. Все ваши записи надежно хранятся на вашем устройстве, и вы можете изменить или удалить что угодно в любой момент.",
      "cta": "Смотреть обещание приватности",
      "before": "Приложения, которые собирают данные",
      "after": "100% приватно и безопасно",
      "feeling": "Вы хотите полезный инструмент, а не алгоритм, который вас осуждает.",
      "shift": "Это не терапия и не диагноз. Это полностью личное пространство только для вас."
    }
  },
  "trust": {
    "eyebrow": "Доверие",
    "title": "Полностью приватно. Полностью ваше.",
    "body": "Miravelys никогда не загружает ваши записи без вашего разрешения. Вы можете удалить всё навсегда.",
    "notTherapy": "Не терапия. Не диагноз. Просто инструмент для вашего ума."
  },
  "finale": {
    "eyebrow": "Начни здесь",
    "title": "Сделайте первый шаг.",
    "body": "Никакого давления. Никаких трекеров привычек. Просто безопасное место, чтобы распутать мысли, когда вам это нужно.",
    "primary": "Скачать Miravelys",
    "secondary": "Ранний доступ"
  }
};
export const ro = {
  "hero": {
    "deviceLabel": "Ghid interactiv Miravelys"
  },
  "journey": {
    "progressAria": "Turul produsului Miravelys — ecranul se schimbă pe măsură ce derulați"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Ce este Miravelys",
      "title": "Un loc sigur pentru a-ți descurca cele mai grele momente.",
      "body": "Uneori, un eveniment mic poate declanșa o spirală masivă de anxietate. Miravelys te ajută să scrii ceea ce simți, să separi faptele de temeri și să-ți dai seama care este următorul pas.",
      "cta": "Începe turul",
      "before": "Problema pare uriașă",
      "after": "Un loc sigur de unde să începi",
      "feeling": "„Ceva m-a declanșat, iar acum mintea mea nu se mai oprește.”",
      "shift": "Începe cu orice simți chiar acum."
    },
    "writeInside": {
      "eyebrow": "Scrie",
      "title": "Scrie exact ce te deranjează.",
      "body": "Folosind funcția „Linie clară”, poți scrie emoțiile brute, reacțiile fizice sau temerile. Nu trebuie să fii perfect logic — doar scoate-le din minte.",
      "cta": "Vezi Linie clară",
      "before": "Gândul a rămas blocat pe repeat",
      "after": "În sfârșit a ieșit din mintea ta",
      "feeling": "„Știu că poate exagerez, dar se simte atât de real acum.”",
      "shift": "Scoate-l din minte mai întâi. Înțelege-l mai târziu."
    },
    "separateLayers": {
      "eyebrow": "Separă straturile",
      "title": "Separă faptele de anxietatea ta.",
      "body": "Când ești copleșit, totul pare un mare dezastru. Aplicația te ajută să separi ce s-a întâmplat de fapt, de poveștile anxioase pe care mintea ta le inventează.",
      "cta": "Explorează Linia clară",
      "before": "Totul este încurcat",
      "after": "Faptele sunt clare",
      "feeling": "Fricile tale încep să pară fapte. O singură greșeală pare că îți definește întreaga identitate.",
      "shift": "Odată ce descompui momentul, devine mult mai ușor de gestionat."
    },
    "patternsOverTime": {
      "eyebrow": "Observă tipare",
      "title": "Observă-ți tiparele emoționale în timp.",
      "body": "Funcția „Oglindă” îți arată blând temele recurente din intrările tale de jurnal. Te ajută să recunoști declanșatorii emoționali și convingerile nefolositoare, fără a te judeca.",
      "cta": "Vezi Oglinda",
      "before": "„De ce se tot întâmplă asta?”",
      "after": "Informații utile",
      "feeling": "„E ceva în neregulă cu mine?”",
      "shift": "Privește tiparele tale ca pe niște informații utile, nu ca pe un defect permanent."
    },
    "calmFirst": {
      "eyebrow": "Mai întâi corpul",
      "title": "Mai întâi calmează-ți sistemul nervos.",
      "body": "Când ești foarte anxios, încercarea de a-ți analiza gândurile înrăutățește lucrurile. Oferim respirație ghidată, meditație și sprijin pentru somn, astfel încât corpul tău să se poată calma mai întâi.",
      "doorsAriaLabel": "Patru opțiuni de calmare",
      "cta": "Vezi opțiunile",
      "before": "Inima îți bate cu putere",
      "after": "Un sistem nervos mai calm",
      "feeling": "Nu trebuie să rezolvi problema chiar acum. Ai nevoie doar să respiri.",
      "shift": "Calmează-ți corpul, apoi privește problema din nou.",
      "doors": [
        {
          "label": "Respiră cu mine",
          "hint": "Când trebuie să-ți încetinești ritmul cardiac"
        },
        {
          "label": "Meditează cu mine",
          "hint": "Când trebuie să-ți liniștești mintea"
        },
        {
          "label": "Dormi cu mine",
          "hint": "Când ai nevoie doar să te odihnești"
        },
        {
          "label": "Aliniază-ți energia",
          "hint": "Când trebuie să te simți ancorat"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Somn și sunete",
      "title": "Sunete relaxante pentru nopți nedormite.",
      "body": "Când mintea ta nu se oprește noaptea, aplicația lasă întrebările grele deoparte. Oferim peisaje sonore calmante concepute pentru a te ajuta să renunți la gânduri și să adormi.",
      "cta": "Vezi Dormi cu mine",
      "before": "Stai treaz gândind prea mult",
      "after": "Gata de odihnă",
      "feeling": "„Dacă nu mă mai îngrijorez de problema asta, voi pierde controlul.”",
      "shift": "Lasă-ți corpul să se odihnească la noapte. Problema poate aștepta până mâine."
    },
    "privacyControl": {
      "eyebrow": "Confidențialitate și control",
      "title": "Tu deții mereu controlul asupra datelor tale.",
      "body": "Aplicația nu va încerca niciodată să te diagnosticheze sau să-ți pună o etichetă. Toate intrările tale sunt stocate în siguranță pe dispozitivul tău și poți edita sau șterge orice, oricând.",
      "cta": "Vezi promisiunea de confidențialitate",
      "before": "Aplicații care colectează date",
      "after": "100% privat și sigur",
      "feeling": "Vrei un instrument util, nu un algoritm care să te judece.",
      "shift": "Asta nu este terapie sau un diagnostic. Este un spațiu complet privat pentru tine."
    }
  },
  "trust": {
    "eyebrow": "Încredere",
    "title": "Complet privat. Complet al tău.",
    "body": "Miravelys nu încarcă niciodată intrările tale private din jurnal fără permisiunea ta. Poți șterge orice permanent.",
    "notTherapy": "Nu este terapie. Nu este un diagnostic. Doar un instrument pentru mintea ta."
  },
  "finale": {
    "eyebrow": "Începe aici",
    "title": "Fă primul pas.",
    "body": "Fără presiune. Fără serii de monitorizat. Doar un loc privat pentru a-ți descurca gândurile atunci când ai nevoie.",
    "primary": "Descarcă Miravelys",
    "secondary": "Acces timpuriu"
  }
};
export const fr = {
  "hero": {
    "deviceLabel": "Guide interactif Miravelys"
  },
  "journey": {
    "progressAria": "Visite guidée Miravelys — l'écran change au fur et à mesure du défilement"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Ce qu'est Miravelys",
      "title": "Un endroit sûr pour démêler vos moments les plus difficiles.",
      "body": "Parfois, un petit événement peut déclencher une énorme spirale d'anxiété. Miravelys vous aide à écrire ce que vous ressentez, à séparer les faits des peurs et à déterminer votre prochaine étape.",
      "cta": "Commencer la visite",
      "before": "Le problème semble énorme",
      "after": "Un endroit sûr pour commencer",
      "feeling": "« Quelque chose m'a déclenché, et maintenant mon esprit s'emballe. »",
      "shift": "Commencez par ce que vous ressentez en ce moment."
    },
    "writeInside": {
      "eyebrow": "Écrire",
      "title": "Écrivez exactement ce qui vous dérange.",
      "body": "Grâce à la fonctionnalité « Ligne claire », vous pouvez noter vos émotions brutes, vos réactions physiques ou vos peurs. Vous n'avez pas besoin d'être parfaitement logique — sortez-les simplement de votre tête.",
      "cta": "Voir Ligne claire",
      "before": "La pensée tourne en boucle",
      "after": "C'est enfin sorti de votre tête",
      "feeling": "« Je sais que je réagis peut-être de manière excessive, mais cela semble tellement réel en ce moment. »",
      "shift": "Sortez-le d'abord de votre tête. Comprenez-le plus tard."
    },
    "separateLayers": {
      "eyebrow": "Séparer les couches",
      "title": "Séparez les faits de votre anxiété.",
      "body": "Lorsque vous êtes dépassé, tout ressemble à un grand désastre. L'application vous aide à séparer ce qui s'est réellement passé des histoires anxieuses que votre esprit invente.",
      "cta": "Explorer Ligne claire",
      "before": "Tout est emmêlé",
      "after": "Les faits sont clairs",
      "feeling": "Vos peurs commencent à ressembler à des faits. Une seule erreur semble définir toute votre identité.",
      "shift": "Une fois que vous avez décomposé le moment, il devient beaucoup plus facile à gérer."
    },
    "patternsOverTime": {
      "eyebrow": "Remarquer les schémas",
      "title": "Remarquez vos schémas émotionnels au fil du temps.",
      "body": "La fonction « Miroir » souligne doucement les thèmes récurrents dans vos entrées de journal. Elle vous aide à reconnaître les déclencheurs émotionnels et les croyances inutiles sans vous juger.",
      "cta": "Voir Miroir",
      "before": "« Pourquoi cela continue-t-il à se produire ? »",
      "after": "Des informations utiles",
      "feeling": "« Y a-t-il quelque chose qui ne va pas chez moi ? »",
      "shift": "Considérez vos schémas comme des informations utiles, et non comme un défaut permanent."
    },
    "calmFirst": {
      "eyebrow": "Calmer le corps d'abord",
      "title": "Calmez d'abord votre système nerveux.",
      "body": "Lorsque vous êtes très anxieux, essayer d'analyser vos pensées ne fait qu'empirer les choses. Nous proposons une respiration guidée, de la méditation et un soutien au sommeil pour que votre corps puisse d'abord se calmer.",
      "doorsAriaLabel": "Quatre options apaisantes",
      "cta": "Voir les options",
      "before": "Votre cœur bat la chamade",
      "after": "Un système nerveux plus calme",
      "feeling": "Vous n'avez pas besoin de résoudre le problème maintenant. Vous avez juste besoin de respirer.",
      "shift": "Calmez votre corps, puis examinez à nouveau le problème.",
      "doors": [
        {
          "label": "Respire avec moi",
          "hint": "Quand vous devez ralentir votre rythme cardiaque"
        },
        {
          "label": "Médite avec moi",
          "hint": "Quand vous avez besoin de faire taire votre esprit"
        },
        {
          "label": "Dors avec moi",
          "hint": "Quand vous avez juste besoin de vous reposer"
        },
        {
          "label": "Alignez votre énergie",
          "hint": "Quand vous avez besoin de vous sentir ancré"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Sommeil et sons",
      "title": "Des sons relaxants pour les nuits blanches.",
      "body": "Lorsque votre esprit ne s'éteint pas la nuit, l'application met de côté les questions lourdes. Nous proposons des paysages sonores apaisants conçus pour vous aider à lâcher prise sur vos pensées et à vous endormir.",
      "cta": "Voir Dors avec moi",
      "before": "Rester éveillé à trop penser",
      "after": "Prêt à se reposer",
      "feeling": "« Si j'arrête de m'inquiéter pour ce problème, je perdrai le contrôle. »",
      "shift": "Laissez votre corps se reposer ce soir. Le problème peut attendre jusqu'à demain."
    },
    "privacyControl": {
      "eyebrow": "Confidentialité et contrôle",
      "title": "Vous avez toujours le contrôle de vos données.",
      "body": "L'application n'essaiera jamais de vous diagnostiquer ou de vous coller une étiquette. Toutes vos entrées sont stockées en toute sécurité sur votre appareil, et vous pouvez modifier ou supprimer n'importe quoi à tout moment.",
      "cta": "Voir la promesse de confidentialité",
      "before": "Des applications qui collectent vos données",
      "after": "100% privé et sécurisé",
      "feeling": "Vous voulez un outil utile, pas un algorithme qui vous juge.",
      "shift": "Ce n'est pas une thérapie ou un diagnostic. C'est un espace entièrement privé pour vous."
    }
  },
  "trust": {
    "eyebrow": "Confiance",
    "title": "Complètement privé. Complètement à vous.",
    "body": "Miravelys ne télécharge jamais vos entrées de journal privé sans votre permission. Vous pouvez tout supprimer définitivement.",
    "notTherapy": "Pas une thérapie. Pas un diagnostic. Juste un outil pour votre esprit."
  },
  "finale": {
    "eyebrow": "Commencer ici",
    "title": "Faites le premier pas.",
    "body": "Pas de pression. Pas de suivi des séries. Juste un endroit privé pour démêler vos pensées quand vous en avez besoin.",
    "primary": "Télécharger Miravelys",
    "secondary": "Accès anticipé"
  }
};
export const hi = {
  "hero": {
    "deviceLabel": "मिरावेलिस इंटरैक्टिव गाइड"
  },
  "journey": {
    "progressAria": "मिरावेलिस उत्पाद टूर — जैसे-जैसे आप स्क्रॉल करते हैं फोन की स्क्रीन बदलती है"
  },
  "scenes": {
    "overview": {
      "eyebrow": "मिरावेलिस क्या है",
      "title": "अपने सबसे कठिन पलों को सुलझाने के लिए एक सुरक्षित जगह।",
      "body": "कभी-कभी एक छोटी सी घटना चिंता की एक बड़ी लहर पैदा कर सकती है। मिरावेलिस आपको यह लिखने में मदद करता है कि आप क्या महसूस कर रहे हैं, तथ्यों को डरों से अलग करते हैं, और यह पता लगाते हैं कि आपका अगला कदम क्या होना चाहिए।",
      "cta": "टूर शुरू करें",
      "before": "समस्या बहुत बड़ी लगती है",
      "after": "शुरुआत करने के लिए सुरक्षित जगह",
      "feeling": "“किसी बात ने मुझे ट्रिगर कर दिया, और अब मेरा दिमाग शांत नहीं हो रहा है।”",
      "shift": "आप अभी जो भी महसूस कर रहे हैं उसी से शुरू करें।"
    },
    "writeInside": {
      "eyebrow": "लिखो",
      "title": "बिल्कुल वही लिखें जो आपको परेशान कर रहा है।",
      "body": "\"स्पष्ट रेखा\" सुविधा का उपयोग करके, आप अपनी कच्ची भावनाओं, शारीरिक प्रतिक्रियाओं या डरों को लिख सकते हैं। आपको पूरी तरह से तार्किक होने की आवश्यकता नहीं है - बस इसे अपने दिमाग से बाहर निकालें।",
      "cta": "स्पष्ट रेखा देखें",
      "before": "विचार बार-बार आ रहा है",
      "after": "आखिरकार यह दिमाग से बाहर है",
      "feeling": "“मुझे पता है कि मैं शायद ज्यादा प्रतिक्रिया दे रहा हूं, लेकिन यह अभी बहुत वास्तविक लग रहा है।”",
      "shift": "पहले इसे अपने दिमाग से बाहर निकालें। बाद में इसे समझें।"
    },
    "separateLayers": {
      "eyebrow": "परतों को अलग करें",
      "title": "तथ्यों को अपनी चिंता से अलग करें।",
      "body": "जब आप अभिभूत होते हैं, तो सब कुछ एक बड़ी आपदा जैसा लगता है। ऐप आपको यह अलग करने में मदद करता है कि वास्तव में क्या हुआ और आपका दिमाग क्या चिंतित कहानियाँ गढ़ रहा है।",
      "cta": "स्पष्ट रेखा देखें",
      "before": "सब कुछ उलझा हुआ है",
      "after": "तथ्य स्पष्ट हैं",
      "feeling": "आपके डर तथ्यों की तरह महसूस होने लगते हैं। एक ही गलती ऐसा महसूस कराती है कि वह आपकी पूरी पहचान को परिभाषित करती है।",
      "shift": "एक बार जब आप पल को छोटे हिस्सों में बांट लेते हैं, तो इसे संभालना बहुत आसान हो जाता है।"
    },
    "patternsOverTime": {
      "eyebrow": "पैटर्न पर ध्यान दें",
      "title": "समय के साथ अपने भावनात्मक पैटर्न पर ध्यान दें।",
      "body": "\"दर्पण\" सुविधा धीरे से आपकी डायरी प्रविष्टियों में आवर्ती विषयों को इंगित करती है। यह बिना आपको आंके आपके भावनात्मक ट्रिगर्स और अनुपयोगी मान्यताओं को पहचानने में आपकी सहायता करती है।",
      "cta": "दर्पण देखें",
      "before": "“ऐसा बार-बार क्यों होता है?”",
      "after": "मददगार अंतर्दृष्टि",
      "feeling": "“क्या मुझमें कोई कमी है?”",
      "shift": "अपने पैटर्न को मददगार जानकारी के रूप में देखें, न कि किसी स्थायी खामी के रूप में।"
    },
    "calmFirst": {
      "eyebrow": "पहले शरीर को शांत करें",
      "title": "पहले अपने नर्वस सिस्टम को शांत करें।",
      "body": "जब आप अत्यधिक चिंतित होते हैं, तो अपने विचारों का विश्लेषण करने का प्रयास इसे बदतर बना देता है। हम निर्देशित श्वास, ध्यान और नींद समर्थन प्रदान करते हैं ताकि आपका शरीर पहले शांत हो सके।",
      "doorsAriaLabel": "चार सुखदायक विकल्प",
      "cta": "विकल्प देखें",
      "before": "आपका दिल तेजी से धड़क रहा है",
      "after": "एक शांत तंत्रिका तंत्र",
      "feeling": "आपको अभी समस्या को हल करने की आवश्यकता नहीं है। आपको बस सांस लेने की जरूरत है।",
      "shift": "अपने शरीर को शांत करें, फिर समस्या को फिर से देखें।",
      "doors": [
        {
          "label": "मेरे साथ साँस लें",
          "hint": "जब आपको अपनी हृदय गति धीमी करने की आवश्यकता हो"
        },
        {
          "label": "मेरे साथ ध्यान करें",
          "hint": "जब आपको अपने दिमाग को शांत करने की आवश्यकता हो"
        },
        {
          "label": "मेरे साथ सोएं",
          "hint": "जब आपको बस आराम करने की आवश्यकता हो"
        },
        {
          "label": "अपनी ऊर्जा को संरेखित करें",
          "hint": "जब आपको खुद से जुड़ने की आवश्यकता हो"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "नींद और आवाज़ें",
      "title": "नींद न आने वाली रातों के लिए आरामदायक आवाज़ें।",
      "body": "जब रात में आपका दिमाग शांत नहीं होता, तो ऐप भारी सवालों को किनारे रख देता है। हम शांत साउंडस्केप प्रदान करते हैं जो आपको अपने विचारों को जाने देने और सो जाने में मदद करने के लिए डिज़ाइन किए गए हैं।",
      "cta": "मेरे साथ सोएं देखें",
      "before": "जागते हुए ज्यादा सोचना",
      "after": "आराम करने के लिए तैयार",
      "feeling": "“अगर मैं इस समस्या के बारे में चिंता करना बंद कर दूं, तो मैं नियंत्रण खो दूंगा।”",
      "shift": "आज रात अपने शरीर को आराम करने दें। समस्या कल तक इंतजार कर सकती है।"
    },
    "privacyControl": {
      "eyebrow": "गोपनीयता और नियंत्रण",
      "title": "आप हमेशा अपने डेटा के नियंत्रण में होते हैं।",
      "body": "ऐप कभी भी आपका निदान करने या आप पर लेबल लगाने की कोशिश नहीं करेगा। आपकी सभी प्रविष्टियां आपके डिवाइस पर सुरक्षित रूप से संग्रहीत की जाती हैं, और आप किसी भी समय कुछ भी संपादित या हटा सकते हैं।",
      "cta": "गोपनीयता का वादा देखें",
      "before": "ऐप जो आपका डेटा एकत्र करते हैं",
      "after": "100% निजी और सुरक्षित",
      "feeling": "आप एक उपयोगी उपकरण चाहते हैं, न कि कोई एल्गोरिदम जो आपको आंकता हो।",
      "shift": "यह कोई चिकित्सा या निदान नहीं है। यह आपके लिए पूरी तरह से एक निजी स्थान है।"
    }
  },
  "trust": {
    "eyebrow": "भरोसा",
    "title": "पूरी तरह से निजी। पूरी तरह से आपका।",
    "body": "मिरावेलिस आपकी अनुमति के बिना आपकी निजी डायरी प्रविष्टियों को कभी अपलोड नहीं करता है। आप कुछ भी स्थायी रूप से हटा सकते हैं।",
    "notTherapy": "चिकित्सा नहीं। कोई निदान नहीं। बस आपके दिमाग के लिए एक उपकरण।"
  },
  "finale": {
    "eyebrow": "यहाँ से शुरू करें",
    "title": "पहला कदम उठाएं।",
    "body": "कोई दबाव नहीं। कोई ट्रैकिंग स्ट्रीक्स नहीं। जब आपको आवश्यकता हो तो अपने विचारों को सुलझाने के लिए बस एक निजी जगह।",
    "primary": "मिरावेलिस डाउनलोड करें",
    "secondary": "जल्दी पहुंच"
  }
};
export const zh = {
  "hero": {
    "deviceLabel": "Miravelys 互动指南"
  },
  "journey": {
    "progressAria": "Miravelys 产品导览 — 手机屏幕随着您的滚动而变化"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Miravelys 是什么",
      "title": "一个帮助您理清最艰难时刻的安全空间。",
      "body": "有时，一件小事会引发巨大的焦虑漩涡。Miravelys 帮助您写下您的感受，将事实与恐惧区分开来，并弄清楚您的下一步。",
      "cta": "开始导览",
      "before": "问题感觉很严重",
      "after": "一个安全的起点",
      "feeling": "“有些事情触发了我，现在我的大脑无法停止运转。”",
      "shift": "从您现在的任何感受开始。"
    },
    "writeInside": {
      "eyebrow": "写下来",
      "title": "准确写下困扰您的事情。",
      "body": "使用“清晰线索”功能，您可以写下您最真实的感受、身体反应或恐惧。您不需要绝对合乎逻辑——只要把它从脑海中释放出来。",
      "cta": "查看 清晰线索",
      "before": "思绪一直卡在重复中",
      "after": "终于从脑海中释放出来了",
      "feeling": "“我知道我可能反应过度了，但现在感觉如此真实。”",
      "shift": "首先把它从脑子里拿出来。然后再去理解它。"
    },
    "separateLayers": {
      "eyebrow": "分层解析",
      "title": "将事实与您的焦虑区分开来。",
      "body": "当您不知所措时，一切感觉都像是一场大灾难。该应用程序帮助您将实际发生的事情与您大脑编造的焦虑故事区分开来。",
      "cta": "探索 清晰线索",
      "before": "一切都纠缠在一起",
      "after": "事实很清楚",
      "feeling": "您的恐惧开始感觉像是事实。一个错误感觉就像它定义了您的整个身份。",
      "shift": "一旦您将这个时刻分解，它就变得容易处理得多了。"
    },
    "patternsOverTime": {
      "eyebrow": "注意模式",
      "title": "随着时间的推移注意您的情绪模式。",
      "body": "“镜子”功能会温和地指出您日记条目中反复出现的主题。它帮助您识别情绪触发点和无益的信念，而不会评判您。",
      "cta": "查看 镜子",
      "before": "“为什么这种情况不断发生？”",
      "after": "有用的见解",
      "feeling": "“我是不是有什么问题？”",
      "shift": "将您的模式视为有用的信息，而不是永久的缺陷。"
    },
    "calmFirst": {
      "eyebrow": "首先平静身体",
      "title": "首先平静您的神经系统。",
      "body": "当您极度焦虑时，试图分析您的想法会使其变得更糟。我们提供引导式呼吸、冥想和睡眠支持，让您的身体可以首先平静下来。",
      "doorsAriaLabel": "四个舒缓的选项",
      "cta": "查看选项",
      "before": "您的心跳加速",
      "after": "更平静的神经系统",
      "feeling": "您现在不需要解决问题。您只需要呼吸。",
      "shift": "平静您的身体，然后再次审视问题。",
      "doors": [
        {
          "label": "与我呼吸",
          "hint": "当您需要减慢心率时"
        },
        {
          "label": "与我一起冥想",
          "hint": "当您需要让头脑安静时"
        },
        {
          "label": "和我一起入睡",
          "hint": "当您只需要休息时"
        },
        {
          "label": "调整你的能量",
          "hint": "当您需要感觉脚踏实地时"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "睡眠和声音",
      "title": "失眠之夜的放松声音。",
      "body": "当您的头脑在晚上无法关闭时，应用程序会将沉重的问题放在一边。我们提供平静的声景，旨在帮助您放下思绪并入睡。",
      "cta": "查看 和我一起入睡",
      "before": "醒着躺着想太多",
      "after": "准备休息",
      "feeling": "“如果我停止担心这个问题，我就会失去控制。”",
      "shift": "让您的身体今晚休息。问题可以等到明天。"
    },
    "privacyControl": {
      "eyebrow": "隐私和控制",
      "title": "您始终控制着您的数据。",
      "body": "应用程序永远不会试图诊断您或给您贴上标签。您的所有条目都安全地存储在您的设备上，您可以随时编辑或删除任何内容。",
      "cta": "查看隐私承诺",
      "before": "收集您数据的应用程序",
      "after": "100% 私密和安全",
      "feeling": "您想要一个有用的工具，而不是一个评判您的算法。",
      "shift": "这不是治疗或诊断。这是为您提供的完全私密的空间。"
    }
  },
  "trust": {
    "eyebrow": "信任",
    "title": "完全私密。完全属于您。",
    "body": "未经您的许可，Miravelys 绝不会上传您的私人日记条目。您可以永久删除任何内容。",
    "notTherapy": "不是治疗。不是诊断。只是为您的心灵准备的工具。"
  },
  "finale": {
    "eyebrow": "从这里开始",
    "title": "迈出第一步。",
    "body": "没有压力。没有打卡记录。只是一个在您需要时理清思绪的私人场所。",
    "primary": "下载 Miravelys",
    "secondary": "抢先体验"
  }
};
export const de = {
  "hero": {
    "deviceLabel": "Miravelys Interaktiver Leitfaden"
  },
  "journey": {
    "progressAria": "Miravelys Produkttour — Der Telefonbildschirm ändert sich beim Scrollen"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Was Miravelys ist",
      "title": "Ein sicherer Ort, um Ihre schwersten Momente zu entwirren.",
      "body": "Manchmal kann ein kleines Ereignis eine massive Angstspirale auslösen. Miravelys hilft Ihnen aufzuschreiben, was Sie fühlen, Fakten von Ängsten zu trennen und herauszufinden, was Ihr nächster Schritt ist.",
      "cta": "Tour beginnen",
      "before": "Das Problem fühlt sich riesig an",
      "after": "Ein sicherer Ort für den Anfang",
      "feeling": "„Etwas hat mich getriggert und jetzt rasen meine Gedanken.“",
      "shift": "Fangen Sie mit dem an, was Sie gerade fühlen."
    },
    "writeInside": {
      "eyebrow": "Aufschreiben",
      "title": "Schreiben Sie genau auf, was Sie stört.",
      "body": "Mit der Funktion „Klare Linie“ können Sie Ihre rohen Emotionen, körperlichen Reaktionen oder Ängste aufschreiben. Sie müssen nicht perfekt logisch sein – bekommen Sie es einfach aus dem Kopf.",
      "cta": "Siehe Klare Linie",
      "before": "Der Gedanke hängt in einer Schleife",
      "after": "Es ist endlich aus Ihrem Kopf",
      "feeling": "„Ich weiß, dass ich vielleicht überreagiere, aber es fühlt sich jetzt so real an.“",
      "shift": "Holen Sie es zuerst aus dem Kopf. Verstehen Sie es später."
    },
    "separateLayers": {
      "eyebrow": "Schichten trennen",
      "title": "Trennen Sie die Fakten von Ihrer Angst.",
      "body": "Wenn Sie überwältigt sind, fühlt sich alles wie eine große Katastrophe an. Die App hilft Ihnen, das zu trennen, was tatsächlich passiert ist, von den ängstlichen Geschichten, die Ihr Verstand erfindet.",
      "cta": "Klare Linie erkunden",
      "before": "Alles ist miteinander verheddert",
      "after": "Die Fakten sind klar",
      "feeling": "Ihre Ängste beginnen sich wie Fakten anzufühlen. Ein einziger Fehler fühlt sich an, als würde er Ihre gesamte Identität definieren.",
      "shift": "Sobald Sie den Moment aufschlüsseln, wird er viel einfacher zu bewältigen."
    },
    "patternsOverTime": {
      "eyebrow": "Muster erkennen",
      "title": "Beachten Sie Ihre emotionalen Muster im Laufe der Zeit.",
      "body": "Die Funktion „Spiegel“ weist Sie sanft auf wiederkehrende Themen in Ihren Tagebucheinträgen hin. Sie hilft Ihnen, emotionale Auslöser und wenig hilfreiche Überzeugungen zu erkennen, ohne Sie zu verurteilen.",
      "cta": "Siehe Spiegel",
      "before": "„Warum passiert das immer wieder?“",
      "after": "Hilfreiche Einsichten",
      "feeling": "„Stimmt etwas mit mir nicht?“",
      "shift": "Sehen Sie Ihre Muster als hilfreiche Informationen, nicht als permanenten Fehler."
    },
    "calmFirst": {
      "eyebrow": "Zuerst den Körper beruhigen",
      "title": "Beruhigen Sie zuerst Ihr Nervensystem.",
      "body": "Wenn Sie sehr ängstlich sind, macht der Versuch, Ihre Gedanken zu analysieren, es nur noch schlimmer. Wir bieten geführte Atemübungen, Meditation und Schlafunterstützung an, damit sich Ihr Körper zuerst beruhigen kann.",
      "doorsAriaLabel": "Vier beruhigende Optionen",
      "cta": "Optionen ansehen",
      "before": "Ihr Herz rast",
      "after": "Ein ruhigeres Nervensystem",
      "feeling": "Sie müssen das Problem nicht sofort lösen. Sie müssen nur atmen.",
      "shift": "Beruhigen Sie Ihren Körper und schauen Sie sich dann das Problem noch einmal an.",
      "doors": [
        {
          "label": "Atme mit mir",
          "hint": "Wenn Sie Ihre Herzfrequenz verlangsamen müssen"
        },
        {
          "label": "Meditiere mit mir",
          "hint": "Wenn Sie Ihren Geist beruhigen müssen"
        },
        {
          "label": "Schlaf mit mir",
          "hint": "Wenn Sie sich einfach nur ausruhen müssen"
        },
        {
          "label": "Richten Sie Ihre Energie aus",
          "hint": "Wenn Sie sich geerdet fühlen müssen"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Schlaf und Klänge",
      "title": "Entspannende Klänge für schlaflose Nächte.",
      "body": "Wenn Ihr Verstand nachts nicht abschalten will, legt die App die schweren Fragen beiseite. Wir bieten beruhigende Klanglandschaften, die Ihnen helfen sollen, Ihre Gedanken loszulassen und einzuschlafen.",
      "cta": "Siehe Schlaf mit mir",
      "before": "Wachliegen und zu viel nachdenken",
      "after": "Bereit zum Ausruhen",
      "feeling": "„Wenn ich aufhöre, mir über dieses Problem Sorgen zu machen, verliere ich die Kontrolle.“",
      "shift": "Lassen Sie Ihren Körper heute Nacht ruhen. Das Problem kann bis morgen warten."
    },
    "privacyControl": {
      "eyebrow": "Privatsphäre und Kontrolle",
      "title": "Sie haben immer die Kontrolle über Ihre Daten.",
      "body": "Die App wird niemals versuchen, Sie zu diagnostizieren oder Ihnen ein Etikett aufzukleben. Alle Ihre Einträge werden sicher auf Ihrem Gerät gespeichert, und Sie können alles jederzeit bearbeiten oder löschen.",
      "cta": "Datenschutzversprechen ansehen",
      "before": "Apps, die Ihre Daten sammeln",
      "after": "100% privat und sicher",
      "feeling": "Sie möchten ein hilfreiches Werkzeug, keinen Algorithmus, der Sie verurteilt.",
      "shift": "Dies ist keine Therapie oder Diagnose. Es ist ein völlig privater Raum für Sie."
    }
  },
  "trust": {
    "eyebrow": "Vertrauen",
    "title": "Völlig privat. Ganz Ihres.",
    "body": "Miravelys lädt Ihre privaten Tagebucheinträge niemals ohne Ihre Erlaubnis hoch. Sie können alles dauerhaft löschen.",
    "notTherapy": "Keine Therapie. Keine Diagnose. Nur ein Werkzeug für Ihren Geist."
  },
  "finale": {
    "eyebrow": "Hier beginnen",
    "title": "Machen Sie den ersten Schritt.",
    "body": "Kein Druck. Keine Streaks, die verfolgt werden. Nur ein privater Ort, um Ihre Gedanken zu entwirren, wenn Sie es brauchen.",
    "primary": "Miravelys herunterladen",
    "secondary": "Vorabzugang"
  }
};
export const ja = {
  "hero": {
    "deviceLabel": "Miravelysインタラクティブガイド"
  },
  "journey": {
    "progressAria": "Miravelys製品ツアー — スクロールに合わせてスマートフォンの画面が変わります"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Miravelysとは",
      "title": "一番辛い瞬間を解きほぐすための、安全な場所。",
      "body": "小さな出来事が、時に大きな不安の連鎖を引き起こすことがあります。Miravelysは、あなたが感じていることを書き出し、事実と恐れを切り離し、次のステップを見つけ出すお手伝いをします。",
      "cta": "ツアーを始める",
      "before": "問題がとてつもなく大きく感じる",
      "after": "始めるための安全な場所",
      "feeling": "「何かがきっかけで、心がざわついて止まらない。」",
      "shift": "今、あなたが感じていることから始めてください。"
    },
    "writeInside": {
      "eyebrow": "書き出す",
      "title": "あなたを悩ませていることを正確に書き出してください。",
      "body": "「明確なライン」機能を使用すると、ありのままの感情、身体の反応、恐れなどを書き留めることができます。完全に論理的である必要はありません。ただ頭の中から出してみてください。",
      "cta": "明確なラインを見る",
      "before": "思考が堂々巡りしている",
      "after": "ようやく頭の中から出せた",
      "feeling": "「過剰反応かもしれないと分かっているけれど、今はこれがとてもリアルに感じる。」",
      "shift": "まずは頭の中から出してください。理解するのは後で大丈夫です。"
    },
    "separateLayers": {
      "eyebrow": "レイヤーを分ける",
      "title": "事実と不安を切り離す。",
      "body": "圧倒されているとき、すべてが大きな災難のように感じられます。アプリは、実際に起こったことと、心が作り出している不安な物語を切り離すお手伝いをします。",
      "cta": "明確なラインを探索する",
      "before": "すべてが絡み合っている",
      "after": "事実がクリアになる",
      "feeling": "恐れが事実のように感じ始めます。一つのミスが、自分のアイデンティティすべてを決定づけるように感じられます。",
      "shift": "瞬間を分解すれば、対処はずっと簡単になります。"
    },
    "patternsOverTime": {
      "eyebrow": "パターンに気づく",
      "title": "時間とともに自分の感情のパターンに気づく。",
      "body": "「ミラー」機能は、ジャーナルエントリの繰り返されるテーマを優しく指摘します。あなたを批判することなく、感情の引き金や役に立たない信念を認識するのに役立ちます。",
      "cta": "ミラーを見る",
      "before": "「なぜこれが何度も起こるのだろう？」",
      "after": "役立つ洞察",
      "feeling": "「私に何か問題があるのだろうか？」",
      "shift": "パターンを永久的な欠点としてではなく、役立つ情報として捉えてください。"
    },
    "calmFirst": {
      "eyebrow": "まず体を落ち着かせる",
      "title": "まず、神経系を落ち着かせましょう。",
      "body": "非常に不安なとき、自分の考えを分析しようとすると状況はさらに悪化します。体が先に落ち着けるよう、ガイド付きの呼吸法、瞑想、睡眠サポートを提供します。",
      "doorsAriaLabel": "4つのリラックスできるオプション",
      "cta": "オプションを見る",
      "before": "心臓がドキドキしている",
      "after": "落ち着いた神経系",
      "feeling": "今すぐ問題を解決する必要はありません。ただ呼吸をすればいいのです。",
      "shift": "体を落ち着かせてから、もう一度問題を見てください。",
      "doors": [
        {
          "label": "一緒に呼吸",
          "hint": "心拍数を落としたいとき"
        },
        {
          "label": "一緒に瞑想しましょう",
          "hint": "心を静めたいとき"
        },
        {
          "label": "一緒に眠る",
          "hint": "ただ休みたいとき"
        },
        {
          "label": "エネルギーを整える",
          "hint": "地に足が着いていると感じたいとき"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "睡眠と音",
      "title": "眠れない夜のためのリラックスできる音。",
      "body": "夜、心が休まらないとき、アプリは重い質問を脇に置きます。思考を手放し、眠りにつくのを助けるためにデザインされた、落ち着くサウンドスケープを提供します。",
      "cta": "一緒に眠るを見る",
      "before": "考えすぎて眠れない",
      "after": "休む準備ができた",
      "feeling": "「この問題について心配するのをやめたら、コントロールを失ってしまう。」",
      "shift": "今夜は体を休ませましょう。問題は明日まで待つことができます。"
    },
    "privacyControl": {
      "eyebrow": "プライバシーとコントロール",
      "title": "あなたは常に自分のデータを管理しています。",
      "body": "アプリがあなたを診断したり、レッテルを貼ったりすることは決してありません。すべてのエントリはデバイスに安全に保存され、いつでも何でも編集または削除できます。",
      "cta": "プライバシーの約束を見る",
      "before": "データを収集するアプリ",
      "after": "100%プライベートで安全",
      "feeling": "あなたが欲しいのは役立つツールであり、あなたを評価するアルゴリズムではありません。",
      "shift": "これは治療や診断ではありません。あなただけの完全にプライベートな空間です。"
    }
  },
  "trust": {
    "eyebrow": "信頼",
    "title": "完全にプライベート。完全にあなたのもの。",
    "body": "Miravelysは、あなたの許可なくプライベートなジャーナルエントリをアップロードすることは決してありません。何でも完全に削除できます。",
    "notTherapy": "治療ではありません。診断ではありません。あなたの心のためのただのツールです。"
  },
  "finale": {
    "eyebrow": "ここから始める",
    "title": "最初の一歩を踏み出そう。",
    "body": "プレッシャーはありません。記録をつける必要もありません。必要なときに思考を整理するための、プライベートな場所があるだけです。",
    "primary": "Miravelysをダウンロード",
    "secondary": "早期アクセス"
  }
};
export const es = {
  "hero": {
    "deviceLabel": "Guía interactiva de Miravelys"
  },
  "journey": {
    "progressAria": "Recorrido por el producto Miravelys: la pantalla del teléfono cambia a medida que te desplazas"
  },
  "scenes": {
    "overview": {
      "eyebrow": "Qué es Miravelys",
      "title": "Un lugar seguro para desenredar tus momentos más difíciles.",
      "body": "A veces, un pequeño evento puede desencadenar una espiral masiva de ansiedad. Miravelys te ayuda a escribir lo que sientes, separar los hechos de los miedos y descubrir tu próximo paso.",
      "cta": "Comenzar el recorrido",
      "before": "El problema se siente enorme",
      "after": "Un lugar seguro para empezar",
      "feeling": "«Algo me provocó y ahora mi mente no deja de dar vueltas.»",
      "shift": "Empieza con lo que sea que estés sintiendo en este momento."
    },
    "writeInside": {
      "eyebrow": "Escríbelo",
      "title": "Escribe exactamente lo que te molesta.",
      "body": "Con la función «Línea clara», puedes escribir tus emociones puras, reacciones físicas o miedos. No necesitas ser perfectamente lógico, solo sácalo de tu cabeza.",
      "cta": "Ver Línea clara",
      "before": "El pensamiento está atascado en repetición",
      "after": "Finalmente está fuera de tu cabeza",
      "feeling": "«Sé que podría estar exagerando, pero se siente muy real en este momento.»",
      "shift": "Sácalo de tu cabeza primero. Dale sentido más tarde."
    },
    "separateLayers": {
      "eyebrow": "Separar las capas",
      "title": "Separa los hechos de tu ansiedad.",
      "body": "Cuando te sientes abrumado, todo parece un gran desastre. La aplicación te ayuda a separar lo que realmente sucedió de las historias ansiosas que tu mente está inventando.",
      "cta": "Explorar Línea clara",
      "before": "Todo está enredado",
      "after": "Los hechos están claros",
      "feeling": "Tus miedos empiezan a sentirse como hechos. Un solo error se siente como si definiera toda tu identidad.",
      "shift": "Una vez que desglosas el momento, se vuelve mucho más fácil de manejar."
    },
    "patternsOverTime": {
      "eyebrow": "Notar patrones",
      "title": "Nota tus patrones emocionales con el tiempo.",
      "body": "La función «Espejo» señala suavemente temas recurrentes en tus entradas de diario. Te ayuda a reconocer desencadenantes emocionales y creencias poco útiles sin juzgarte.",
      "cta": "Ver Espejo",
      "before": "«¿Por qué sigue pasando esto?»",
      "after": "Perspectivas útiles",
      "feeling": "«¿Hay algo mal conmigo?»",
      "shift": "Mira tus patrones como información útil, no como un defecto permanente."
    },
    "calmFirst": {
      "eyebrow": "Calmar el cuerpo primero",
      "title": "Calma tu sistema nervioso primero.",
      "body": "Cuando estás muy ansioso, intentar analizar tus pensamientos lo empeora. Ofrecemos respiración guiada, meditación y apoyo para dormir para que tu cuerpo pueda calmarse primero.",
      "doorsAriaLabel": "Cuatro opciones relajantes",
      "cta": "Ver las opciones",
      "before": "Tu corazón está acelerado",
      "after": "Un sistema nervioso más tranquilo",
      "feeling": "No necesitas resolver el problema en este momento. Solo necesitas respirar.",
      "shift": "Calma tu cuerpo, luego vuelve a mirar el problema.",
      "doors": [
        {
          "label": "Respira conmigo",
          "hint": "Cuando necesitas disminuir tu ritmo cardíaco"
        },
        {
          "label": "Medita conmigo",
          "hint": "Cuando necesitas aquietar tu mente"
        },
        {
          "label": "Duerme conmigo",
          "hint": "Cuando solo necesitas descansar"
        },
        {
          "label": "Alinea tu energía",
          "hint": "Cuando necesitas sentirte conectado a la tierra"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Sueño y sonidos",
      "title": "Sonidos relajantes para noches de insomnio.",
      "body": "Cuando tu mente no se apaga por la noche, la aplicación deja de lado las preguntas difíciles. Ofrecemos paisajes sonoros relajantes diseñados para ayudarte a dejar ir tus pensamientos y conciliar el sueño.",
      "cta": "Ver Duerme conmigo",
      "before": "Despierto pensando demasiado",
      "after": "Listo para descansar",
      "feeling": "«Si dejo de preocuparme por este problema, perderé el control.»",
      "shift": "Deja que tu cuerpo descanse esta noche. El problema puede esperar hasta mañana."
    },
    "privacyControl": {
      "eyebrow": "Privacidad y control",
      "title": "Tú siempre tienes el control de tus datos.",
      "body": "La aplicación nunca intentará diagnosticarte o ponerte una etiqueta. Todas tus entradas se almacenan de forma segura en tu dispositivo, y puedes editar o eliminar cualquier cosa en cualquier momento.",
      "cta": "Ver la promesa de privacidad",
      "before": "Aplicaciones que recopilan tus datos",
      "after": "100% privado y seguro",
      "feeling": "Quieres una herramienta útil, no un algoritmo que te juzgue.",
      "shift": "Esto no es terapia o un diagnóstico. Es un espacio completamente privado para ti."
    }
  },
  "trust": {
    "eyebrow": "Confianza",
    "title": "Completamente privado. Completamente tuyo.",
    "body": "Miravelys nunca sube tus entradas de diario privadas sin tu permiso. Puedes eliminar cualquier cosa permanentemente.",
    "notTherapy": "No es terapia. No es un diagnóstico. Solo una herramienta para tu mente."
  },
  "finale": {
    "eyebrow": "Empieza aquí",
    "title": "Da el primer paso.",
    "body": "Sin presión. Sin rachas de seguimiento. Solo un lugar privado para desenredar tus pensamientos cuando lo necesites.",
    "primary": "Descargar Miravelys",
    "secondary": "Acceso anticipado"
  }
};
export const pt = {
  "hero": {
    "deviceLabel": "Guia interativo do Miravelys"
  },
  "journey": {
    "progressAria": "Tour do produto Miravelys — a tela do telefone muda conforme você rola"
  },
  "scenes": {
    "overview": {
      "eyebrow": "O que é o Miravelys",
      "title": "Um lugar seguro para desembaraçar os seus momentos mais difíceis.",
      "body": "Às vezes, um pequeno evento pode desencadear uma enorme espiral de ansiedade. O Miravelys ajuda-o a escrever o que está a sentir, a separar os fatos dos medos e a descobrir o seu próximo passo.",
      "cta": "Começar o tour",
      "before": "O problema parece enorme",
      "after": "Um lugar seguro para começar",
      "feeling": "«Alguma coisa me engatilhou, e agora a minha mente não para de acelerar.»",
      "shift": "Comece com o que quer que esteja a sentir agora mesmo."
    },
    "writeInside": {
      "eyebrow": "Escreva",
      "title": "Escreva exatamente o que o está a incomodar.",
      "body": "Usando a funcionalidade «Linha clara», pode escrever as suas emoções brutas, reações físicas ou medos. Não precisa ser perfeitamente lógico — apenas tire isso da sua cabeça.",
      "cta": "Ver Linha clara",
      "before": "O pensamento está preso no modo de repetição",
      "after": "Finalmente saiu da sua cabeça",
      "feeling": "«Sei que posso estar a exagerar, mas parece tão real agora.»",
      "shift": "Tire isso da sua cabeça primeiro. Faça sentido disso depois."
    },
    "separateLayers": {
      "eyebrow": "Separar as camadas",
      "title": "Separe os fatos da sua ansiedade.",
      "body": "Quando está sobrecarregado, tudo parece um grande desastre. A aplicação ajuda-o a separar o que realmente aconteceu das histórias ansiosas que a sua mente está a inventar.",
      "cta": "Explorar a Linha clara",
      "before": "Tudo está emaranhado",
      "after": "Os fatos são claros",
      "feeling": "Os seus medos começam a parecer fatos. Um único erro parece que define toda a sua identidade.",
      "shift": "Depois de decompor o momento, torna-se muito mais fácil de lidar."
    },
    "patternsOverTime": {
      "eyebrow": "Notar padrões",
      "title": "Note os seus padrões emocionais ao longo do tempo.",
      "body": "A funcionalidade «Espelho» aponta gentilmente temas recorrentes nas suas entradas de diário. Ajuda-o a reconhecer gatilhos emocionais e crenças inúteis sem o julgar.",
      "cta": "Ver Espelho",
      "before": "«Por que isto continua a acontecer?»",
      "after": "Informações úteis",
      "feeling": "«Há algo de errado comigo?»",
      "shift": "Veja os seus padrões como informações úteis, não como uma falha permanente."
    },
    "calmFirst": {
      "eyebrow": "Acalmar o corpo primeiro",
      "title": "Acalme o seu sistema nervoso primeiro.",
      "body": "Quando está muito ansioso, tentar analisar os seus pensamentos só piora as coisas. Oferecemos respiração guiada, meditação e apoio ao sono para que o seu corpo possa acalmar-se primeiro.",
      "doorsAriaLabel": "Quatro opções relaxantes",
      "cta": "Ver as opções",
      "before": "O seu coração está a bater forte",
      "after": "Um sistema nervoso mais calmo",
      "feeling": "Não precisa resolver o problema agora. Só precisa respirar.",
      "shift": "Acalme o seu corpo e, em seguida, olhe para o problema novamente.",
      "doors": [
        {
          "label": "Respire comigo",
          "hint": "Quando precisar diminuir o seu ritmo cardíaco"
        },
        {
          "label": "Medite comigo",
          "hint": "Quando precisar silenciar a sua mente"
        },
        {
          "label": "Durma comigo",
          "hint": "Quando só precisa descansar"
        },
        {
          "label": "Alinhe sua energia",
          "hint": "Quando precisa sentir-se aterrado"
        }
      ]
    },
    "soundsAndSleep": {
      "eyebrow": "Sono e sons",
      "title": "Sons relaxantes para noites sem dormir.",
      "body": "Quando a sua mente não se desliga à noite, a aplicação deixa as perguntas difíceis de lado. Oferecemos paisagens sonoras calmantes concebidas para o ajudar a libertar-se dos seus pensamentos e adormecer.",
      "cta": "Ver Durma comigo",
      "before": "Deitado acordado a pensar demais",
      "after": "Pronto para descansar",
      "feeling": "«Se eu parar de me preocupar com este problema, perderei o controle.»",
      "shift": "Deixe o seu corpo descansar esta noite. O problema pode esperar até amanhã."
    },
    "privacyControl": {
      "eyebrow": "Privacidade e controle",
      "title": "Você tem sempre o controle dos seus dados.",
      "body": "A aplicação nunca tentará diagnosticá-lo ou colocar-lhe um rótulo. Todas as suas entradas são armazenadas de forma segura no seu dispositivo e pode editar ou excluir qualquer coisa a qualquer momento.",
      "cta": "Ver a promessa de privacidade",
      "before": "Aplicativos que coletam os seus dados",
      "after": "100% privado e seguro",
      "feeling": "Quer uma ferramenta útil, não um algoritmo que o julgue.",
      "shift": "Isto não é terapia ou um diagnóstico. É um espaço completamente privado para si."
    }
  },
  "trust": {
    "eyebrow": "Confiança",
    "title": "Completamente privado. Completamente seu.",
    "body": "O Miravelys nunca faz o upload das suas entradas de diário privado sem a sua permissão. Pode excluir qualquer coisa permanentemente.",
    "notTherapy": "Não é terapia. Não é um diagnóstico. Apenas uma ferramenta para a sua mente."
  },
  "finale": {
    "eyebrow": "Comece aqui",
    "title": "Dê o primeiro passo.",
    "body": "Sem pressão. Sem sequências de monitoramento. Apenas um lugar privado para desembaraçar os seus pensamentos quando precisar.",
    "primary": "Transferir o Miravelys",
    "secondary": "Acesso antecipado"
  }
};

const presentationCopy = { en, ru, ro, fr, hi, zh, de, es, pt, ja };

export function resolvePresentation(lang) {
  return presentationCopy[lang] || presentationCopy.en;
}

export { presentationCopy };
export default presentationCopy;
