/** Generated by scripts/generate_app_identity_assets.py. Do not edit by hand. */
export const APP_IDENTITY_ASSETS = {
  "miravelys": {
    "faviconSvg": "/favicon.svg",
    "faviconIco": "/identities/miravelys/favicon.7dc7e212.ico",
    "icon16": "/identities/miravelys/icon-16.7dc7e212.png",
    "icon32": "/identities/miravelys/icon-32.7dc7e212.png",
    "icon48": "/identities/miravelys/icon-48.7dc7e212.png",
    "appleTouchIcon": "/identities/miravelys/apple-touch.7dc7e212.png",
    "icon192": "/identities/miravelys/icon-192.7dc7e212.png",
    "icon512": "/identities/miravelys/icon-512.7dc7e212.png",
    "ogImage": "/identities/miravelys/og.7dc7e212.jpg",
    "manifest": "/identities/miravelys/manifest.webmanifest",
    "hash": "7dc7e212"
  },
  "mirascribe": {
    "faviconSvg": null,
    "faviconIco": "/identities/mirascribe/favicon.c650d6bc.ico",
    "icon16": "/identities/mirascribe/icon-16.c650d6bc.png",
    "icon32": "/identities/mirascribe/icon-32.c650d6bc.png",
    "icon48": "/identities/mirascribe/icon-48.c650d6bc.png",
    "appleTouchIcon": "/identities/mirascribe/apple-touch.c650d6bc.png",
    "icon192": "/identities/mirascribe/icon-192.c650d6bc.png",
    "icon512": "/identities/mirascribe/icon-512.c650d6bc.png",
    "ogImage": "/identities/mirascribe/og.c650d6bc.jpg",
    "manifest": "/identities/mirascribe/manifest.webmanifest",
    "hash": "c650d6bc"
  },
  "miravoxis": {
    "faviconSvg": null,
    "faviconIco": "/identities/miravoxis/favicon.5dd1a702.ico",
    "icon16": "/identities/miravoxis/icon-16.5dd1a702.png",
    "icon32": "/identities/miravoxis/icon-32.5dd1a702.png",
    "icon48": "/identities/miravoxis/icon-48.5dd1a702.png",
    "appleTouchIcon": "/identities/miravoxis/apple-touch.5dd1a702.png",
    "icon192": "/identities/miravoxis/icon-192.5dd1a702.png",
    "icon512": "/identities/miravoxis/icon-512.5dd1a702.png",
    "ogImage": "/identities/miravoxis/og.5dd1a702.jpg",
    "manifest": "/identities/miravoxis/manifest.webmanifest",
    "hash": "5dd1a702"
  }
};
